### ISSUE TITLE
Dashboard 

### ISSUE THREAD

**Issue by ghostinhershell** [getgrav/grav#1000]
I get these 'Fetch Failed, Logged Out' error messages on the right-hand side of my screen whenever I log into Grav and view my Dashboard. This has been an issue since the update. I'm not 100% sure if this is a bug on the Admin side of things but we've tried disabling and deleting plug-ins we've installed recently and that did not solve the issue.

I've also tried
1. Clearing history, cache, cookies
2. Logging in using other browsers (Chrome, Safari, Firefox)
3. Ignoring it

![fetch failed](https://cloud.githubusercontent.com/assets/14021469/17897080/d35697ae-6920-11e6-958c-6cfabfa35d25.gif)

Not sure if this is related, but I also get this 'invalid security token' message on the login screen. I never have any issues logging in though. This might be an issue for another support ticket.
![invalid security token](https://cloud.githubusercontent.com/assets/14021469/17896969/74c1c952-6920-11e6-9862-eb928df63f9a.png)
(removed username for privacy)

Please advise and a huge thanks in advance!
- Sarto

**Comment by flaviocopes** [comment]
Hi, I fixed this yesterday (https://github.com/getgrav/grav-plugin-admin/issues/739), the fix will be available in the next release.
The problem is when you login with an user with no `admin.super` rights.

What you can do now, until the next release, is disable the "News Feed Widget" in the Admin plugin settings.

**Comment by ghostinhershell** [comment]
Thanks so much! I look forward to it.
