### ISSUE TITLE
ERROR Missing .dependencies file in user/ folder

### ISSUE THREAD

**Issue by Sogl** [getgrav/grav#1027]
Hello!

Got this error after `bin/grav install`:
```
"eval" ▒▒ ▒▒▒▒ ▒▒▒▒७▒▒▒ ▒▒▒ ▒▒▒譥▒
▒▒▒▒▒▒▒▒, ▒ᯮ▒▒塞▒▒ ▒ணࠬ▒▒▒ ▒▒▒ ▒▒▒▒▒▒ 䠩▒▒▒.
ERROR Missing .dependencies file in user/ folder
ERROR invalid YAML in .dependencies
```

Can't see any `.dependencies` file in `user` or root folder.
Tried to check grav+admin zip from offsite. The same. No `.dependencies` file.

What it wants from me?

Env:
Windows 7 x64 (hidden files enabled, also checked with Total Commander)
Grav 1.1.3
Git Bash console

**Comment by rhukster** [comment]
it's only there if you clone from github.  it's stripped out of the grav download package because it's only intended to be used by developers:

https://github.com/getgrav/grav/blob/develop/.dependencies

**Comment by Sogl** [comment]
I have more plugins. How to create this file for my situation?

Found something about `.dependencies` file only on this url:
https://learn.getgrav.org/advanced/grav-development

But nothing about how to build this file or use...

**Comment by flaviocopes** [comment]
Just check how skeletons are implementing it, for example https://github.com/getgrav/grav-skeleton-agency-site/blob/develop/.dependencies

**Comment by Sogl** [comment]
@flaviocopes I think grav docs needs tutorial how to create this file from scratch etc.

**Comment by flaviocopes** [comment]
What's your issue with it? You need to change it to list your dependencies.

But this is needed to build skeletons. I don't know from what you are writing above if this is what you need. What do you need to do?

**Comment by rogerpfaff** [comment]
I just installed grav from different approaches (zip base + admin, skeleton with theme, composer) and for the exception of the base + admin install no installation was able to download admin panel because of dependencies.

So I think here lies the unintuitive part about .dependencies, it's just not there and blocks the try-out phase by just not working as you would expect.

**Comment by rhukster** [comment]
.dependencies is primarily use by skeleton packages to include REQUIRED plugins and themes. Core grav skeleton don't include the admin on this file because it's not required to run and not all people want it 

You can install admin anywhere by just typing `bin/gpm install admin`.

**Comment by rogerpfaff** [comment]
you are right. I just tested this again with a clone from github and it works.

**Comment by flaviocopes** [comment]
@rogerpfaff what can we do to avoid confusion in the first place, in your opinion? Adding a more verbose error message explaining that Grav is already installed, instead of complaining that .dependencies is not found maybe makes the process smoother

**Comment by rogerpfaff** [comment]
@flaviocopes the only thing I can right now imagine is that I might have tried multiple times to `bin/grav install admin` because this is the only way I can reproduce the error.

I have tested it now with the zip from the website, the clean blog skeleton, a composer install and a git clone. May be this is that one thing you need to do wrong in the beginning? Or it might have been a wrong tutorial somewhere on the web.

For my part this could be closed.

**Comment by flaviocopes** [comment]
Ok, I'll try to make sure this does not confuse other people as well. Thanks

**Comment by flaviocopes** [comment]
This should work

```
$ bin/grav install
HINT Are you trying to install Grav? Grav is already installed. You
need to run this command only if you download a skeleton from GitHub
directly.

$ bin/grav install admin
HINT Are you trying to install a plugin or a theme? Make sure you use
bin/gpm install <something>, not bin/grav install. This command is only
used to install Grav skeletons.
```
