### ISSUE TITLE
Modular Templates are not working ...

### ISSUE THREAD

**Issue by ChrisGitIt** [getgrav/grav#1049]
Hi all,

i just started with GRAV and wanted to try out the modular stuff. Unfortunately, the following error message appears:

> An exception has been thrown during the rendering of a template ("Template modular/default.html.twig" is not defined.") in "modular.html.twig" at line 54

I think its very obvious, there is a missing file in antimatter/themes/modular

I just copied the default.html.twig to this folder and deleted "{% extends 'partials/base.html.twig' %}"  and everything seem to work ... somehow...

Greets,

Chris

**Comment by rhukster** [comment]
Which theme are you using? Some things might not support modular layouts as it's optional for theme developers to include this.

**Comment by ChrisGitIt** [comment]
Hi, its the default theme that comes with the grav+admin 1.1.5 version ... checked also theme "Afterburner2", but there is also no modular/default.html.twig file.

**Comment by rhukster** [comment]
Ah ok, now I got you.  Yes that's correct, there is no 'default' modular page type there is only `features`, `showcase` and `text` modular types provided by Antimatter (I think Afterburner2 also). - https://github.com/getgrav/grav-theme-antimatter/tree/develop/templates/modular

These are used in the "one-page skeleton" - https://github.com/getgrav/grav-skeleton-onepage-site/tree/develop/pages/01.home

The idea is that you can create your own modular templates for your needs.  The Antimatter theme only has these 3 as shown in the One-Page Skeleton demo: https://demo.getgrav.org/onepage-skeleton/

BTW, regular pages can be of type **default** because there is a page provided for that type in the root of templates: https://github.com/getgrav/grav-theme-antimatter/tree/develop/templates

**Comment by ChrisGitIt** [comment]
@rhukster: thanks for your feedback. It working now. I think it was an issue with the admin backend and the selection of template for a "sub modular". I will try to reproduce the problem and will open up an issue if i can reproduce it. Thanks!
