### ISSUE TITLE
Modular page: CSS grouped assets doesn't work like JS

### ISSUE THREAD

**Issue by tranduyhung** [getgrav/grav#1068]
From my modular page, I want to add JS at the bottom of BODY and add extra CSS at the bottom of HEAD. It is successful so far with JS but extra CSS. Here is my HTML structure:

```
<html>
    <head>
        {% include 'partials/head.html.twig' %}
        {% block top %}
            {{ assets.css('top') }}
        {% endblock %}
    </head>
    <body>
        {% block content %}{% endblock %}
        {% block bottom %}
            {{ assets.js('bottom') }}
        {% endblock %}
    </body>
</html>
```

Here is what inside my modular page which is an image slideshow which requires its own JS files and CSS files:

```
<div class="slideshow">
    {% for image in page.header.images %}
    <div class="slideshow-item" style="background-image: url({{ page.media.images[image].url }})"></div>
    {% endfor %}
</div>

{% do assets.addCss('theme://css/slideshow.css', { 'group': 'top' }) %}
{% do assets.addJs('theme://js/slideshow.js', {'group': 'bottom'}) %}

{% do assets.addInlineJS('
(function(){
    // Slideshow configuration here
', {'group':'bottom'}) %}
```

slideshow.js and inline JS are added to bottom block successfully, but slideshow.css is not added to top block.

Can we do this with CSS? Or do I do something wrong here? Thanks!

**Comment by rhukster** [comment]
CSS is only valid in the <head /> tag sonteallly it makes no sense to support groups.

**Comment by tranduyhung** [comment]
In https://learn.getgrav.org/themes/asset-manager#grouped-assets group is supported for both JS and CSS. Maybe I misunderstand it?

**Comment by rhukster** [comment]
Oh sorry, misread your request. Thought you were asking about CSS at the bottom of the page. You should be able to do what you want by adding appropriate blocks in your theme.  However, this is not trivial for modular pages.  This is because that twig is processed during the content render, and after it's cached, it's not reprocessed.  Also You would have to be able to extend the base template in order to add the twig.  For this reason, you should put the CSS/JS in the top level modular page, not the modular sub-pages.

**Comment by tranduyhung** [comment]
I see. Thank you for the info!
