### ISSUE TITLE
spelling of <link> tag in assets

### ISSUE THREAD

**Issue by tidiview** [getgrav/grav#1075]
_Please forgive if this sounds stupid_
the `<link>` tag is actually ouput like `<link .... / >` while it seems that the `/` is not strickly necessary.
see [here](http://www.w3schools.com/tags/tag_link.asp) for reference
same thing can be said for `<meta>` tag
thanks in advance

**Comment by OleVik** [comment]
It is not strictly necessary, but necessary for strict HTML. That is XHTML, the stricter standard wherein

> Empty elements must either have an end tag or the start tag must end with />. For instance, `<br/>` or `<hr></hr>`. [W3Spec](http://www.w3.org/TR/xhtml1/#h-4.6).

**Comment by w00fz** [comment]
You are right that the spec says not to close `link` elements since they are `void` elements, however this refers to HTML5 doctypes only ([reference](https://www.w3.org/TR/html5/document-metadata.html#the-link-element)).

Although I'm quite positive all themes available for Grav today have a HTML5 doctype, I am not quite sure it is safe to assume so.
Browsers can understand an HTML5 doctype with a closing tag for `link`, but I don't think they would understand  a `link` without a closing tag in XHTML mode.

If you'd like to investigate this further and share your finds, we can definitely change this behavior. As it is now, although it's not strict, I believe it has a wider range support.

**Comment by tidiview** [comment]
OK I understood that having the `/` is cleaner than not to have it: difference between `HTML` and `XHTML`.
Thanks for closing the issue.

**Comment by mahagr** [comment]
There is also another benefit on closing the tags: most xml readers are really bad with html, including the one used in PHP. Closing tags makes life just much easier if you are trying to parse external site from another script.
