### ISSUE TITLE
Grav is inserting a "Pragma : no-cache" header which breaks mod_pagespeed

### ISSUE THREAD

**Issue by craigward** [getgrav/grav#1081]
I've been trying to narrow down an issue I am having getting `mod_pagespeed` working. I seem to have narrowed it down to Grav but can't find a way to stop this header.

I have a site at www.thinkoptimised.com which has `mod_pagespeed` running, however I don't get the pagespeed header present on the response for the homepage. However I have also setup a http://www.thinkoptimised.com/example.html and http://www.thinkoptimised.com/example.php served from the same folder as the Grav index.php. For both the examples pages pagespeed is working correctly and the responses show the "X-Mod-Pagespeed : 1.11.33.2-0" header.

Trying to unset the header in the htaccess doesn't solve the issue.

**Comment by Perlkonig** [comment]
Both of those URLs are returning `404 NOT FOUND`, which any web server would mark as "no-cache". Looks like there's a more fundamental problem happening.

**Comment by craigward** [comment]
Sorry, I deleted the files :/

I have just added them again so you can see.

www.thinkoptimised.com/example.html and www.thinkoptimised.com/example.php both generate the "X-Mod-Pagespeed : 1.11.33.2-0" header

www.thinkoptimised.com doesn't have the header. Everything is running out of the same directory

**Comment by Perlkonig** [comment]
If you search the source code, the only time `pragma` appears is with `cache`. I'm not a Grav dev, but it seems to me more likely that there's a server configuration issue. You may wish to [visit the forums](https://getgrav.org/forum) and see if anybody else is using mod_pagespeed. It's hard to say without seeing all the config files. Have you tried fully disabling the Grav cache and seeing if that changes anything?

**Comment by craigward** [comment]
I've posted https://getgrav.org/forum#!/general:grav-is-inserting-a-pragma

I looked through the code and couldn't see anything where it is being set. But pagespeed works up until the point of installation. As soon as Grav is running pagespeed stops.

**Comment by craigward** [comment]
I've managed to track down what is causing the issue.

`/system/src/Grav/Common/Grav.php` line 133 has `register_shutdown_function([$this, 'shutdown']);`

If you comment out this line mod_pagespeed springs back to life. Tested locally and now on live and I can see the effects.

I understand it would be written back in after an update, but what would be the harm in removing this line permanently for my installation of Grav?

**Comment by w00fz** [comment]
You can disable the shutdown close connection, it's a system setting.

**Comment by Perlkonig** [comment]
If you just comment out that line, you break any plugins that rely on the `onShutdown` event (if I'm understanding the source code correctly). Better is to start with setting `debugger.shutdown.close_connection` to false in `system.yaml` and see if that fixes the problem. (Though, @w00fz, why is it set to true in the default config? I assume there's a reason.) Even if that fixes the problem, it would still be helpful to know exactly what in that code is causing the problem. If there's a side effect that can be fixed, we can try to do that.

**Comment by w00fz** [comment]
It's set to true because it's supposed to work all the times, we have it as an option for this cases and to let people bail out.
I haven't directly worked on this, I know @mahagr went through a rewrite of that method. I am not familiar with it to be honest.

This case where it breaks with `mod_pagespeed` sounds like something that should be addressed. In the meantime you can disable shutdown.

Also *note* that switching off the setting shutdown is NOT going to break anything relying on the event. The event is fired even if the setting is off. This method is to allow for background activities in Grav and to speed things up, if you disable it it will still function exactly as expected, probably slightly slower.

**Comment by craigward** [comment]
I have uncommented the line from the system and set "Shutdown close connection" to "No" and I can confirm that mod_pagespeed is working.

You have no idea how long its taken me to find that out :)

**Comment by w00fz** [comment]
Sorry about that it should probably be better explained in the docs.
I also thing we should look into why `mod_pagespeed` fails here.

**Comment by craigward** [comment]
I looked at the php docs for `register_shutdown_function ` and I would guess its something to do with the call back. I couldn't see how it would modify headers though

**Comment by Perlkonig** [comment]
You commented out the line from Grav *and* set the system setting to false? Don't do both. Just change the system setting. 

If you're willing to spend a little more time, it would be helpful if you could comment out individual lines in [the shutdown function](https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Grav.php#L291-L320) so we can figure out what exactly is causing the problem.

**Comment by w00fz** [comment]
No he said he reverted the core change he made and just used the setting which still kept it all working.

**Comment by mahagr** [comment]
Our close connection function is known to break in some PHP instances as there is no bullet proof method to close the connection -- all but one method are really hacks that attempt to get client to close the connection as its something that cannot be done from anywhere else but some fastcgi installs.

The reason why we need a function to close the connection is that its the only way to do some time consuming postprocessing without slowing down page load time. Using cron is also an option, but unfortunately most sites will not use it.

**Comment by flaviocopes** [comment]
Basically if you have "_Shutdown close connection_" enabled, Grav is going to process some PHP after the page is sent to the browser. Currently the only usage I know now is the stats feature provided by the Admin plugin (the visits traker), which writes to file the "hit" after the response is sent, but we might have more in the future (and other plugins might already have some processing that I don't know about).

How that might interfere with mod_pagespeed sending the header, I don't know. Are you using php-fpm?

**Comment by craigward** [comment]
No im not using php-fpm. Everything is working fine now I have set Shutdown close connection to No

**Comment by flaviocopes** [comment]
Closing the issue then 👍

**Comment by herrminni** [comment]
I would like to re-open this issue, because the problem still exists in the current versions of grav.

A quick investigation showed, that the `Pragma: no-cache` response-header is added during the creation of the session, which happens in the `InitializeProcessor`, that calls the `init()` method on the Session object:  

![2018-02-21_21 39 43_screenshot-001](https://user-images.githubusercontent.com/948547/36528184-8a54267c-17b4-11e8-81c4-e70f7b6e8082.png)


Since the `Session` class from Grav extends the `Session` in `RocketTheme\Toolbox\Session` package, the method that adds this is in here:

Inside the `__construct()` method, the PHP function `session_cache_limiter` is called with the parameter `nocache`, which adds the `Pragma` header and others.

![2018-02-21_21 40 13_screenshot-001](https://user-images.githubusercontent.com/948547/36528185-8a6b80ec-17b4-11e8-9cc0-3a0fbe70cdf1.png)


As a quick workaround I just added `header_remove('Pragma');` inside Grav's own `Session` class at the end of `init()` function.
Since this change, the pages are cached from the browser as the Expires-, E-Tag-Headers are working now.

IMHO, the creation of a session should not imply, that each page must not be cached.
It will strongly depend, if session content is used to _change_ the page (e.g. to show the logged in user on the page, if the page supports user logins).

**Comment by drzraf** [comment]
That's a hard issue (a performance killer). Basically, `Pragma: no-cache` basically bypasses any caching (from Apache to cloudflare) for every hit of every client to every page.
If the goal is to use session, then the login plugin should set a cookie (and nothing more) **when needed**, that means only after a successful login ¹.
`Pragma` and `Set-Cookie` are showstopper for high-traffic websites.


¹ Even better: use JS LocalStorage and fallback to cookies from client not supporting javascript.

**Comment by mahagr** [comment]
I think we should add a configuration option for the session wide caching. I have already reworked session a lot allowing us to configure it much better here https://github.com/getgrav/grav/pull/1933

The pull request already supports you changing cache settings, like:

```yaml
session:
  options:
    cache_limiter: 'nocache'
```
