### ISSUE TITLE
Folder with number followed by dot unreachable

### ISSUE THREAD

**Issue by flaviocopes** [getgrav/grav#1090]
Reported by @muflone in https://github.com/getgrav/grav-plugin-admin/issues/8, posting here as more appropriate.

> I've a folder structure for various assets under /user/pages/resources/version_number/filename.zip and I'm unable to access to any resources when the folder version_number contains any dot, for example the page http://localhost/muflone/resources/0.8.5/gespeaker-0.8.5.zip raises a 404 error.
> Renaming the folder 0.8.5 in 0_8_5 everything works fine.

>changing the requested URL to http://localhost/muflone/resources/8.5/gespeaker-0.8.5.zip everything works fine, thus removing the initial 0.
>I understand this is for ordering but is there a way to keep the correct version number for the folders?

I replicated it.

Folder named `0.1.2`,
`http://localhost:8080/grav-develop/0.1.2/ssss.jpg` does not work
`http://localhost:8080/grav-develop/1.2/ssss.jpg` works

@rhukster is this something we can solve by _also_ allowing the order in a page asset route, or we can do this differently? Or we do not support this kind of folder naming?

**Comment by rhukster** [comment]
I need to look into this a bit.  I know the limitations are currently there to provide ordering with numeric value before period, and slug after.  I need to see deep it goes.

**Comment by rhukster** [comment]
Ok, so i looked into this a bit.  Here's the issue:

1. Page uses the regex `/^[0-9]+\./u` to get the the order from the first part of the folder if it's numeric, 1 or more digits, followed by period.  That is catching `0.1.2` and setting order to `0`, and folder/slug to `1.2`.

2. Your second example of `1.2` is actually setting order to `1` and folder/slug to `2`.  It _appears_ to work find, but actually it's find the image from the first `0.1.2` example, that is actually appearing to grav as `1.2`

3. I looked into allowing a custom page override to set a custom Regex for the page.  The idea being you could set something that is never found, so the first part is not treated like an order value, and the folder/slug will retain the whole thing.  However, the problem is that the way pages are built, the `slug` is built way before the page is processed, so the header, and custom regex has not been set yet.  Changing how this works would require significant rearchitecting of the core functionality that i'm not inclined to do at this point.

4. The best _workaround_ i can suggest at this time, is simply to preceed any of these version style folders with a throwaway order value. like: `0.0.8.5`, the first `0.` will be removed and used for ordering, and you are left with a folder/slug of `0.8.5` as you intended. 

5. By having this numeric prefix, ordering is set, but also visibility which is by default `true` when you have a folder prefix.  Therefore, if you don't want this behavior, you would need to also add `visibility: false` in the page header.

It's not perfect but should work.
