### ISSUE TITLE
So....What happens when I attempt to load 30,000 pages into grav.  Out of memory error?

### ISSUE THREAD

**Issue by msharron** [getgrav/grav#1099]
I opted for a flat file CMS because SQL driven CMS's fall over after 5000 posts.
It would appear the same issue occurs with Grav.
Any recommendations on getting Grav to load to 30K pages loaded into it?

**Comment by flaviocopes** [comment]
There are no hardcoded limits. If you hit a memory limit, increase the PHP allowed memory.

Check this ticket https://github.com/getgrav/grav/issues/343, people reported using Grav for lots of pages too. The main problem lies in rebuilding the cache. It's an area still with space for improvements.

**Comment by msharron** [comment]
So what do you recommend.  turning off the cache?

**Comment by flaviocopes** [comment]
30000 pages IMHO is way out of the Grav scope. 
It won't work fine and speedy out of the box, much like no SQL-driven website will work fine out of the box. 
We don't have a "plan" yet on how to optimize at such scale, though.

**Comment by msharron** [comment]
I wish I'd known that before I started development. 
I can get it working by turning off the cache and increasing the memory limit but it runs like a brick.
Maybe add an option for static site generation similar to Jekyll?

**Comment by Perlkonig** [comment]
Once it's cached, do you still have problems? You definitely want cache on. You can use a plugin like Precache to build it when you want it. 30k is a lot of pages. There are lots of static generators out there, if that's what you need. Grav isn't an SSG.

**Comment by msharron** [comment]
ooooh pre-cache?

We're breaking new ground with lead gen sites - havent tried anything on this scale before.
The setup I'm using is 34 silo's / verticals per site
Each vertical depending on the site has between 100-1000 pages.
I managed to get the sites some of the site working on a dedicated server with 800 pages per vertical.
The really dont like digital ocean droplets at that size.

I notice there are a few advanced caching options I haven't tried yet.   I'm looking at the idea of firing up the sets on the server and then pushing them out to droplets.   If all else fails, I can always look at a static site generator but I'd kind of fallen in love with Grav.  Just didn't expect to hit a hard wall like this.

**Comment by w00fz** [comment]
We did actually have some discussion about this internally. One of the ideas that came out that I really think will help is a way to have a decoupled cacher that can run independently of page hits and timestamp changes. A CLI command that can run periodically in the background and takes care of doing the hard work of caching, when needed and without interfering with the site performance.

That in combination with disabling the automatic cache altogether would mean that on a large scale site like yours the initial work of pre-caching will be slow but then progressively become faster. It would also take out of the equation any automatic re-triggering of cache when file changes, since the background "process" would take care of it.

This is all things we have discussed and keep in the back of our heads but I'm sorry to say it's not our main focus at the moment, mainly because as it's been said in other occasions, Grav is not really meant for such large scale. A DB based CMS would probably fit best in this case.

That said, we are definitely interested in improving this and to find a good balance for making Grav scale better than it actually can today.

Worth noting is that there's been some recent ongoing discussion about a SSG plugin for Grav, in case you are interested: #516

**Comment by msharron** [comment]
the reason I selected Grav is that wordpress falls over after you load in 5000 posts :)
With the pre-caching plugin I guess I need to warm it up to get the most out of it?

So I'm trying a few things.

Advanced Cache + PreCache
Also testing  

twig:
  auto_reload: false

cache:
  enabled: true
  check:
    method: none

Not clear what this options gives me
cache: check: pages  ??

I'm definitely seeing some improvements :)

**Comment by msharron** [comment]
https://github.com/barryanders/grav-plugin-blackhole   oh then there's this.

**Comment by rhukster** [comment]
The main issue is that grav caches all the page headers (frontmatter) and on a page load, it loads this data back in to memory.  This is so that it knows about all the available pages and routes, and makes them available.  This is where the top-end performance bottleneck is really coming from. 

For sites to be viable above 10,000 pages we need to find a solution so that we store this information in a format that can be retrieved as we need it, rather than all at once.

FYI, in my test site with 10,000 basic text pages and file-caching on with `cache.check.method: none` and `cache.driver: apcu`, i'm seeing load times in the 440ms range but with memory usage of 280mb.

**Comment by rhukster** [comment]
It really start's falling off from there.  Here's the result with 20,000 pages:

![home grav 2016-10-11 15-46-11](https://cloud.githubusercontent.com/assets/1084697/19289845/e71536b8-8fc9-11e6-908c-2f14bb702ff1.png)

BTW, i bumped up my PHP memory to 1024MB, and my APCu shim size to 512MB.  This is with PHP7 on a 2008 Mac Pro.

**Comment by rhukster** [comment]
BTW, there is another open thread that to keep track of regarding this topic: https://github.com/getgrav/grav/issues/343

**Comment by rhukster** [comment]
And for completeness, 30,000 pages. It does load.. but is using a lot of memory at this point, and it's getting kinda slow (nearly 2s page loads).

![home grav 2016-10-11 15-50-11](https://cloud.githubusercontent.com/assets/1084697/19289969/7d300060-8fca-11e6-8452-b036c5a2dab4.png)

**Comment by msharron** [comment]
i can live with 2 seconds load time.
i put varnish on the sever and that seems to help a LOT.

ill test your config this evening and see what happens :)

**Comment by msharron** [comment]
i'd be happy to contribute some funds towards development if that'll speed things up :)

**Comment by msharron** [comment]
update:

I've been able to get upto 34000 page install singing and dancing on a $160 digital ocean droplet.
PHP7.  Apache + CPANEL for ease of management and XVARNISH installed.

Using file cache, check method none, advanced cache plugin and pre-cache plugin.

It takes 2 seconds to load a page.  I set the VARNISH TTL to 1 year for the lols.  Once VARNISH warms up - it flies.

Currently load testing to see how many sites it will hold before falling over / getting upset with me.

**Comment by msharron** [comment]
I had to increase the memory limit to 4gb but im running 40,000 pages no problem

**Comment by rhukster** [comment]
wow that's pretty crazy :)

**Comment by msharron** [comment]
Yeah - it creaks a bit when it first fires up but once the caching kicks in and Varnish gets its teeth into it - game over ;)

**Comment by msharron** [comment]
Quick update on this.  80 sites with about 1000,000+ pages between them all.  160 GB droplet all working fine....

UNTIL

I ran out of space.  Turns out caching eats up a lot of storage.  I dont want to have to pay $320 USD.

SOLUTION

Moved the server over to Digital Oceans (France), as they have the block storage add on.   $30 for 300 GB. Speed impact should be minimal in view of the GEO location..   I'll post any news issues/solutions as I encounter them.

**Comment by rhukster** [comment]
How fast is that new block storage option on DigitalOcean?? Does it impact Grav?

Also how are you generating 1million pages??? :)

**Comment by msharron** [comment]
I'll report back on the block storage tomorrow once I've tested it thoroughly.

Regarding 1 million pages....or what ever. 

Landing pages for local SEO. e.g. Keyword + Location

1. Write 1000 words of copy.
2. Write each sentence 10 times.
3. Turn it into sentence level spintax. 
4. Output how ever many versions of the page you need
5. Use a find and replace tool like FARTIT to inject location names / phone numbers / other relevent terms en mass.
6. That creates semi unique 100% readable copy.
7. Create a macro to create the folder system / file name.
8. Dump them into your user/pages folder
9. Warm up the cache and off you go.

**Comment by msharron** [comment]
Once page rank trickles down into the pages the low-mid competition terms rank no problem.

**Comment by msharron** [comment]
Block storage works a charm, though some of my sites are now 6GB, assume thats file caching.

**Comment by matthew-dean** [comment]
I don't understand why Grav can't cache pages and serve those directly (via .htaccess)? That is, why is PHP needed for anything other than spidering and creating static content? The site is 99% static as it is.

**Comment by msharron** [comment]
i struggled a bit at the start with the same issue.   Grav is a flat file CMS, not a static site generator. 
You can turn off gravs file checks and use file cache / something like varnish to acheive a similar effect.

**Comment by matthew-dean** [comment]
I think Riot solves this by essentially writing YAML data from updated pages to a SQLite database, and then data queries are performed against the database, rather than having to scan and pre-load all the data into memory.

It seems like that's a more rational and robust approach, and would be quite scalable. What about doing that for Grav?

**Comment by Endogen** [comment]
Grav wants to store data as accessible as possible for the user. So i don't think a SQLite database is an option right now. Not possible to open the db-file with an editor and hack on it.

**Comment by Perlkonig** [comment]
What you're basically asking for is a [static site generator](https://github.com/getgrav/grav/issues/516). That would indeed be great, but that was not Grav's original intent. There are a couple of ways to scrape an existing site, as that thread discusses.

**Comment by matthew-dean** [comment]
> What you're basically asking for is a static site generator.

If you're referring to me, no, it's not what I'm asking for. I'm talking about essentially a DB-backed cache. So, @Endogen, the page data would be the source, but not on an HTTP request. Page updates would be cached to a DB, and then that would be queried, since a DB engine could more efficiently query a large dataset, as the YAML page data would be normalized as actual data structures. You could also scale a single file store to multiple DB stores, so that you could effectively load balance a Grav-based site.

**Comment by flaviocopes** [comment]
Out of the box, Grav is not going to require a database, not even SQLite. 

That said, if you want to write a plugin that takes care of this using a database, you're encouraged. There are other caching plugins in the GPM, so it's possible to improve caching in other ways too.

**Comment by rsmarples** [comment]
> Out of the box, Grav is not going to require a database, not even SQLite.

I don't think anyone is saying require it, but make it optional in the same way that php-opcode, php-apcu and php-yaml are optional things to make Grav go faster.

**Comment by Endogen** [comment]
As flaviocopes said: you are encouraged to write a plugin that does it

**Comment by GChester** [comment]
@msharron, I would love to get in contact and chat.  Seems we have some common goals.

**Comment by msharron** [comment]
Ping me on skype "markworkpc"

**Comment by msharron** [comment]
Anyone here using blackhole?  any way to gen it without the grav site being active?

**Comment by mahagr** [comment]
Btw, do you have the test data you were using in your testing @msharron ?

**Comment by rhukster** [comment]
Closing to due to inactivity
