### ISSUE TITLE
Question about apcu cache driver

### ISSUE THREAD

**Issue by maxlysenko** [getgrav/grav#1105]
Hello.
With the setting `cache.driver: auto` Grav chooses `apcu` driver if the apcu php extension is loaded, regardless of apcu settings.
For example in `php.ini` I have the following lines:
```ini
...
extension=php_apcu.dll

[apcu]
apc.enabled = 0
apc.enable_cli = 0
...
``` 
With such configuration in Debug Bar there is a message:
```
Cache: [true] Setting: [auto] Driver: [apcu]
```
So the question is how cache works in this case when apcu is disabled with `apc.enabled = 0` but Grav cache driver is `apcu`?

**Comment by flaviocopes** [comment]
Grav checks APCU (and others) with `extension_loaded()`. Is there a reason why you load it but you disable it? We could check with `ini_get()` for enabled state.

**Comment by flaviocopes** [comment]
Relevant line: https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Cache.php#L177

**Comment by maxlysenko** [comment]
Thank you for your response.
I asked this question to clarify things for myself.
But in general not every single hosting provides access and control over `php.ini` settings, so it's possible to have various combination of settings without possibility to change them.

**Comment by rhukster** [comment]
Really this has not come up before.  If you have APCu installed, generally you want to use it.  If you don't want to use it, simply change the `auto` setting to `file` or something else.  if you want to disable APCu, rather than setting `apc.enabled=0` you can simply comment out the extension entry. That way you are not loading something you are not wanting to use.  This is safer, faster, and just an all around better approach.
