### ISSUE TITLE
[add-resource] New Mobile Detect Plugin 

### ISSUE THREAD

**Issue by dimitrilongo** [getgrav/grav#1153]
I would like to add my new (first) plugin to the Grav Repository.
Here are the project details: https://github.com/dimitrilongo/grav-plugin-mobile-detect

The Grav Mobile Detect Plugin for Grav CMS : adds the ability to detect mobile devices (including tablets). Plugin use https://github.com/serbanghita/Mobile-Detect PHP Class.

**Comment by w00fz** [comment]
Very nice!
I just noticed that you have the blueprint version not matching the release version. You should also probably use semver.

In your [blueprints.yaml](https://github.com/dimitrilongo/grav-plugin-mobile-detect/blob/master/blueprints.yaml#L2) `version: 1.0.0` instead of `version: '1.0'` and then you should redo the tag/release and use `1.0.0` instead of `v1.0`.

Can you make this changes?

Thanks!

**Comment by dimitrilongo** [comment]
@w00fz thanks, version number match now.

**Comment by w00fz** [comment]
Added! Should be available soon.
