### ISSUE TITLE
Recommendation: Theme template standards

### ISSUE THREAD

**Issue by matthew-dean** [getgrav/grav#1158]
In the Grav documentation, it says:

> There are no set rules regarding the structure of a Grav theme except that there must be appropriate Twig templates provided in the templates/ folder for each of the page types you use in your content.

I would recommend changing that to the benefit of the end user. I ran into this when trying to change themes was that pages that were attached to templates that didn't have the same name/path in another theme, it caused an instant exception.

Because there are no set rules for a Grav theme, there is inherent incompatibility between themes built into Grav. In other words, Grav is currently designed for themes to fail, which isn't a great user experience and could be improved.

What I would recommend instead:

1. Establish a few very simple and limited rules for "base" templates required for a theme.
2. Publish a set of recommended guidelines for template structuring including paths and names.
3. Set a behavior in Grav that missing templates will fallback to particular default templates. (Set in No. 1)

What do you think?

**Comment by Perlkonig** [comment]
1. I'm not sure what "rules" you'd create. Depending on the content you're trying to serve, you may only need one or two templates. I guess it wouldn't be too burdensome to say all themes must have a "default" template. I'm just not sure what you gain.

2. Immediately following the quote you pulled you'll also see the following:

   > A good way to create general themes is to support the template types used by the Skeleton packages that are available on our downloads page. For example, support: default, blog, error, item, and modular.

   What additional guidance might you suggest? I agree that documentation is really important. If you use the Devtools plugin to create the theme, [you can see that it does create some basics for you](https://github.com/getgrav/grav-plugin-devtools/tree/develop/components/theme/pure-blank). That might be a good place to make changes, too.

3. Fallback sounds nice, but what would it fall back to? Let's say we mandated a "default" template but one didn't exist, should Grav use something built in? Even if some built-in fallback were created, I would rather know that something was wrong (via exception) than get unintended output. A missing template is indeed a problem to be solved.

I agree that to compete with CMSs like WordPress, theme changing needs to be as painless as possible. I'm just not sure how far the core system can go to mitigate this.

(I'm not a team member, just an avid user.)

**Comment by matthew-dean** [comment]
Even if there wasn't a clear fallback, if Grav wants to keep it's flexibility, then there should be a way to users to either cast (overwrite and change) pages to the new theme's templates, or alias (map to a theme's templates, but without changing the values in case you want to switch back).

Right now, it just breaks, and after failing to figure out where it was breaking, or figuring out an easy way to just try out the theme without a bunch of tedium, I just kind of threw up my hands and went back to the original theme.

As far as additional guidance, the part about "a good way" is good, but I would switch that to recommended, along with a list of optional recommended theme file names.

Another problem, I noticed (I think) that not only does the filename have to match, but they have to be in the same folder structure, no? I could be wrong about that.

Anyway, I think you get what I'm saying. Right now page migration between themes is very painful, and it really doesn't have to be. And because it's so painful, I think it's even a bit misleading to call them "themes", because I would say that there's a user expectation that they behave like Wordpress themes i.e. they are (mostly) interchangeable. They behave more like libraries that have a unique API.

**Comment by Perlkonig** [comment]
There is no folder structure involved. When Grav goes to the requested folder, it looks for an `X.md` file. It then looks in the `user/themes/THEME/templates` folder for `X.html.twig` and applies it, regardless of where exactly `X.md` lives.

As for modifying existing themes, [there is a best practice for that](https://learn.getgrav.org/themes/customization#theme-inheritance). It's a simple matter to symlink templates to a new name so you don't have to change your existing page data. But this does indeed require facility with the terminal. I don't use the Admin plugin, so I have no direct experience with this, but I know they are working hard to make it easy for non-command-line folks to do this sort of thing with relative ease. It's not an easy thing, though.

**Comment by paulhibbitts** [comment]
Just to add my two-cents, even just having a list of suggested core theme Twig template filenames would be helpful - I think in some ways Antimatter has served this purpose for blog sites. For non-blog sites is there a suggested list of template files/names?

One thing I've started to do in my own custom themes is to also provide a default Twig file for modular content, just to help get things going 🙂

**Comment by flaviocopes** [comment]
This is by design. A theme has much more power than what other popular CMS grant to themes. 

That's part of Grav's flexibility, a theme is not just a skin. The theme is a fundamental part of the design of the site, not just the UI but the information architecture, the functionality etc.

That's why you can't really switch themes easily, unless the themes are very general / simple. 
This is what allows Grav sites to be very different with minimal use of plugins. Consider the skeletons *RTFM*, *Receptar*, *Ceevee*, *Course Hub*, they can do what they do because the theme has special handling for special page types.
This is no different than what happens with other CMS as well, considering for example Custom Post Types in WP.

Then, it's nice if every theme could provide a default page, and a blog structure for example, but it's not required.

**Comment by rhukster** [comment]
I think this has been answered already, but for clarification:

* Grav is not a typical CMS where the theme is purely a skin over your site.  The theme is an integral part, and as Grav has no real requirements as to how you structure your site, not can the theme.

* This is by design.  Grav is built this way to ensure it's supremely flexible, and can be tailored to support any kind of site design you wish.  I believe this is one of the reasons why it's so hard to work with WordPress/Joomla/etc as they enforce strict rules on what a theme can do, what it provides, etc. Grav has no such limitations and is better for it.

* Grav makes it pretty easy to create 'skeleton' packages which are really ready-to-roll demo sites with content + configuration + plugin + theme.  This means that you can create wildly different site types and make them easy to install and modify by the end user.  This is not typically a simple thing for other platforms.

I would suggest theme designers grab a theme they wish to use as their basis, and follow the structure/templates of that theme for their own.  Antimatter is the closest thing Grav has for a kitchen-sink type theme, that can handle a single page design (via modular twig templates), blog layout, and simple pages.  That is a good model to copy if you wish to provide a more 'general' theme.
