### ISSUE TITLE
Content Cache Scheduling

### ISSUE THREAD

**Issue by Wartybliggens** [getgrav/grav#1176]
Feature Request:
1. Allow setting start and end date-times to blocks of content within a page.
2. Refresh the cache for that page whenever one of those blocks changes its visibility.

For #1, I've already made a little plugin that works. But it's not really viable if the whole page is cached. I would like to know what people think would be a good way forward for this (short of duplicating entire pages with different publish dates, which I am trying to avoid). 

In the bigger picture, a 'timed blocks' feature may seem strange, but for me (and clients) it's important from an organization perspective: being able to set not only publish start/end dates for whole pages but also for parts within it, then to be able to preview the site at different dates (which is separate need of ours). 

Imagine that a content person does the work, then needs to get approval from superiors long beforehand: "Hey boss, on the 21st the page will show up, then on the 25th it will look like this for just 24 hours, then the coupon part will go away and a 'game over' alert will show instead, then on the 30th the whole page goes away. Is that OK?"

Like I said, I already made a plugin but I'm not sure how to get around the cache issue without hacking the Grav core.  I have imagined something about a cache status list in the frontmatter that the page.php file could read and write to, like a list of cache refresh dates and true/false whether they have been completed. But that's likely crazy talk.

**Comment by Wartybliggens** [comment]
I should also say that by "within a page" I mean in the content markdown, not in the Twig templates.

**Comment by rhukster** [comment]
Have you looked at the Twig cache plugin? Would this work for you? 

https://github.com/getgrav/grav-plugin-twigcache

**Comment by Wartybliggens** [comment]
@rhukster - no, I've looked at the twig cache plugin, but that is for use in templates that developers create, and (if I understand it correctly) adds extra caching for specific blocks. What I have made is a markdown extension for use in the markdown content itself, so non-technical content creators can create 'timed blocks' within their content. But the whole-page caching gets in the way of it being usable. 

A page can have publish and un-publish dates, which is great. To support sub-page 'timed block' scheduling, I imagine the publishing dates part of the front-matter supporting a list of dates instead of a single date, and there be an additional entry saying 'last-cache-clear-date', or some such. So when the page load is after a date in the list but the last-clear date is before that date, the cache would be cleared once. That may not actually make sense in the real code but you get the idea. Something simple that plugins can read and write to.

Content scheduling is a constant real-life problem, especially for sites that don't have dedicated staff to make changes in real time. They want to set up all the upcoming content, then put the site into a future-date mode to see what it will look like (and to get approval etc.). You often see sites for smaller organizations that show announcements that have already gone stale and the 'web person' is not around to fix it. This is often the case with small pieces of a page, not the entire page.

**Comment by Perlkonig** [comment]
Even if a page is cached, Grav is still invoked. Plugins can still run, for example. A plugin could override or invalidate the cached version (see [a forum post on this topic](https://getgrav.org/forum#!/general:disable-page-cache-based-on)). I don't see how Grav could natively support this functionality without fundamentally overhauling its caching code. 

For maximum speed, I really don't see how you can avoid storing multiple versions of the page. My knee-jerk first stab at it would probably go as follows:

* When a page is requested, the plugin loads the raw page and looks for the marked blocks.
* It then looks at the current date and determines where in the "timeline" the page falls.
* Look for a cached version and deliver it if available.
* On a cache miss, do the following:
  * For each unique expiration date that falls after "now," generate and manually cache a version of the page, plus one version for "now."
    * The manual caching is relatively straightforward, but the generating is more problematic. I don't actually know how you'd do it given that you'd want the full life cycle to be run (so that custom shortcodes and other plugins have a stab at the content).
  * Return the "now" version to the client.

A slightly faster approach may be to also store the expiration data in the header so that you don't have to actually parse the page text. But that's not the most user friendly as the authors would have to mark things in multiple places.

Of course the simplest and most fool-proof approach is to simply disable caching for these pages and just let Grav do it's thing. Create a shortcode plugin that simply drops content after certain timestamps. Unless you do some benchmarking with real-world content, it's hard to say whether developing a whole plugin to cache this stuff is even worth it. ([Obligatory xkcd link](https://xkcd.com/1205/))

**Comment by Perlkonig** [comment]
Created a simple content scheduler as a "proof of concept" of sorts: https://github.com/Perlkonig/grav-plugin-scheduler

**Comment by Wartybliggens** [comment]
@Perlkonig - thank you very much for thinking through my request, and for making the POC. It's similar to mine, except mine used "$markdown->addInlineType(...)", only because I had an example to work from in the markdown color plugin. I hear you about simply not caching, but I'm thinking in terms of non-technical users who will screw it up and forget to turn off the cache. And for big high-traffic websites I would still want to have the cache handle it. If we choose Grav for our project I will have to solve this somehow (I will for whatever CMS we choose), so I'll keep you updated.

**Comment by Perlkonig** [comment]
That's a perfectly reasonable approach. Obviously the earlier the content is pruned, the less processing has to be done. If caching is essential, then the built-in cache may not be sufficient anyway. There are a couple of approaches one could take to this, depending on the caching method chosen. You could adjust TTLs, for example. The real roadblock seems to me the generating of multiple versions of the pages. Maybe I just don't understand the system well enough yet. Seems to me you'd basically have to create a separate Grav instance for each page so that the whole life cycle runs, but I don't know if that's even possible. For sure let us know what you end up doing.

**Comment by karfau** [comment]
Have you thought about using modular blocks with their own expiration date?
Not sure if this is even a valid approach, but just had this idea when reading through the issue.

**Comment by mahagr** [comment]
I'm working on taggling this issue in Grav 2.0 branch, though there's still a lot of work to make it to work.

Basically, I've created [`Grav\Framework\ContentBlock`](https://github.com/getgrav/grav/tree/2.0/system/src/Grav/Framework/ContentBlock) classes, which allow me to create nested sets of content, with possibility to have different parts of the page cached by different amount of times (classes to do that are still missing). Each block can have their own assets (including JS/CSS, maybe even resized images etc) and the nested blocks can (in the future) be cached separately from each other, having a method call backup.

This approach would allow much more flexibility than hardcoding the logic per page type (or modular in this case) as it basically allows any widgets inside the page to be dynamic or having their own caching logic.

**Comment by Wartybliggens** [comment]
@mahagr - I just saw your post today. So what you're saying is that within the markdown, we could use markers for blocks of content? That sounds good to me. I look forward to seeing where this goes.

**Comment by rhukster** [comment]
Something we're looking to improve in Grav 2.x
