### ISSUE TITLE
when grav fails, HTTP error should be returned instead of 200

### ISSUE THREAD

**Issue by AddaxSoft** [getgrav/grav#1291]
When grav fails due for example to file access error, error HTTP 200 is currently returned.
This behavior confuses health check system to think everything is alright :)

Instead an HTTP 5xx error should be returned instead, so the health check systems can trigger

**Comment by rhukster** [comment]
Whenever there's an error, i'm seeing a 500 error returned as expected.  Can you please provide an example of how to get an error with a 200 response?

**Comment by flaviocopes** [comment]
I added the `enhancement` because I could reproduce the problem, but after a bit of research this is a PHP-level thing, when `display_errors` is enabled, and/or xdebug is enabled, parse errors trigger a 200, seems so it's able to correctly display the error message.

So, not a Grav issue, but an environment setting. (see https://bugs.php.net/bug.php?id=50921)

![screen shot 2017-02-06 at 18 55 20](https://cloud.githubusercontent.com/assets/11783388/22659578/68fe7dfc-ec9e-11e6-81b7-c2f3dcf531e5.png)

After disabling errors:

![screen shot 2017-02-06 at 19 02 14](https://cloud.githubusercontent.com/assets/11783388/22659683/d43c7470-ec9e-11e6-8032-ff6f1c185eb6.png)

**Comment by AddaxSoft** [comment]
OK, here is how to reproduce the problem:
when I change the owner of all folders to root, some dirs will lose the "write" permission automatically to www-data; hence Grav will complain about not being able to write to some folders.

Instead of displaying error 500, Grav displays a normal 200 with error page that some folders are not writable.

**Comment by flaviocopes** [comment]
Oh ok that's the Problems plugin output. It can be fixed by adding a `http_response_code(500);` here: https://github.com/getgrav/grav-plugin-problems/blob/develop/problems.php#L121 

Can you check if this solves your problem?

**Comment by AddaxSoft** [comment]
@flaviocopes yes it works like expected now!
The web server returns a 500 error WITH the explanation of the error.

The health checker now reports a problem with the server in this case :)
![image](https://cloud.githubusercontent.com/assets/6898938/22684681/b2a13db2-ed1d-11e6-9a0c-c486f5c1c563.png)

![image](https://cloud.githubusercontent.com/assets/6898938/22684703/cdeb0814-ed1d-11e6-9200-73839a2a011c.png)


Thank you!
