### ISSUE TITLE
Unable to to fetch cache contents when saving on the command line

### ISSUE THREAD

**Issue by johnnoel** [getgrav/grav#1293]
I'm building a custom plugin for one of our clients and part of the requirement is caching some information (from an external API) and then using that information on subsequent requests.

Using the CLI functionality, I've created a command that can be run on a schedule; it downloads the data and then saves it to the Grav cache. However, when trying to retrieve that information on a request (so not on the command line), the cache always reported a miss.

After some investigation this seems to be because the [Cache](https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Cache.php#L123) class generates a key according to the [Uri](https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Uri.php#L66) hostname. On the command line this is short-circuited to 'localhost', while on a normal web request, this is obviously whatever the hostname is.

To reproduce: create a plugin with a CLI Command that saves some data to the Grav cache; then set the plugin to listen on any event and try to fetch the same data.

Expected behaviour: Data cached on the same Grav system would be accessible regardless of environment.

Workaround: The most straightforward way of circumventing this behaviour is to set the global cache key to something known prior to saving or fetching data e.g.

```php
$originalKey = $grav['cache']->getKey();
$grav['cache']->setKey('my-cache-key');
// do caching operations
$grav['cache']->setKey($originalKey);
```

If the Uri class adhered to the `custom_base_url` in the system.yaml configuration file then this would be a good fix while retaining existing functionality. Otherwise making sure that the cache prefix in system.yaml is used verbatim, or perhaps introducing a cache namespace configuration option would, again, solve the problem.

**Comment by rhukster** [comment]
Ok I've looked into this and found a couple of things:

1) A plugin that sets the cache key early (`onPluginsInitialized()`) and then used for both web/cli works.

2) The caveat with the above is that APC/APCu/XCache etc have seperate cache instance for each PHP process (web/cli) so even with the same cache key, they caches are independent between cli and web.  

So, i've attached a test plugin to show how you can set the cache key for both CLI and web.  It includes a simple CLI command:

```
bin/plugin cli-cache-test cache
```

to store a value in cache, then the plugin itself retrieves that and then dumps it via `dump()` command.   This plugin works with latest Grav if you have the cache setting set to `file` as this is a shared cache between both and it works fine.

Here's the plugin zip (just extract into your `user/plugins/` dir to test: 
[cli-cache-test.zip](https://github.com/getgrav/grav/files/755639/cli-cache-test.zip)

However, it makes sense that if you have an eternal cache system (memecache/redis/etc) it should work also,  So i've added a PR that only falls back to file (the prior default behavior) if the cache driver is one of the more volatile types: https://github.com/getgrav/grav/pull/1294

**Comment by rhukster** [comment]
Ok, made some updates, and have a better solution based on what you originally were mentioning.

The first solution I have technically does work with Grav as it is, but it does feel a bit kludgy.  So, i reworked it so that any plugin will just work if you set things up correctly.  With my PR all you need to do is:

1. Set an explicit `custom_base_url` path in your `system.yaml` . This will be used by the CLI (as well as web although it's redundant there) to ensure the `$uri->rootUrl(true)` as used by the cache key is in sync between CLI and Web.

2.Enable `cache: cli_compatibility: true` in your `system.yaml`.  This will ensure that both CLI and Web only use a CLI-safe cache driver.  Previously the default driver setting of 'auto' would mean the tear-down process of CLI commands cleared the cache.  So only external non-volatile cache mechanisms are allowed with this setting . ie (file, memcache, redis).. so no APCu, Xcache, etc.

So now you can take that plugin I wrote, and comment out the `CLICacheTestPlugin::setCacheKey();` line from both the plugin and the CLI command and it should work as long as you did both previous steps.

**Comment by rhukster** [comment]
Attached is latest update to the test plugin with `setKey()` removed:

[cli-cache-test.zip](https://github.com/getgrav/grav/files/758399/cli-cache-test.zip)

**Comment by rhukster** [comment]
BTW, tested with redis and that works fine also.

**Comment by johnnoel** [comment]
This is spot on perfect, thanks for your speedy solution @rhukster!
