### ISSUE TITLE
Is It Possible to Have Nested Taxonomies?

### ISSUE THREAD

**Issue by moshemo** [getgrav/grav#1304]
Is it possible to nest taxonomies?  For instance, let's assume I have a category called animals.  I now want to create sub-categories of animals -- i.e., cats, dogs, fish, etc.  Next, I'd like to create sub-sub-categories (for instance, of Dogs -- Poodles, Golden Retrievers, etc).  And so on...

Is this possible?  If so, how.  If not, is it possible to make a feature request?

Thanks.

**Comment by rhukster** [comment]
It's not possible currently.  Right now Grav has a very simple one-level taxonomy mapping. Ie, you can create an unlimited number of taxonomy types, you can assign those to pages as required.  Grav simply goes through those during the page building process and stores the route to the page under each taxonomy type.

A more sophisticated taxonomy system along with an accompanying query language to make advanced taxonomy queries is something we are interested in doing for future releases.

**Comment by hughbris** [comment]
+1 from me for this feature, never got around to submitting as an issue.

I struggle with the use of the term 'taxonomy' without any hierarchy BTW. I guess you could technically argue it's a flat hierarchy. Vocabulary would be a better term to use in the docs to manage expectations until Grav supports hierarchical vocabularies.

Until this is developed, I am considering a rough workaround using concatenated terms. The plan hasn't made it out of my head yet. If it's successful, I'll post details here.

Glad to hear this is on others' radars and a planned enhancement :)

**Comment by rhukster** [comment]
I would gladly accept a PR on this subject as long as it was 100% compatible with current flat-map-style system.

**Comment by Perlkonig** [comment]
A standard approach to creating heirarchy in a flat system is to use colons to separate levels: `animals`, `animals:dogs`, `animals:cats`, `animals:dogs:poodles`, etc. Depending on where you're trying to discern the levels and what you're trying to accomplish, you could write a plugin that looks for the colon (or whatever delimiter you want) and works its magic. If you want to use them in page collections, though, you'd have to get into the core code, methinks. But it *should* be relatively straightforward to add a "recognize hierarchy" setting (so that your code doesn't affect existing installs) and then insert code into the page collections code that does its magic based on that. Of course performance is always a concern. A plugin is better where possible. A full grown native hierarchical taxonomy structure with accompanying query language sure sounds nice, but it would have to be blazing fast.

**Comment by mahagr** [comment]
I would just create a simple plugin which would have configuration for the nested taxonomies and would then add the extra parent taxonomies based on the tags in the pages.

**Comment by syelan** [comment]
I'm not sure if this would be the same issue, but also is there a way to manage tags outside of blog or content items? A way to assign tags in batch to several content items, and to search items according to previously assigned tags?

**Comment by rhukster** [comment]
Closing to due to inactivity

**Comment by hughbris** [comment]
There still seems to be a strong case for this eventually, regardless of activity on this issue or obvious best solutions. Can't it be left open and tagged 'enhancement' plus something to indicate it needs more discussion?

I've suggested on Slack that we use a bot to notify Github activity (and importantly encourage discussion among devs _and users_) for this kind of reason.

**Comment by rhukster** [comment]
It really seems like an advanced feature that could be handled by a plugin. I think that' Grav's flat taxonomy model works fine for 99% of people, and i don't think it's worth complicating this.

If you believe you can create a PullRequest which adds this functionality without breaking the current behavior I would consider it.

**Comment by chreniuc** [comment]
@hughbris did you manage to find a plugin that does this? I just found out about grav and I started to see if I would be able to migrate from wordpress, but I got stuck when I tried to find something equivalent to subcategories from wordpress.
