### ISSUE TITLE
Feature Request: Modular Pages Ordering

### ISSUE THREAD

**Issue by phideas** [getgrav/grav#1320]
Refering to this Forum thread https://getgrav.org/forum#!/getgrav/general:modular-page-ordering

I'd like to propose this feature request: Ordering Modular Pages in similar manner as Pages Ordering works. The parent page should have a drag and drop ordering list of its Modular Pages. 

It would be very nice and usefull to have this feature in Grav.

**Comment by flaviocopes** [comment]
It's something we know should be improved, in the plans for the future 👍

**Comment by rhukster** [comment]
You can do this today with `01._modular/` folder names.

**Comment by mikecrittenden** [comment]
@rhukster I think the request is that it should be possible to be done in the UI? Right now it appears that you can re-order from each of the modules themselves, using the Advanced > Ordering section (if "Folder Numeric Prefix" is enabled), but it seems more logical that you could reorder the modules from the parent modular page itself, since that is the "container". Thoughts?

**Comment by rhukster** [comment]
This is something we plan on tackling when we redo the modular page UI.
