### ISSUE TITLE
Page Linking (target attribute) not working with special characters

### ISSUE THREAD

**Issue by axel-rank** [getgrav/grav#1399]
If you have a external link like: 
``
[link](http://www.xyz.com/folder/#page?target=_blank)
``

then the target attribute isn't working because of the  `#` 

A link like:
``
[Link](https://www.landkreis-bayreuth.de/KulturBildung/Weiterbildung/VHS-Programm.aspx?view=~/custom/vhs-kalender/details&orgid=330f1b0f-d22b-429a-a90f-679f76967836)
``  

gets processed as:

``
https://www.landkreis-bayreuth.de/KulturBildung/Weiterbildung/VHS-Programm.aspx?view=~%2Fcustom%2Fvhs-kalender%2Fdetails&orgid=330f1b0f-d22b-429a-a90f-679f76967836
``

Guess it's because of the `~` the `/` gets processed as `%2F`

and is only working if you put the link in html code in your markdown file.

**Comment by flaviocopes** [comment]
First URL issue: the fragment needs to be last. So write it like this:

`[link](http://www.xyz.com/folder/?target=_blank#page)`

Second URL issue: in the query part of the URL, the one after the ?, special characters need to be encoded. So it's a problem in the destination site, rather than in Grav. Grav processes the URL as it should be. You can write it as a normal HTML link, as you said.
