### ISSUE TITLE
is there an issue when putting it into a subfolder

### ISSUE THREAD

**Issue by rapsli** [getgrav/grav#143]
Hi there

Installed grav into www.myserver.com/podcast. The frontpage is showing just fine, but then when trying to access a subpage, e.g. http://websli.ch/podcast/blog/background-image I get a 404 from the server and not from grav. 
I'm running nginx.

Regards
Raphael

**Comment by rhukster** [comment]
Here's some general Info: http://learn.getgrav.org/troubleshooting/page-not-found

However, Nginx is a special case, it's not like Apache in that you can easily create subfolders, and drop Grav into those. For Nginx, you **must** configure a vhost config for each site or the rewrite rules will not work because it has no ability to have folder-based .htaccess type configurations. 

So in your case you will just need to create a config in your nginx server config for your /podcast folder.

**Comment by rapsli** [comment]
do you happen to have a sample nginx config with the htaccess content?

**Comment by rhukster** [comment]
should be an `nginx.conf` in the root of the grav folder

**Comment by rapsli** [comment]
still having some issues. I now put it into a subdomain. Not as nice maybe, but must do for the moment. Thanks for the quick support.

**Comment by rhukster** [comment]
Yah nginx is really not as convenient for this stuff compared to Apache :) Probably why I stick with Apache 2.4 even though Nginx is supposed to be faster, seem about the same in my testing.
