### ISSUE TITLE
How to add custom field/editor types to admin plugin

### ISSUE THREAD

**Issue by e-frank** [getgrav/grav#1438]
What is the best way to add custom editor types to admin plugin?
I want to add a wysiwig editor for textboxes, as well as more specialized selects with data from another application.
it would be great if i could register such plugin through user/plugins and then use `type: myeditor` in my blueprint.

**Comment by OleVik** [comment]
Read the [Docs on Extending Admin](https://learn.getgrav.org/admin-panel/extending), it outlines best practices for extending the Admin-plugin through a plugin, as well as how to register a custom field. Specialized editors require some special attention when constructing the field, especially in handling input and sanitizing it, and you should be aware of a strong preference for Markdown - rather than HTML - within the Grav ecosystem.

Several plugins use custom fields within their plugins. One example is the [AdminStyles-plugin](https://github.com/OleVik/grav-plugin-adminstyles) which uses a "Radio Image" field for selecting style.

**Comment by e-frank** [comment]
perfect! thank you
