### ISSUE TITLE
Weird Characters showing up on IOS

### ISSUE THREAD

**Issue by Eggeriley** [getgrav/grav#1443]
My site kegge.accessipd.com is showing up with some weird characters..It looks like it might be Gzipped but it  Gizip compression is disabled in the system.yaml file.. any help??
![image1](https://cloud.githubusercontent.com/assets/19999634/25300918/55289db0-26cf-11e7-9d21-1f2b42b3e56d.png)

**Comment by OleVik** [comment]
Where is GZip disabled, through Grav or the server?

**Comment by Eggeriley** [comment]
I never changed anything related to Gzip, but i checked the system.yaml file. under the "cache" catagory i checked and both webserver gzid and gzip is not enabled

**Comment by OleVik** [comment]
Depending on your server, Gzip may be enabled - which generally it should be for speed - and in which case you do want to enable `allow_webserver_gzip`.

**Comment by Eggeriley** [comment]
okay thank you, is there a reason why these characters would only be showing up on ios devices?

**Comment by Eggeriley** [comment]
for some reason, only certain newer ios devices have this problem.

**Comment by Eggeriley** [comment]
i set the system.yaml file to allow_webserver_gzip. no difference !! grr..

**Comment by OleVik** [comment]
Ok, some more diagnostic questions:
- Did this occur after an upgrade to Grav v1.2.3?
- What version of Gantry are you running?
- In your `.htaccess`-file in Grav's root directory, is there any `mod_deflate` set up?
- Is compression enabled through PHP? Typically set through `zlib.output_compression` in php.ini, which on a live server you can reveal through a simple file containing `<?php phpinfo(); ?>` accessed through the browser.
- Just to verify, does your system.yaml now contain the following?

```
cache:
  gzip: false
  allow_webserver_gzip: false
```

The reason it wold only show up on certain devices is because of how their browsers interpret the output from the server. Per your site, it is encoded as `Content-Encoding: identity` currently and running on Apache, both of which are normal. It also appears to have Gzipping set up through the server, as it returns `Accept-Encoding: gzip, deflate, sdch`.

The error appears to be outside of Grav, ie. between PHP and Apache, so we'll need to find more information from their setups as suggested above.

**Comment by Eggeriley** [comment]
yes it occurred after i updated to grav 1.2.3

**Comment by Eggeriley** [comment]
i the latest version of gantry 5

**Comment by rhukster** [comment]
Can you possible test an installation of Grav without Gantry5? That would help isolate the issue.

**Comment by Eggeriley** [comment]
Hey guys, thank you so much for your support, i looks like i may have fixed the issue, i am confirming with my client currently. we can close the issue and if for some reason i was mistaken and it's not fixed we can re-open it

**Comment by rhukster** [comment]
Can you let us know what it was in case it comes up again?  Cheers.

**Comment by Eggeriley** [comment]
for some reason the site was being gzipped even though i did not have it set in the system.yaml file
i had to enable "webserver gzip" then i had to clear gantry 5 cache, grav cache, and the phones browser cache.
