### ISSUE TITLE
Combine modular components of themes [Feature Request]

### ISSUE THREAD

**Issue by PurgingPanda** [getgrav/grav#1463]
Would be nice if there would be a way to combine multiple themes. Especially the modular parts.
Maybe a marketplace for parts would be convenient.

**Comment by rhukster** [comment]
These 'parts' are still going to be very specific to a theme, because even if you have a blueprint and a twig file, you will still need CSS to style it.  That's a little tricky to do outside of a theme but it is possible i suppose to a limited degree.  You can provide the twig and the blueprint in a plugin however, and i think distributing these as plugins either for a specific modular type or in a combo-pack is a viable option and is already supported.

The ability to have a marketplace is something we are already working on for the near future.
