### ISSUE TITLE
Nasty bug on Windows 10 x64 / Caddy / Microsoft Edge  — Grav v1.2.4 - Admin v1.4.2 — Expert Mode

### ISSUE THREAD

**Issue by ITSecMedia** [getgrav/grav#1466]
Sorry that I don't have more time for a large error report, time is short, this is rather a warning.

It happened here a couple of times, that a modular page "pages/_name/content.md file was moved outside  the modular page folder (that got erased too ) and the whole content of the modular fragment page was deleted when I used the admin panel - activated expert mode, it's so bad that I'm not using the admin panel for editing content right now.

No idea whats causing this - no time to dig deeper into the problem, running a dev system on caddy server on windows 10 x64.

Note it doesn't always happen, it tends to happen random.
Just as a notice for other devs to be aware of this.

I had no such problems in the past.
Good possible that it's an issue with Caddy/Grav and will not occur on other webservers but as I said it occurs randomly, when I restart Caddy, re-login its good possible that it works for a while.

**Comment by ITSecMedia** [comment]
Verified - issue occurs only in EXPERT mode - looks like mkdir call
_banner/banner.jpg
_banner/landing_banner.md
in Expert mode folder _banner gets deleted and the files moved on hierarchy up + .md file gets nulled

**Comment by flaviocopes** [comment]
You mention `pages/_name/content.md`. This is an invalid page structure: a folder with a `_` prefix indicates a modular "item" inside a modular page (see https://learn.getgrav.org/content/modular)

So you should have

- `pages/01.somepage/modular.md`
- `pages/01.somepage/_name/content.md`

Is this the cause of the problem?

**Comment by ITSecMedia** [comment]
Hi @flaviocopes, sorry my error report was just not clear enough. 
My file structure is correct according to the documentation. 
Modular Pages in general work.
To me it looks like there is an issue is in the admin plugin when editing modular pages.

**Comment by rhukster** [comment]
Hey @ITSecMedia this does sound serious, and I would like to get this sorted as quickly as possible.  I understand your probably busy, but as soon as you are able, if you could create a dummy set of user pages where you saw this problem and explain the steps to repeat it, that would help us immensely to isolate and resolve the issue. 

My gut feeling is that the webserver is not going to have anything to do with it, and it's likely if this happens on Caddy it will happen elsewhere.  It 'might' be a windows issue, but we'll have to dig deeper to prove that.

Thanks!

**Comment by gerwintmg** [comment]
I have experienced this same problem 

Steps that i experienced it whit
1. Grav installed with https://github.com/giansi/gravstrap-theme demo pages
2. add a blog item with Microsoft Edge 
    I got 2 different results
    - it froze on the continue button of the first dialogue. (or i lost my patience)
    - It continued to pages main and the blog page stops working properly. When i looked at the file structure  the had page reverter to a other page template than i had selected and no sub folder for tha page was created.

It worked fine in Firefox.

i hope this helps.

**Comment by kittym88** [comment]
I am not sure if this issue is related, but figure I would let you know in case it is.  I am just learning my way in the developing world.  I am generally on the testing side..... 

-I am running Grav v1.3.1 - Admin v1.5.1. 

-Page contents entered using Expert Mode.

I was going through Admin Configuration System looking for reason my tabs were not collapsed on site as they were in Content Preview with the "ui-tabs" from "UI-Shortcode plugin".  Checking the page configuration for "Accordion" page that works correctly. 

 Made a couple changes (read/re-read Grav Configuration Page). I always refresh on site side to check if page/site broken each change. Pages were good, I minimized windows and put computer in sleep mode.

-I had 41 pages total.
-When I came back I Admin Dashboard displayed I had 25 pages! 

 I changed the "Parameter separator" setting from ": Default" to "; Apache for Windows", but changed this back to ": Default" (this was the last configuration change I made prior to getting up). 

I did not change anything else. Not knowing what else to do, I repeated the same configuration (only this time the  "Parameter separator" setting was already set to  ": Default".  I selected " ": Default" once again and Saved again.  And all 41 pages returned. 

Like I said, this may be helpful, or may be known. Hope it helps.
