### ISSUE TITLE
Install Latest Grav Develop --> Admin and Site Broken!

### ISSUE THREAD

**Issue by axel-rank** [getgrav/grav#1474]
![error](https://cloud.githubusercontent.com/assets/12480617/26025517/d7b14ed2-37e9-11e7-9f56-db82a7a3d403.png)

**www.test.axelrank.de**

**Comment by rhukster** [comment]
You need to `composer install --no-dev`

**Comment by axel-rank** [comment]
???
What do you mean?
Logging in via ssh, using command line?

**Comment by rhukster** [comment]
ssh. If you don't have composer you can use `bin/composer.phar`

**Comment by axel-rank** [comment]
Sorry, I don't get it. Why should I use this command? (bin/composer.phar doesn't work)
I installed latest grav develop in admin using tools --> install from remote. I did this several times lately and it worked without an error. So why this error suddenly?

**Comment by axel-rank** [comment]
Just copied the system folder from another grav install and everything is working again!
So there has been a change/commit in latest grav develop that caused the error.

**Comment by axel-rank** [comment]
Guess it's your latest commit/new exif function that causes the error:
https://github.com/getgrav/grav/commit/82f223248eeb38995963d9e128bcb68a5cade934

**Comment by rhukster** [comment]
If you're installing develop versions you have to be aware that sometimes you are going to need to upgrade the vendor dependencies. I added exif support that requires a new library. Hence the missing classes you see. Also you should be updating with composer in every pull because the github repo does not actually include vendors like the zip packages. And there good be important updates or changes in packages.

**Comment by axel-rank** [comment]
Cool!Thank You!
https://github.com/getgrav/grav/commit/6b282d845f40b847ac1f62624f1e5ba4f1b381ab

**Comment by flaviocopes** [comment]
I stumbled on the same issue, I didn't even see this issue, but yes https://github.com/getgrav/grav/commit/6b282d845f40b847ac1f62624f1e5ba4f1b381ab is fixing this issue when cloning from git.
