### ISSUE TITLE
Setting date and publish_date in header does not publish page

### ISSUE THREAD

**Issue by trst** [getgrav/grav#1506]
I just had a pretty catastrophic issue on the server last night which caused me to have to do a hard reset from the repository where I store my user/pages data. When pulling down those files again, any page with only a `publish_date` (in the past) was then ordered by its modified date. Thanks to the reset, that meant I had a load of pages all with today's date. No big deal, I can manually set the header `date` to equal `publish_date` through the admin interface.

To make sure I avoid another issue like that, I tested setting a `publish_date` into the future and set the `date` to now. After testing, the page didn't publish. I tried setting `date` to all sorts of different times past, present and future but no dice.

Any thoughts as to how I should be properly using these features or thinking about them?

**Comment by flaviocopes** [comment]
If you rely on dates to order your posts, use the Auto Date plugin https://github.com/getgrav/grav-plugin-auto-date, it will automatically add a date when a page is created.

Otherwise Grav has no way to know when the original page was created, as pulling from the repo will make all the files created "now", not when the page was originally added to the repository.

Answer to the other question: `publish_date` should alter the published state of a page.

**Comment by trst** [comment]
Thanks for the plugin suggestion.

Just humour me for one last moment: so if I set the `publish_date` into the future, the `date` set by auto-date won't conflict then and Grab should respect the `publish_date`, not the latter?

**Comment by flaviocopes** [comment]
Grav should always respect publish_date. By default collections only list published pages. Make sure the page does not have "published: true" as that overrides any other publishing setting

**Comment by peter-doherty** [comment]
Dear all, I believe this is still an issue. I can't get my page to auto post. I use a date and time stamp. It appears to work in local dev but not on heroku or even in production.
 
![image](https://user-images.githubusercontent.com/22255078/30933137-eba0c12e-a3c9-11e7-96c4-b3904e50119b.png)
