### ISSUE TITLE
Possibility to save data in AWS S3

### ISSUE THREAD

**Issue by lauroguedes** [getgrav/grav#1513]
Hello, I would like to know if you can implement the possibility of saving the data on a cloud server like AWS S3. This would be very useful if the tape is served by another host, but the user wants to save the attachments as images and files more safely and available.

**Comment by OleVik** [comment]
A detailed tutorial for using Grav with AWS [was posted on the blog](https://getgrav.org/blog/fast-free-grav-development).

**Comment by lauroguedes** [comment]
Yes, however We assume that the user does not want to host the application in aws, but only the files. I'm going to make an application fork and try to implement this solution

**Comment by rhukster** [comment]
You are welcome to try this, but I know it will be VERY slow.  Grav is file based so it makes extensive use of file methods to see if files are modified, get contents, write contents etc.  A remote file system like S3 is going to be a huge performance problem. Local SSD drives are the best option and these are a marked improvement even over standard local HDD spinning drives.

**Comment by pierrejoye** [comment]
Hello,
thanks for this awesome CMS :)

I was looking for something similar.

@rhukster is fully correct about performance, however it is about updating or creating contents being slow. Assets (css/js/images) delivery will be much faster with S3 and cloudfront in the front. For the actual HTML, I as said, it does make sense due to the very nature of grav.

Would something to store assets on S3 (or other) be something grav will be interested in?
