### ISSUE TITLE
Filtering collections in twig doesn't work

### ISSUE THREAD

**Issue by ntopulos** [getgrav/grav#1542]
Hi,

When I try to get a list of the children pages of a `/projects` page and filter them by taxonomy using twig, it doesn't work, the result is never filtered and all children are systematically returned:

    {% rockets = page.evaluate([{'@page.children': '/projects', '@taxonomy.domain': 'rockets'}]) %}

Interestingly when the parent page doesn't exist, the result is correctly filtered:

    {% rockets = page.evaluate([{'@page.children': '/non-existing-page', '@taxonomy.domain': 'rockets'}]) %}

Is this a bug ?

**Comment by flaviocopes** [comment]
That's because that statement returns the SUM of the two top-level filters. That's a so-defined [Complex Collection](https://learn.getgrav.org/content/collections#complex-collections).

Only second-level options are intersected, like:

`$collection = $page->evaluate(['@taxonomy' => ['category' => 'blog', 'tag' => 'birds']]);`

but not

`$collection = $page->evaluate(['@page.children' => '/blog', '@taxonomy.tag' => 'birds']);`
