### ISSUE TITLE
page.summary($size) do you like it or hate it?

### ISSUE THREAD

**Issue by ash0080** [getgrav/grav#1560]
hmmm ... for me,  I always confused by it,

by setting a length,  trust me, you can never get the exact length you want.
by putting an image in the top of your post, WTF, the {{ page.summary }} will render it in your browser!
what about put  \# \#\# \#\#\# \#\#\#\#  in the top of your MARKDOWN?

Are you using a language besides only english?
or do you need a mixture language inside your web?

lot of headache...

So I changed the function,  now it will only return a **string**, without any html tags!
and, It will return exact same number characters as you assigned. 
and, It support double width characters like Chinese or Japanese now

if you like it, please 👍 +1

CONES: 
you need wrap your {{ page.summary }} in html tag (or not) by yourself. 
you can't get the google search results  like summary with images any more. 
( Actually, I thinks you can simply wrap a page.media.images[x] and your page.summary() now)

#1554

**Comment by w00fz** [comment]
Have you tried `{{ page.summary|strip_tags|length }}` ?

**Comment by ash0080** [comment]
@w00fz  

Sure  I tried so complex expression like this,

```
post.summary|striptags('<p><h1><h2><h3><h4><h5><h6><blackquote>')|slice(0,36)
```

now It's simply 
```
{{ post.summary(72) }}
```

**Comment by w00fz** [comment]
See this, might be exactly what you are looking for: https://learn.getgrav.org/themes/twig-filters-functions#truncate-a-string

**Comment by ash0080** [comment]
I read it,  It's useless.

the old codes are really bad,  it count the length with the html  tags
so if you wrote
aaaaaa or \> aaaaaa in Markdown, the rendered result  will totally different
cuz the one  is <p>  3 chas , another is <blackquote> 12 chas

and it subtract string with mb_substr, so an Chinese Character will take 3 times length of  an english letter.  If you can get 10 english characters,  you get 3 in chinese now.

**Comment by ash0080** [comment]
the code is simple, but plz think it as a redesign!

Maybe no one really need an summary with any tags and media files
when you copy some sentences to your doc file , do you want copy it with the format? I think most time, the answer is no,

**Comment by flaviocopes** [comment]
Linking to your PR as it's in the context: https://github.com/getgrav/grav/pull/1554
Is this you in the forum? https://discourse.getgrav.org/t/summary-confusion/4003/4

The non-ASCII char length is surely an issue.
As for summary, currently it's being added to the content, it's not an unusual behavior in CMS, but I agree that in some cases you don't really want it. We can't simply change it, or existing sites would be affected, but we could add an option.

What you can do right now is adding a "header.excerpt" blueprint field to the default page (https://learn.getgrav.org/forms/blueprints/example-page-blueprint) and use `page.header.excerpt` in your page templates instead of `page.summary`.

**Comment by ash0080** [comment]
@flaviocopes It isn't my forum account.
maybe page.summary($size,$noHtml=false) is a more straight solution
page.level configuration always boring when there're handreds pages

**Comment by ash0080** [comment]
Done😈
