### ISSUE TITLE
PHP7 minimum?

### ISSUE THREAD

**Issue by mahagr** [getgrav/grav#1624]
I'd like to raise minimum requirements for upcoming Grav 2.0 to PHP 7. Note that it will likely not be released this year, which means that PHP 5.6 will be receiving security fixes for less than a year when Grav 2 comes out.

Please give thumbs up or thumbs down reaction for this post (there is a smiley icon above ^). If you are against the change, also please give a reason why something like PHP 5.6 would suit better for you.

The main issue is that most of the libraries we depend on have PHP 7 minimum for the latest version, though some of them still maintain PHP 5.5/6 compatible version.

Another reason to jump to PHP 7 minimum are a few new language features which would greatly simplify the code and improve the quality of the project.

**Comment by Eihrister** [comment]
PHP 5.5 has been End of Life since July 21st, 2016.
PHP 5.5 will receive no more bug fixes.
PHP 5.5 will receive no more security updates.

PHP 5.6 has been End of Support since January 17th, 2017.
PHP 5.6 will receive no more bug fixes.
PHP 5.6 will receive security updates until December 31st, 2018.

Obviously, LTS maintainers might support it for longer in their distributions, but that's besides the point.

Since 5.6 is no longer supported by PHP, I wholeheartedly agree: Set the minimum requirement to 7.0.

**Comment by rhukster** [comment]
I see no reason not to have Grav 2.0 to be PHP7.0+ only.  The next version will not be out for some time, and by the time it is, we need to be thinking about the future, and ensuring that 2.0 is viable for several years to come after release.

**Comment by OleVik** [comment]
Given the time-frame of PHP 5.6, and the time-frame of Grav 2.0, it seems there would be a very short window for where 5.6 is worthwhile. It will at any rate just be receiving security-fixes as Eihrister notes, and many newer versions of dependencies are already bumping up to 7.0 as required. Thus if Grav is to continue to utilize up-to-date versions of it has to move to PHP 7.0 along with its dependencies.

That said, like PHP and libraries Grav depends on, the obvious solution is to set a time-frame for Grav 1.0 that follows along with 5.6. Ie., Grav 1.0 will continue to receive security fixes and patches until December 2018, but once Grav 2.0 comes out it goes all in on 7.1 because that is in active development - because 7.0 stops active support in December 2017.

Ultimately: Freeze the minor-version of Grav 1.0 when 2.0 is released, and set 2.0's minimum to 7.1 (given 7.0's time-frame).

**Comment by mahagr** [comment]
I didn't specify which PHP7 version by purpose, the minimum will be whatever release is current when we do the release. By current I mean either PHP 7.1 or even PHP 7.2 if it is really worth it.

**Comment by drnasin** [comment]
you also have to take into account if v7.2 will be widely available on shared hostings at the time plus we need to get grav into as many autoinstall hosting scripts as possible...my current hosting provider offers 70+ one click install apps but not Grav...

**Comment by OleVik** [comment]
Given that 5.6 will be close to EOL or actually EOL, hosts will have to move to 7.x or loose credibility. There are many cases where hosts have not even gone to 5.6, and are thus incompatible with Grav and many other scripts. 7.2 is not all that much of an issue, because 2.0 can take account for the few idiosyncrasies there are between 7.0, 7.1, and 7.2 through fallbacks - whose necessity are revealed in Travis or the like.

Though any open source project like Grav would like for hosts to upgrade their installations, it's not really a worthwhile issue to make considerations for. If programmers were to wait for hosts to catch up, we'd still be mainly using PHP 4, barely having moved into 5. If the requirement is broadly construed as PHP 7.0 for Grav 2.0, it can be pushed to 7.1 and 7.2 with minor-version upgrades to 2.0. This still leaves open the avenue of freezing the minor-version of 1.0, where users will have to accept using an outdated version if their system does not have PHP 7 available.

But to impede progress and not utilize improvements to libraries Grav depends on would be outrageous.

**Comment by Eihrister** [comment]
Please keep in mind that PHP 7.0 will be supported for 5 years for Ubuntu 16.04, and Debian 9 (stretch) that recently came out. We're talking 2021, and 2022 respectively here. I would suggest not choosing 7.1/7.2 as minimum just yet.

Reason behind my suggestion is that those that will need another kind of version will, like now, most likely have to resort to external repositories. Those external repositories like sury.org (Dotdeb will not release 7.1 and higher), are mostly maintained by one person. The native LTS versions are maintained by whole Security Teams entirely focused on these things. For many production systems in corporate environments, LTS versions are way more ideal.

**Comment by rhukster** [comment]
https://getgrav.org/blog/raising-php-requirements-2018
