### ISSUE TITLE
Dynamic home page

### ISSUE THREAD

**Issue by niahoo** [getgrav/grav#1642]
Hello, 

I'm looking for directions in order to build a specific type of blog. I would like the homepage to be the last item of a specific collection.

The goal is not to have to change home config whenever I add a post, of course.

Thank you.

**Comment by rhukster** [comment]
Wouldn't it be better to have a regular home page, but then in that homepage, simply display the last item in a collection of blog posts?

Basically you could take any blog type skeleton (eg `blog-site`) and then change the homepage configuration (`blog.md`), and limit the collection size to 1.  Then if you wanted to show the whole thing rather than just the summary, change the output to `page.content()` rather than `page.summary()`

Alternatively you could take the `random` plugin and modify it and call it `latest` and then in that plugin, simply pull the latest not just a random one.  Then you could redirect to `/latest` from your homepage or something.

**Comment by niahoo** [comment]
Ok, I'll try to use the first solution, I looked at the plugin but I don't want to duplicate it in order to use both versions (random and latest).

I may duplicate the blog twig template, though, in order to have classic summaries if I want listing pages.

It should be fine, thank you.

**Comment by rhukster** [comment]
sounds good!
