### ISSUE TITLE
Error, no space left on device again!

### ISSUE THREAD

**Issue by axel-rank** [getgrav/grav#1650]
Really strange, this error occurred again. Complete Site/Admin Broken  #1616 The grav cache folder had only 7 MB! After clearing the error went away. 
(cleared all cache in admin only 2 days ago)
**This error did not occur since Grav 1.3.2/Admin 1.5.2**
I didn't change anything in system.yaml...???
My hosting space is 75 GB, Grav folder has 165 MB
So must have something changed in Grav/Admin, (or maybe hoster/server problem???)

**Comment by rhukster** [comment]
If the cache folder had only 7MB it seems unlikely that the cache is the culprit here.  The cache is primarily where things are stored, but also there's the possibility that the `assets/` folder has things in it. Images are also processed and stored in the `images/` folder.  Perhaps you can check the size of these the next time this happens?

If these are relatively small, then you might want do login via the terminal/ssh and try `du-shc *` in the Grav directory.. For example on a test install:

```
> du -shc *
 92K	CHANGELOG.md
4.0K	CODE_OF_CONDUCT.md
8.0K	CONTRIBUTING.md
4.0K	LICENSE.txt
 16K	README.md
 12K	assets
 30M	backup
1.8M	bin
 26M	cache
  0B	cachecompiled
4.0K	codeception.yml
4.0K	composer.json
120K	composer.lock
444K	images
4.0K	index.php
 24K	logs
4.0K	robots.txt
2.7M	system
1.1M	tests
  0B	tmp
 36K	user
 17M	vendor
 24K	webserver-configs
 80M	total
```

**Comment by rhukster** [comment]
BTW, you might want to run this in the root of your account also, in case you have a bunch of core dumps, or other things that are taking up a lot of space.

**Comment by axel-rank** [comment]
Ok, I'll check this next time.
Plesk Panel shows me I'm using only 1% of my webspace.

![plesk](https://user-images.githubusercontent.com/12480617/30471163-e542b64c-99f7-11e7-8876-952aab89e3e6.png)

Could a PHP Update be a reason for the error?

**Comment by axel-rank** [comment]
I'll check it out.
