### ISSUE TITLE
Progressive Web Apps (PWA) is it compatible with Grav ?

### ISSUE THREAD

**Issue by STnetwork** [getgrav/grav#1652]
Hi,

I would like to configure my website with Progressive Web Apps, for access to the website offline for example, I know it's easy with static website, but with dynamic website like grav is it possible, and if it is how ?

**Comment by rhukster** [comment]
"Progressive Web Apps" is a very generic term that has many definitions.  My understanding is that a progressive web app is one that responds well to a variety of devices and platforms.  The details that underly this principal are open for interpretation, but everything that is output to a browser is 100% controllable by the user with Grav. There is nothing stopping you from optimizing that output to ensure it does 100% what your want for your definition of "Progressive Web App".  I suggest you start with a minimal responsive theme and build and tweak on top of that.

**Comment by STnetwork** [comment]
@rhukster 
Actually I was rather talking about the service worker, with this service you can access to the entire website in offline. Is this possible with grav ?

**Comment by STnetwork** [comment]
@rhukster 

Sorry, but I wasn't clear , I would like to use a service worker that is a require to be PWA, by this way I want access to my  Grav Website completely offline, and I don't know how to do that what pre-cache exactly, which will be the best tools for that there are many tools like : 

- https://github.com/NekR/offline-plugin
- https://github.com/GoogleChrome/workbox
- https://github.com/GoogleChromeLabs/sw-precache

Thanks for your help !

**Comment by lil5** [comment]
@rhukster please re-open

**Comment by andrewd72** [comment]
Its not really a grav issue IMO.
Have a look at my notes on using a service worker here: https://github.com/getgrav/grav/issues/1664
Due to the dynamic nature of grav you can't precache URL's but you can get the service worker to cache the pages that are created once they have been visited.
You should be able precache any static resources like a javascript file used on a different page type (pre caching for resources that are on the homepage doesn't speed anything up as the service worker registers bottom of page. )

**Comment by jodumont** [comment]
he also explain how to do it [here](https://flaviocopes.com/offline-website-pwa/ )
