### ISSUE TITLE
Yaml parser Boolean type does not conform to the specs

### ISSUE THREAD

**Issue by gamahachaa** [getgrav/grav#1667]
http://yaml.org/type/bool.html

_Expected behaviour :_
in **user/config/myData.yaml**
set a variable to one of these values:
```
 y|Y|yes|Yes|YES|n|N|no|No|NO
|true|True|TRUE|false|False|FALSE
|on|On|ON|off|Off|OFF
```
expl ::
YAML:
`myBool: NO`
PHP
`gettype(Grav::instance()['config']->get('data.myBool'))`
Should return `boolean` and 
`echo(Grav::instance()['config']->get('data.myBool'))`
should return `false` (or `true` accordingly)

_Current behaviour :_
in **user/config/myData.yaml**
set a variable to one of these values:
```
 y|Y|yes|Yes|YES|n|N|no|No|NO
|on|On|ON|off|Off|OFF
```
expl ::
YAML :
`myBool: NO`
PHP
`gettype(Grav::instance()['config']->get('data.myBool'))`
returns `string`

_The current behaviour matches the expected behaviour with one of these values only :_
```
|true|True|TRUE|false|False|FALSE
```
expl :: 
YAML :
`myBool: FALSE`
in php 
`gettype(Grav::instance()['config']->get('data.myBool'))`
returns `boolean` with value of `false`

**Comment by rhukster** [comment]
Ok, i've done some investigating and actually this is not a Grav issue per-say, but rather an upstream issue with Symfony's YAML parser.  I've provided a zip file to test with.

[yaml-booleans.zip](https://github.com/getgrav/grav/files/1345829/yaml-booleans.zip)

<img width="945" alt="cloudapp annotation 2017-09-29 at 4 33 59 pm png" src="https://user-images.githubusercontent.com/1084697/31038429-02fd69ec-a534-11e7-86d5-78ffd3fb72d3.png">

As we rely extensively on Symfony YAML, there's really nothing we can do from here, but feel free to raise the issue here: https://github.com/symfony/symfony/issues?q=is%3Aopen+is%3Aissue+label%3AYaml
