### ISSUE TITLE
image.derivatives(width,height,[background]).url() just returns the original image URL

### ISSUE THREAD

**Issue by jpgklassen** [getgrav/grav#1694]
When the results of the `derivatives()` function are piped into `url()`, we just get the original image URL instead of a URL for the cached, resized image.

**Comment by OleVik** [comment]
This is because the `.url()` function/chain is still preserved for the original image, whereas `.derivates().html()` will return the HTML-structure. Derivatives generates the images and the `srcset`-attribute, which has no meaning without the HTML-tag. Therefore you'd commonly use `image.derivates().html()` to generate the responsive IMG-tag - including its generated images - and  `image.derivates().url()` to link to the fullsize image, for example as a part of a lightbox feature.

**Comment by jpgklassen** [comment]
Okay, I see what you mean. But I feel like the logical thing would be for `derivatives().url()` to return the URL of the appropriate resized image for the user's device. Is this not possible on the server side? I thought it must be - for example, it looks like [mod_pagespeed can do this](https://www.modpagespeed.com/doc/filter-image-optimize) even though it's running on the server side. Please correct me if I'm wrong.

**Comment by OleVik** [comment]
`derivatives().url()` is unable to return the device-specific URL, because Twig renders - like PHP - server-side, ie. before any client input is returned. That, however, is not the function of the `srcset`-attribute. In the IMG-tag, we set a default `src`-attribute - typically a medium size image for fallback - and populate the `srcset`-attribute with alternatives. When the browser loads the site, it is already aware of the size of the viewport on render, and thus the browser will replace the `src`-attribute with the most appropriate image available in the `srcset`-attribute.

That is to say, rather than waiting on the client (browser) to report back what device is used (often through JS), we have a predefined list of available images that the browser can choose from to render to the client. It really is a question of what is more efficient: Waiting for input before selecting a source, or giving a preset menu of alternatives that are applied beforehand. In essence, `srcset` and `derivatives` does all this server-side, and waits for no input before giving the client optimized alternatives. PageSpeed does the same, but on the server-level rather than programming-interface-level.

**Comment by jpgklassen** [comment]
I understand that generally server-side languages cannot get information like this about the user. But then how does [mod_pagespeed](https://www.modpagespeed.com/doc/filter-image-optimize) do it? Does it grab the information from the request header? And could `derivatives()` be set up to do something similar?

I understand that `derivatives()` basically exists to generate a `srcset` HTML tag with a call to `derivatives().html()`. But I feel like it could be used for so much more. For example, it would be amazing if we could use `derivatives().url()` to get the URL of the appropriate resized image for the user's device. _Could this be possible?_ If it worked, we would have a very cutting-edge way to do image optimization!

**Comment by OleVik** [comment]
Mod_pagespeed and srcset deliver virtually the same thing; information is grabbed from the browser on render, determining the size of the viewport, then the browser selects the most appropriate image. Derivates() could presumably be extended to allow targeting the generated image-sizes from cache, but cache should be able to deliver the URL of it by using image.resize.url().

With mod_pagespeed or srcset you are already delivering optimized sizes for the set device-sizes, what would you want to optimize further?

**Comment by jpgklassen** [comment]
To answer your question, an example of where I would use `derivatives().url()` would be in the CSS `background-image` property. It would be a super-cool cutting edge way to display optimized background images. What do you think?

**Comment by OleVik** [comment]
You could achieve that with pseudo-CSS, ie. render it in `<style>` so Twig can generate it in a template.

**Comment by jpgklassen** [comment]
Could you give an example of how I would code that?

**Comment by OleVik** [comment]
This is where the `derivatives()`-function comes short, as it currently cannot pass paths to generated images back into Twig other than to output the full IMG-tag. That is, to my knowledge, one of the core devs might be aware of any changes to it that allows this.

Last I did this, I passed images to a macro, like this:

```
{% macro css(file, base, id) %}
	{% set filename = file|split('.') %}
	{% set filenameext = "." ~ filename|last %}
	{% set file = file|replace({(filenameext): ""}) %}
	#{{ id }} {
		background-image: url("{{ base }}/{{ file }}-2240{{ filenameext }}");
	}
	@media (min-width: 30em) {
		#{{ id }} {
			background-image: url("{{ base }}/{{ file }}-640{{ filenameext }}");
		}
	}
	@media (min-width: 34em) {
		#{{ id }} {
			background-image: url("{{ base }}/{{ file }}-960{{ filenameext }}");
		}
	}
	@media (min-width: 48em) {
		#{{ id }} {
			background-image: url("{{ base }}/{{ file }}-1280{{ filenameext }}");
		}
	}
	@media (min-width: 62em) {
		#{{ id }} {
			background-image: url("{{ base }}/{{ file }}-1600{{ filenameext }}");
		}
	}
	@media (min-width: 75em) {
		#{{ id }} {
			background-image: url("{{ base }}/{{ file }}-1920{{ filenameext }}");
		}
	}
	@media (min-width: 125em) {
		#{{ id }} {
			background-image: url("{{ base }}/{{ file }}-2240{{ filenameext }}");
		}
	}
{% endmacro %}
```

This, in conjunction with this [script](https://github.com/OleVik/grav-plugin-imgsrcset#generating-images), to generate the responsive-sized images. Used, for example, for header images:

```
{{ srcset.img(page.header.header_image, page.url, "article-header-image") }}
```
