### ISSUE TITLE
relative slug using directory name as fallback does not work

### ISSUE THREAD

**Issue by cord** [getgrav/grav#173]
on http://learn.getgrav.org/content/linking#slug-relative it says

> It can also pull slugs assigned both in the header of the file, as well as the fallback directory name. This makes creating quick links easy as you don't have to remember the specific file name, but an easily remembered (and relevant) slug.

however this does not work.

when defining a custom slug the link using the directory name leads to a 404

**Comment by rhukster** [comment]
Thanks, i'll look into this next week.

**Comment by rhukster** [comment]
Just to confirm. What this mean is that if you use a `slug` in the page haeder, that will be used rather than the based on directory name.  For example, you have a page:

```
user/pages/02.blog/blog-post/default.md
```

The URL to that page would be `blog/blog-post`.  However, if you had a header option in that `default.md` say:

```
slug: really-great-post
```

Then the URL would now be: `blog/really-great-post`, so your basically overriding the folder name which was used as the default slug.  I use this in a few places and i've never had any issues with it.

**Comment by rhukster** [comment]
Actually I know what the issue is here, unfortunately it's not a simple fix.  I'll have to think about how best to handle this.

**Comment by rhukster** [comment]
Should be sorted in the next release.
