### ISSUE TITLE
Text Injection from Url

### ISSUE THREAD

**Issue by dvbrooks** [getgrav/grav#1750]
Our company was alerted to this issue of being able to inject text from the url into pages that have forms on them. Below is an example:

Url with injection: www.example.com/some-url/1zqjqq'%22()%7B%7D%3Cx%3E:1zqjqq;9
Resulting form action url:  www.example.com/some-url/1zqjqq'">:1zqjqq;9

It seems like maybe the Routing system is at fault here. I would expect a request like that to 404, but it doesn't.

**Comment by rhukster** [comment]
Can you please provide some more information about how you have the form defined, and also the twig template that renders that form (if it's a custom twig template). Also the version of Grav and Form plugin you are using?  Thanks.

**Comment by dvbrooks** [comment]
Grav version: 1.3.8
Form: v2.10.0
Template: form-messages (template provided by the plugin)

The form is defined in the yaml FrontMatter in the page.

You can actually inject that text ( 1zqjqq'%22()%7B%7D%3Cx%3E:1zqjqq;9 ) into any url on the Grav site, and it gets resolved. It just so happens that on pages with the form that it gets injected into the form action url, since the form gets its url from the current page. That is why I believe it is an issue with the Router, since it lets that url through without throwing a 404.

Let me know if I can provide any other info.

**Comment by rhukster** [comment]
The thing is that in Grav, the `:` is treated as a param separator.  This allows you to write URLs such as `/my/route/key:value`

and then you can retrieve that value with `uri->param('key')`.  This is similar to the standard browser query implementation: `/my/route?key=value` that is retrievable via `uri->query('key')`.  So in your example above, that escaped text is really treated as a key/value pair due to the existence of the `:` in the middle. And because of this it's also appended to the form action just as a query would be.  Now, this is not going to be used anywhere in Grav unless you actually try to retrieve the value with `uri->param('1zqjqq'%22()%7B%7D%3Cx%3E')`.

It may look like your injected data into the page, but really Grav is just passing along the URL.  There is quite a bit of extra validation happening to ensure no script is injected, but if its merely escaped characters, we cannot tell if those are valid or invalid.  

it's not a 404 in this case because that extra data is merely a param.  If you were to remove the `:` it would issue a 404.

**Comment by dvbrooks** [comment]
Ok, thanks for explanation. I'm new to Grav, and this is the first issue that was put on my plate. I will pass this info along to my company.

Thanks again for your help!
