### ISSUE TITLE
Login Credentials Set Through CLI Not Working for New Users

### ISSUE THREAD

**Issue by kelseyurgo** [getgrav/grav#1752]
Ever since I updated to the latest GRAV install I have had issues with creating new users.

First I was getting this issue:

PHP Fatal error:  Uncaught RuntimeException: Opening file for writing failed on error fopen(/home/kelseyurgo/xdci/cache/compiled/blueprints/master-localhost.php): failed to open stream: Permission denied in /home/kelseyurgo/xdci/vendor/rockettheme/toolbox/File/src/File.php:202

Which was odd because master-localhost.php didn't exist, but master-xdci.renci.org.php did.

After not getting anywhere I did find a similar permissions issue here https://github.com/getgrav/grav/issues/912 turns out the permissions are fine, the file just didn't exist. So I copied the file that did exist into a new file name master-localhost.php.

This did move things along to a new error that looked similar, but it was looking for a new file that didn't exist, this time in cache/compiled/files which definitely had to do with permissions because once I loosened permissions recursively on cache/ directory, the bin/plugin login newuser command was able to run and I was able to complete the process.

However, the credentials I have set (and I have done this three times now just to be sure) are leading to a failed login page.

This is happening across two different sites since updating.

Any help would be greatly appreciated!

**Comment by rhukster** [comment]
How are you creating new users? From the CLI command?

I just tested with the latest develop branch and it worked fine. What version of Grav are you running?

**Comment by kelseyurgo** [comment]
I am creating new users through the CLI Command. I am running version Grav v1.3.8 - Admin v1.6.6.

**Comment by rhukster** [comment]
So can you confirm that when logged in and using the CLI you can actually create files in the `user/accounts/` folder?

Try something like:

```
$ touch user/accounts/testfile
```

If that gives a permission error, then check the permission on the user/accounts folder and see if your current logged in user has write permissions.

**Comment by kelseyurgo** [comment]
So the CLI can definitely has permission as it is able to create the user yaml files (there are new correctly named files under user/accounts/ after each new user added). 

The issue comes in when someone actually goes to log in on the frontend (our url with /admin appended), the credentials that were set up don't actually work. And I have checked this multiple times across both recently updated installs of GRAV.

**Comment by kelseyurgo** [comment]
And just to be sure I ran`touch user/accounts/testfile` and testfile was successfully created.

**Comment by rhukster** [comment]
Ok, then the problem is that the webserver itself cannot write to the file.  Ideally you should have the user that logs in to the CLI be the same user that webserver runs under.  This way there's no chance of having permission issues.  An alternative is to share a group that has write permissions.  More info here: https://learn.getgrav.org/troubleshooting/permissions

**Comment by domsson** [comment]
I'm currently seeing a similar error message when trying to use `bin/gpm`:

    PHP Fatal error: Uncaught RuntimeException: Opening file for writing failed on error fopen(/var/www/redacted/cache/compiled/blueprints/master-localhost.php): 

Now, @kelseyurgo said:

> Which was odd because master-localhost.php didn't exist, but master-xdci.renci.org.php did.

Which is interesting, because when I checked the above directory on my machine, I saw that `master-localhost.php` did not exist, but `master-192.169.0.100.php` does. So it seems that in both cases, Grav is looking for the `maser-localhost.php` file, when the localhost potion might actually be the IP / hostname.
