### ISSUE TITLE
Collections include unpublished pages

### ISSUE THREAD

**Issue by diegovogel** [getgrav/grav#1839]
From what I've read in the docs, Collections should [only include published pages](https://learn.getgrav.org/content/collections#self-collections). But I noticed today that unpublished pages are also being included.

The collection I'm working with is very simple:
```
content:
    items: '@self.children'
```

If I do something like this with Twig:
```
{% for child in page.children %}
   {{ child.title }}
{% endfor %}
```
It will output all child page titles, published and unpublished. It only excludes unpublished pages if I add ".published" to page.children in the for loop. Is this how it should work?

**Comment by rhukster** [comment]
I'm not able to reproduce this.  Collections of this type only include published pages because of this line of code: https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Page/Page.php#L2665

I've actually revamped this a little bit in Grav 1.4 and it allows you to retrieve a collection of all pages, and they filter them by published or unpublished afterward, but the default action remains to have a collection of only published pages

**Comment by diegovogel** [comment]
Strange, I must've been doing something wrong then. Thanks for checking into it.

**Comment by tijamo** [comment]
I'm getting the same result. By default all unpublished pages are showing in collections in our custom templates. We can't see why this should be the case. Is there a config setting that could be creating a system-wide override?
