### ISSUE TITLE
Grav Core - Wrong Facebook metadata - Frontmatter

### ISSUE THREAD

**Issue by xetorixik** [getgrav/grav#1849]
Hi,

The [metadata function of Grav core](https://learn.getgrav.org/content/headers) is in essence an excellent function. Thanks for that.

There is only 1 problem and that is Facebook Metatags.

For example. Metadata: og:image' produces the HTML header:

`<meta name="og:image" property="og:image" content="https://test.be/test.jpg" />`

But it should be:

`<meta property="og:image" content="https://test.be/test.jpg" />`

As can be seen here:

> Warnings That Should Be Fixed
> Tag specified as 'name' instead of 'property'
> The following meta tags are specified using 'name' instead of 'property' and will be ignored unless specified using the 'property' key: og:locale, og:type, og:title, og:description, og:url, og:site_name, fb:app_id, og:image

Reproduce:

1. Add Metadata: og:image or any Facebook metadata as frontmatter.
2. Test url via https://developers.facebook.com/tools/debug/sharing/

Please fix the Facebook metadata.
Thanks.

**Comment by rhukster** [comment]
That is just a warning, the name field is being ignored as the facebook debugger states.  It still has the required `property="og:image"` field that is required.

**Comment by xetorixik** [comment]
The name field ignored?
The meta tags will be ignored unless ..........

Apart from that. 
It is not according to the Facebook guidelines. 
Why not just use the guidelines?

**Comment by rhukster** [comment]
this arose because some services like to use `name=` for OpenGraph tags (e.g Twitter), while most use `property=`.  The safest way seemed to support both, and that used to work fine.  I'm not sure why Facebook is now causing a problem with having both options, but I've added a special case check for Twitter (which I think is the only outlier) to use `name`, and all the rest use `property`.

**Comment by rhukster** [comment]
BTW, this will be part of the upcoming 1.4 Grav release.

**Comment by xetorixik** [comment]
Thanks.
Good to see that it is corrected right away.

**Comment by hughbris** [comment]
This kind of special treatment won't scale if there are many more exceptions. At that stage it seems to me it will be cleaner to allow more nuanced YAML to indicate the preferred meta attribute. My foreboding 2c.

I mean, I think ideally Grav core shouldn't care about things like Twitter and Facebook.

**Comment by Lipstickandme** [comment]
Hi,
I'm new here.  I am currently having this problem with Facebook.  I registered a domain name lipstickandme.com several days ago to use with my publication on the Paper.li platform.  I was told to set up the domain with CloudFlare to manage my SSL.  All done.  Now when I try to post and announcement and preview of my publication on Facebook, I get a grey ? next to the URL and the headline images will not preview UNLESS I share the post.  I scrubbed Facebook and got the error below.    The specific headline in question was created on Google docs.  Any ideas on how to fix this since it's a problem when people can't see the headline images.   

Warnings That Should Be Fixed
Tag specified as 'name' instead of 'property'
The following meta tags are specified using 'name' instead of 'property' and will be ignored unless specified using the 'property' key: og:locale, og:type, og:title, og:description, og:url, og:site_name, fb:app_id, og:image
