### ISSUE TITLE
Meta-file for media  - no alt_text 

### ISSUE THREAD

**Issue by mgollmer** [getgrav/grav#1883]
Hello there, 

i'm trying to use meta-files for my images. I want to set the "title" and "alt" attributes of the image. The content of the meta file looks like this:

```yaml
alt_text: My
title: super
```

The markdown code for the image looks like this ...

```md
[](rahul-anil-273339-unsplash.jpg?lightbox&display=thumbnail&classes=right,toll)
```

The createt html-code looks like this...

![grafik](https://user-images.githubusercontent.com/26478647/36539630-bd78df84-17d7-11e8-903c-b3dfda12d4eb.png)

Looks like a bug to me. Can anybody help me out?

Kind regards, 
Michael

**Comment by rhukster** [comment]
2 problems here:

1) even though documentation was saying `alt_text` it was actually only working with `alt`.  I've fixed it so it takes both options now.

2) second problem was caused by a fix a few months back that forced an alt tag to be included in all image tags, actually was overwriting the set metadata value.  I've fixed that also.

is in 1.4 branch btw.

**Comment by mgollmer** [comment]
Thank you very much ! ;)
