### ISSUE TITLE
[add-resource] New Plugin grav-plugin-adsense2

### ISSUE THREAD

**Issue by clemdesign** [getgrav/grav#1897]
Hi,

I would like to add my new plugin to the Grav Repository.

Here are the project details:  [https://github.com/clemdesign/grav-plugin-adsense2](https://github.com/clemdesign/grav-plugin-adsense2)

The core of this version is reworked compared to the first version [grav-plugin-adsense](https://github.com/muuvmuuv/grav-plugin-adsense) with possibility to:
- Add graphical and text Ad
- Add InArticle Adsense format
- Define script mode (Sync/Async)
- Add many Ads through configuration list

Thank you,
Clem

**Comment by rhukster** [comment]
Will add soon.

**Comment by rhukster** [comment]
Added to GPM for next update.  Thanks.

**Comment by clemdesign** [comment]
Great!! Thanks

**Comment by hughbris** [comment]
Hi @clemdesign. I haven't looked at this plugin or your changes closely, but I'm curious why you decided to release a "2" version rather than extend the current plugin. I ask because I am debating this choice myself for some plugin forks I've made. The reasons are different, but in some cases the plugins seem abandoned. In another, my changes seem incompatible. I don't like having these in limbo while I figure it out! :/ Please tell me _your_ thought process.

**Comment by clemdesign** [comment]
Hi @hughbris, I decided to make a "release 2" (but I could have chosen another name like "Adsense toto") because my version is very different from the other. In this case, I think that if I submitted a pull request of changes, it would had been rejected because the configuration strategy is different. So it was more simple to make a new and propose it.
I already faced a plugin that seems abandoned while the pull request was created, I decided to integrate my version on my website with divergence from the base.
