### ISSUE TITLE
Problem with HTML img tag in markdown page

### ISSUE THREAD

**Issue by WolfgangWakolbinger** [getgrav/grav#198]
If I insert `<img alt="text" src="./example.png" />` the image available in the same directory as the page itself is not shown. Testing the situation and adding a trailing slash per hand results in showing the image correctely on the page.

It looks as trimming the trailing slashes causes a problem with using HTML img tags in markdown pages.
I commented this issue already on commit 718d443 where an issue #190 has been resolved.

**Comment by rhukster** [comment]
We have also noticed this with our testing of some admin plugin stuff, and I think @Gertt said he was going to look at it today perhaps.

**Comment by Gertt** [comment]
It doesn't really have anything to do with that change as far as I can tell, that just makes sure we find pages when people add a trailing slash.

The problem here is that Grav does not add trailing slashes to links. Which causes your browser to interpret the current folder when you're on this page `http://grav.dev/blog` as the site root instead of the `blog` folder. So the browser tries to request the images from the site root.

I do not know if it was a deliberate choice to work without trailing slashes, but imho fixing this would require Grav to change the way it generates links to pages by always including the trailing slash as well as adding some logic that will 301 redirect non-backslashed requests to backslashed reqests for SEO purposes.

Sounds like a big change that could possibly introduce other issues, so I'll wait for @rhukster 's ok on this.

PS: You can also use `twig` to fill in the src of your image tag with an absolute url to the image. That way you don't rely on the browser to figure stuff out.

**Comment by mahagr** [comment]
The reason not to use trailing slashes was that the urls aren't meant to be directory paths, so why to bother even pretending that they are. Trailing slash has no meaning and as such it should be removed. What comes to ./ notation and files not being found, it is another issue and should be fixed.

**Comment by Gertt** [comment]
In that case I see two solutions:

- Grav will need to manually parse all HTML manually looking for links
- All themes would need to implement the `base` tag.

Neither of these are ideal imho. Other suggestions?

**Comment by rhukster** [comment]
I think i'm going to look at moving the `convertUrl()` method out of the markdown trait so it's usable from other places, including plugins.  

My advice after that would be to choose one of 3 options:

1) Use Markdown instead of HTML when possible
2) Use Twig+HTML to add the base_url in the `<img>` tag if you are using HTML
3) Create a plugin that is triggered appropriately to convert HTML url's using the `convertUrl()` method (when moved to appropriate location)

**Comment by rhukster** [comment]
I'll close this now.

**Comment by rhukster** [comment]
FYI, regarding point 3), i've moved the convertUrl() method to the Uri object so writing a plugin would be doable now.
