### ISSUE TITLE
Theme 'x' does not exist, unable to display page.

### ISSUE THREAD

**Issue by diomed** [getgrav/grav#1996]
If theme is active, and user deletes it over FTP...

Yeah, I know it probably sounds funny and illogical, 
but you should take into options what could go wrong, and how to make it right.

anyway, if that happens, grav should fall back to one of installed themes, probably the official one,
or any other available in directory, instead of displaying message above everywhere.

this, what is worse, **affects admin panel** as well, since one cannot just go to grav/admin 
area and choose another theme, because the same error displays. if you decide not to fix so
it fallbacks, at least make it available that one can go freely to admin area and change theme.

**Comment by rhukster** [comment]
No valid theme is a pretty serious error for Grav.  it has to be addressed asap. It affects admin panel even because admin relies on getting templates and other stuff from the currently configured theme.  It's not something we can easily ignore.

Quick solution if you ever get into this unlikely situation, is to just edit the `user/config/system.yaml` and fix it manually.
