### ISSUE TITLE
Custom route breaks error page

### ISSUE THREAD

**Issue by tranduyhung** [getgrav/grav#2022]
We migrated a WordPress site to Grav, everything is good except a custom route makes 404 error page broken.

The old URL structure is ``` site.com/title```. In Grav, we build the blog in this URL structure ```site.com/blog/title/``` so we use this custom route to keep the old structure:

    routes:
      /(.*): /blog/$1

This works, but if we access a non-existing page, instead of getting a 404 error, we get 500 error 

    Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 262144 bytes) in system/src/Grav/Common/Utils.php on line 95

Is it possible to modify the custom route to prevent this problem?

**Comment by andrewd72** [comment]
Did you try setting "Home page" to the the blog and setting hide home route in URLs? (options in system config)
That should do what you want without setting routes.

**Comment by tranduyhung** [comment]
Unfortunately the blog is not the home page :(

**Comment by rhukster** [comment]
You are getting this because your redirect is causing an infinite loop. This is not the fault of Grav itself, but your configuration.

**Comment by tranduyhung** [comment]
Yes I know that is the problem with custom route and not from Grav. My question is if there is any solutions to fix or work around.

Redirecting hundreds of blog post URLs from domain.com/X-Y-Z to domain.com/blog/X-Y-Z is difficult.

**Comment by michaelatmender** [comment]
@tranduyhung I did something similar, I used a regex to stop redirections when a route began with a certain string. (We use grav for a docs site, where we structure content into version 1.0, 1.1.. etc) The regex looks like:

`'^(?!(\/1.)|(\/Development)|(\/development)|(\/search)|(\/sitemap.xml)|(\/^admin$))(.*)$': '/1.6$7'`
So a route like:
`/test` would go to `/1.6/test`, but if this page didn't exist, it would not go into the redirect loop because the regex would exclude routes beginning ` /1.`. You could do something similar for routes beginning `/blog`.

_However_ - this worked until recently when I updated Grav to 1.5.1 (it was 1.1.17) and now it goes to the redirect loop again. Perhaps I should open a new issue for that?
