### ISSUE TITLE
Page->translatedLanguages() 

### ISSUE THREAD

**Issue by spamrakuen** [getgrav/grav#2026]
I've a page with these routes, the first one for english, and the second one for spanish
/grav/products/phone
/grav/es/productos/telefono

the translatedLanguages method from Page returns;
phone 
/productos/telefono

the spanish page was set using routes + default in the frontmatter

I think translatedLanguages should return the full route (including language when needed)

I tried to workaround this in several ways but current Grav support for multilanguage is not ok.

I'm missing something? There is a way to get the full routes of muy page (with language code if needed?). 

I've also tried with Page->url() but if I'm in english language it does not return the /es/ in the spanish route.

**Comment by rhukster** [comment]
https://github.com/getgrav/grav-plugin-langswitcher/issues/1#issuecomment-122886202

This is because of the way Grav works.  Loading every version of the page for each language would cause too much performance hit.  The simple solution is to redirect to default route afer reaching the page.

https://github.com/getgrav/grav-plugin-langswitcher/issues/1#issuecomment-122886202
