### ISSUE TITLE
Text logo instead SVG

### ISSUE THREAD

**Issue by koreos** [getgrav/grav#2031]
Hi, how can I add to basic Quark theme a Logo with just simple text instead SVG Grav logo? 
I want to add name of domain for example MyDomain.pl

Why this is so difficult and when Grav will have customization theme like this https://generatepress.com/premium/? It is the best for people who are not webmasters, programmers or designers!

**Comment by andrewd72** [comment]
Generate press seems just to be yet another Wordpress builder/theme choice. 
I started using Grav because the Wordpress do it all theme I'd bought was so slow to use. 
Not every option suits everyone.

You could try one of the Gantry based themes maybe.

You need to change this line in the Quark, add a <h1>Mydomain.pl</h1> and style with CSS
<a href="{{ home_url }}" class="navbar-brand mr-10">{% include('@images/grav-logo.svg') %}</a>

IMO get the most out of Grav you need to pick up a little HTML / CSS / TWIG along the way.

**Comment by koreos** [comment]
Thank you for quick answer but for me and many people who are not webmasters its too complicated - we don't want to be programmers, we want to write content and change everything in admin panel. We can pay for CMS like Grav but it should be simple for normal people.

I can change the file you wrote but I will have to change it again and again when update new version of Quark - this is sick..

Why Wordpress is so so popular? Because it is for people!

**Comment by andrewd72** [comment]
You can make a theme that inherits from Quark, you only need to change it once. 

Anything can be changeable from admin if the theme is written that way. 
Grav is perhaps more aimed at web devs creating websites for clients. They then set it up so that a client can use it to add content and configure any options. 

I'm a photographer not a web developer. I had a Wordpress site for many years, now I have two Grav sites and I wrote my own themes for both, second one took me a day from scratch and the homepage scores 100/100 on google page speed insights for both desktop and mobile.

**Comment by rhukster** [comment]
Not a grav core question really.  If are having trouble with theming, check the docs on the subject.  if you are having problems with web development, check google :)
