### ISSUE TITLE
page add panel in stored xss vulnerabilty

### ISSUE THREAD

**Issue by ismailtasdelen** [getgrav/grav#2104]
Hello Development Team,

When I was a security researcher and student, I wanted to discover and report " Stored XSS" vulnerability.

Version : Grav v1.4.7 - Admin v1.8.6

Vuln url adress : /GRAV/admin/pages -- page add

Screenshot : 

![screenshot from 2018-07-18 13-44-28](https://user-images.githubusercontent.com/15425071/42877068-2eb9696c-8a91-11e8-9ebd-f89a6a51482b.png)

Payload : 

"><img src=x onerror=alert('ismailtasdelen')>

Thanks

**Comment by rhukster** [comment]
The admin is intended for privileged users.

We really don't consider code you put into a page as a vulnerability.  This is because it can only be done as an authorized user of the admin, and there are legitimate needs for people to be able to add code and script in content (think google analytics code for example). 

if this could be done without admin access, then yes, 100% that's an issue.

**Comment by ismailtasdelen** [comment]
Thanks for the came back :+1:
