### ISSUE TITLE
Hacktoberfest?

### ISSUE THREAD

**Issue by Perlkonig** [getgrav/grav#2188]
I should have saved all my recent PRs until October 😄 Do you guys have a list of things you might want help with over October? I plan on doing a pass over the docs, but I'd love to do other stuff, too.

**Comment by rhukster** [comment]
We really should do something more 'active' for Hacktoberfest.  Really the docs is the biggest thing that needs fleshing out with more details and examples, but there are a few issues that need looking at.  1.6 is shaping up to be a good release with some new functionality already (scheduler, backup), but we have some bigger plans for it too!

**Comment by OleVik** [comment]
In regards to a docs-overhaul, [this](https://github.com/getgrav/grav-learn/issues/356) needs a proper cleanup: Several things on the list were already closed (among others, [this PR](https://github.com/getgrav/grav-learn/pull/632)), and there is little point to keeping things on the list when fixed. I agree that the docs needs fleshing out, but they also currently quite broad and in need of some structure and consistency. Rather than our infrequent passes, a coherent effort would probably be a good goal for Hacktoberfest.

**Comment by weeyin83** [comment]
Happy to help where I can with this as well. :)

**Comment by rhukster** [comment]
https://github.com/getgrav/grav-learn/issues/356 contains various topics that need more coverage in the docs.. not a complete list but it's a start.  Any help here is appreciated.  Thanks!

**Comment by good123boy** [comment]
Hello

**Comment by MichaelTayeprime012** [comment]
Hello

**Comment by CeoFred** [comment]
Hello,whatsup for grabs?? Really to slap my keyboard.

**Comment by damikanye** [comment]
hello

**Comment by Jmidar** [comment]
Hello...

**Comment by good123boy** [comment]
WTF should we do here to get a T-SHİRT?

**Comment by AkhmadRiswanda** [comment]
hello, can you help me to learn programming ?
