### ISSUE TITLE
Route alias creates fatal error for non-existing page

### ISSUE THREAD

**Issue by tranduyhung** [getgrav/grav#2209]
I have these alias routes in user/config/site.yaml:

```
routes:
  /solutions/(.*): /products-solutions/solutions/$1
```

If I access a non-existing page, like `https://domain.com/solutions/this-page-does-not-exist`, I get fatal error instead of 404 error

```
Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 4096 bytes) in /system/src/Grav/Common/Uri.php on line 492

Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 16384 bytes) in vendor/filp/whoops/src/Whoops/Util/SystemFacade.php on line 18
```

I really appreciate if you have any suggestions to solve this. Thanks!

**Comment by rhukster** [comment]
I think it's relaly just an infinite loop caused by your regex.. try this:

```
^/solutions/(.*): /products-solutions/solutions/$1
```

The `^` will pin the regex query to the start of the route.. otherwise it picks it up anywhere in teh route.. like in the redirected route...

**Comment by tranduyhung** [comment]
Thank you @rhukster for your suggestion, unfortunately the problem still exists after adding ```^```. If you have any other suggestions, please let me know. Thank you!

**Comment by jamiepickett** [comment]
I came across this same situation and opened up this issue issue:
https://github.com/getgrav/grav/issues/3012

When the regex for a route runs and it makes it into line 564 of Pages.php, the $found and the $source_url are !==, and the page dispatch code is run.  However, since the page that you are being dispatched to doesn't exist on the filesystem, it seems that you loop right back into this regex route method.

As a workaround so I could keep working on my MVP demo, I adjusted the section of code to do this:
`$site_routes = $config->get('site.routes');
                    if (is_array($site_routes)) {
                        foreach ((array)$site_routes as $pattern => $replace) {
                            $pattern = '#^' . str_replace('/', '\/', ltrim($pattern, '^')) . '#';
                            $found = preg_replace($pattern, $replace, $source_url);
                            $rootDir = $this->grav['locator']->findResource('page://') ? ($this->grav['locator']->findResource('page://') . '/') : '/var/www/html/user/pages/';
                            if( is_dir($rootDir . $found) ){ //checking for directory existing before dispatching
                              if ($found !== $source_url) {
                                $page = $this->dispatch($found, $all);
                              }
                            }
                        }
                    }`

The main adjustment was checking to see if the directory exists before the dispatch method is called.  This allowed for the matches to be routed and for non-matches to be returned a 404 page.
