### ISSUE TITLE
Woo skeleton: single page anchor links don't work on the other subpage

### ISSUE THREAD

**Issue by MatthiasKauer** [getgrav/grav#226]
Hi,
I'm playing with the woo-skeleton on my end and I noticed the following behavior.
If I go to the subpage 'Style Guide' which is not part of the single page landing page http://demo.getgrav.org/woo-skeleton/demo and then select either of the anchor links from the top bar, they will not work.
For instance, clicking features just enlarges the url in my brower to 
```
http://demo.getgrav.org/woo-skeleton/demo#features
```
This link doesn't exist and so the browser doesn't do anything.

I'm testing with Firefox and Chromium on Debian right now.

Any advice on circumventing this? Or should I just limit this skeleton to a single landing page for now?

Best regards,
Matthias

**Comment by rhukster** [comment]
It appears the menu has just got named anchors (e.g. `#pricing`) because the design is intended for a one page site.  However, the typography pages is intended to show some various typographic styles.

The menu could be fixed to point to the home page and then the anchor.  Not a big deal, it's a simple fix. I'll assign this to karol who did the theme port.

**Comment by rhukster** [comment]
I'm going to close this as it's actually a woo skeleton issue, not a grav issue.
