### ISSUE TITLE
Q: why not symfony config component?

### ISSUE THREAD

**Issue by wowcut** [getgrav/grav#2295]
Hi, I am just trying to understand the grav source a little bit and I would like to learn why are you not using the [symfony config component](https://github.com/symfony/config)? 
I am not trying to imply that you _should_ use that - I am just _interested_ in the reasons that made you build the rockettheme yaml file reader instead. Was that for some historical reasons or is there any problem you have seen with the symfony component?
Thanks!

**Comment by mahagr** [comment]
Mostly for historical reasons. When Grav was first created, it was supposed to be a very simple flat file CMS and using the Symfony component was seen as bloat because of its size.

There is another reason, though... Symfony Config requires you to define the configuration by writing PHP code and in Grav we wanted to avoid that (forms, page types, plugins etc could be built without PHP).
