### ISSUE TITLE
Twig Runtime Error (IE 11 and Edge 42)

### ISSUE THREAD

**Issue by lazzich** [getgrav/grav#2337]
Error Message: An exception has been thrown during the rendering of a template ("Template "modular/3-columns.txt.twig" is not defined."). The html.twig template with the same name is definitely there.

You can test this here:
https://www.aepfelundkonsorten.org/home

Site working in Chrome, FF and Edge 42. Not in Edge 41.16, IE 11.

**Comment by Perlkonig** [comment]
But you're requesting a `txt` file, not an `html` file. You need a `txt.twig` file or you need to fix your request so it's actually requesting `text/html` from Grav.

**Comment by lazzich** [comment]
Many thanks. Do you know where to do this setting in Grav?

**Comment by rhukster** [comment]
This is a browser or server issue.. If the browser is requesting a text file, then it's not serving the page correctly, or the browser is requesting a text resource when it should be requesting an html one.

**Comment by garytube** [comment]
I have the same Issue. 
Start happening after upgrading to 1.6.0-rc2

**Comment by garytube** [comment]
So the issue seams to be related to modular pages. All my other Pages are working just fine.
![image](https://user-images.githubusercontent.com/3823504/52478898-2615b380-2ba7-11e9-8e50-d47c272f1c81.png)

My landingpage.md
`---
title: Landingpage
slug: /

content:
    items: '@self.modular'
    order:
        custom:
            - _hero
            - _featured
            - _getstarted
            - _products
            - _news
---`

my templates:
![image](https://user-images.githubusercontent.com/3823504/52478999-6c6b1280-2ba7-11e9-984d-f506af435164.png)

I'm pretty sure my site worked before in IE11.
Since I have everything in git, i checkout at the pre-rc releases and the bug was also present. So forget about my comment above.

![image](https://user-images.githubusercontent.com/3823504/52479060-a50aec00-2ba7-11e9-94fb-762c5eab2c1b.png)


`php -S localhost:8000 system/router.php`   works just fine
maybe it's a htaccess problems? Any Ideas @rhukster  ?

**Comment by rhukster** [comment]
It's something with your webserver configuration, it's not setting the php mimetype correctly when the page is requested, and it's falling back to `text` because it's looking for `modular/featured_coherence.txt.twig` when it should be looking for `modular/featured_coherence.html.twig`.

The fact that it works with built-in webserver means it's not related to your content, configuration, or Grav itself, it has to be the webserver.

We probably did 'fix' something in the newer versions of Grav to ensure the mimetype was honored properly, and this is now exposing a setup issue for you.

**Comment by rhukster** [comment]
What you can try is to look at the request itself with the devtools.  It might shed some light on the matter.

**Comment by rhukster** [comment]
Also you might want to look at content negotiation in your apache config: https://httpd.apache.org/docs/2.4/content-negotiation.html

**Comment by rhukster** [comment]
Ok, i was able to replicate this on my windows machine!  I will investigate it!

**Comment by rhukster** [comment]
Ok, it did it one time, but after a refresh, it works every time.  Grr.. very tricky to track this down if i can't reliably replicate it.

**Comment by garytube** [comment]
Same here, we tested on a bunch machines now. Still got the error 
What IE11 Version are you using @rhukster 

you can check my test site 
http://gidrm.tbodev.de/en  (this is the landingpage with 3 modular elements)

**Comment by rhukster** [comment]
Found it! ok, not sure how this happens, but the order of the page types must be wrong.  I had `txt` first, and it should be html.  If you edit your `user/config/system.yaml` file... look for `system.pages.types` and change that array to:

```
  types:
    - html
    - htm
    - xml
    - txt
    - json
    - rss
    - atom
```

This fixed it for me.

**Comment by garytube** [comment]
maybe thats why ```Utils::getExtensionByMime($mimetype);``` always returned text/plain

and because I have different configs for stage/test/prod  the extension order was different on each server and i couldn't figure out why it was working on stage.

**Comment by garytube** [comment]
Fixed! Thank you so much!

**Comment by lazzich** [comment]
Did also fix it for me! Thanks guys for looking into it again.

**Comment by mahagr** [comment]
@rhukster Didn't you fix this already?

**Comment by rhukster** [comment]
seems not, i need to update the defaults in system.yaml

**Comment by rhukster** [comment]
Now done..

**Comment by hubionmac** [comment]
The re-ordering of the page types helped me also on Google index, since I got 5xx error every time I tried to reindex the page

**Comment by rhukster** [comment]
This fix is now in 1.6 release.

**Comment by vanilla-thunder** [comment]
sorry for reopening, but there might be a new side effect (mainly for custom themes):
when missing favicon image file, grav points favicon tag to web root
`<link rel="icon" type="image/png" href="/" />`
which makes browser request start page with `Accept: image/webp,image/apng,image/*` header.
And this request makes modular pages being rendered with `.txt.twig` insterad of `.html.twig` templates.
This happens in all browsers and changing the order of page types does not help. 

Since faulty href and src tags, causing browser to load website once again, are pretty common problem, probably grav should stick to first/default page type here instead of forcing txt?
It was kind of misleading In my case, since grav tried to render txt.twig template instead of just loading exactly the same page once again.

**Comment by mahagr** [comment]
@vanilla-thunder Could you please create a new issue on this? Also, could you provide a minimal example of what to install to reproduce this issue, it would save some time if some themes work and some not.
