### ISSUE TITLE
grav-admin Not found on debian apache

### ISSUE THREAD

**Issue by ghtmtt** [getgrav/grav#2368]
Hi all,

debian server with apache. 

While the *normal* grav package (after changing some apache configuration file) works, the grav-admin package gives a **NOT FOUND** page. 

Permissions and Apache configuration are the same (same server of course).

It really seems a admin plugin problem

**Comment by rhukster** [comment]
Nope, it's a configuration problem on your server: http://learn.getgrav.org/troubleshooting/page-not-found.

If you tried to create a second page on your normal Grav install, it would be a 404 also because your rewrites are not working. Please follow up in the Discord chat room if you need further assistance.

**Comment by ghtmtt** [comment]
Thanks for the help, working now

**Comment by Savva359** [comment]
I have the same problem and need your help ^-^
I can't fix it D:

**Comment by AleMunin** [comment]
@ghtmtt Could you be so kind to tell how did you fix the rewrite in apache?

I was installing grav and it pointed out I should enable mod_rewrite, I did so and then I just keep getting the 404 error.
