### ISSUE TITLE
Question: FlexObjects indexes

### ISSUE THREAD

**Issue by lufog** [getgrav/grav#2378]
I must say that I know that this feature is only in development. I'm not going to use it in production, I'm just curious how it works. I looked at the Grav test copy, how users are stored in FlexObjects mode. Quite interesting, just a question about the index files. Now they are stored on the path: ```user/data/{flexobject_name}/index.yaml```, in the folder is a single file. I think it would be more logical to store indexes like this ```user/data/index[es]/{flexobject_name}.yaml```. Or, if additional files should be stored in these folders, then so: ```user/data/index[es]/{flexobject_name}/index.yaml```. So they will not clutter up the ```data``` folder.

**Comment by w00fz** [comment]
I think all 3 ways are practically the same, it all just come down to organizational preference.

The folders approach used right now is mostly inline with the non-written standard that we use when putting stuff into the `user-data://`.

I see where you are coming from and I can imagine having a main `user-data://flex-indexes/` folder be very intuitive to reach and browse through, but on the other hand, it will be kinda hard to impose that because anyone who's going to use FlexObjects, will have total freedom about where they want their indexes to be stored.

So personally, I kinda like having all flex indexes under the same `user-data://flex-indexes/` folder, I am just unsure how much that matters.

I'll /cc @rhukster and @mahagr in here to see their thoughts. If this has to change, it should change NOW. Once it goes stable this will be just annoying to change.

**Comment by mahagr** [comment]
You can think of the index file as being like a database index, which allows you to make quick queries over the data. These indexes are stored into the filesystem, but they are also being cached to acpu. Indexes have minimum data of storage key and timestamp (last saved time) of the object, but they can contain extra fields, like in this case username and email address. 

These indexes are optional, meaning that if you remove the file, it gets rebuilt. The index also gets updated if the objects are saved, but this update process is independent of the save, meaning that if the cache expires, the index is being loaded from the filesystem together with full read over the filesystem to fetch storage keys and new timestamps for all the objects. If any of the objects were updated, the index is being regenerated for those objects by reading the files. 

Right now the index is stored with the data by default, but it can be customized inside the code. For users, I just picked up `user-data://accounts`. I have no preference where these should be and as Flex is still an experimental feature (and will be subject to change until 2.0 gets released as we need to add support for database storage etc), there will likely be more changes between the minor features.

You are free to play with Flex and even use the new features in a live site, but beware that there may be some minor tweaks you need to apply when you are upgrading from 1.6 to 1.7 etc.

**Comment by w00fz** [comment]
Even tho it doesn’t really matter much and changing location is no big deal, since indexes just get regenerated in the new location, I now do prefer @Lufog-git  structure suggestion.

`user-data://flex-indexes/accounts.yaml`

If we use this structure as a standard, it will be definitely easier to browse. Granted most people won’t care about those indexes and granted some other developer might pick a different location, but that’s ok.
