### ISSUE TITLE
404 not found on first interaction with grav admin

### ISSUE THREAD

**Issue by symfonysos** [getgrav/grav#2387]
The first try to use grav leads to a 404 - this is a very frustrating first contact experience. Seems like this cms does not work when put into a subfolder of a webserver (with a working php configuration, other cms just work). 

It would be a much better experience for users, if grav would _just work as expected out of the box_ - you should change the default for the grav distribution to make it work _by default_ in every situation (on a webserver with php), and offer an _optional_ rewrite config that allows for nice urls. That way you would gain way more users - for many people understanding how to change rewrite rules is an impossible to solve technical miracle. 

BTW I am able to understand what goes wrong and also I am able to change my nginx config - I am trying to make you understand that many people are _not_ and grav currently is not usable by these people. It would be easy to change if grav was able to adapt to the situation or work without rewrites. 

I just had this scenario today, a non-tec friend found your website, wanted to install grav - what means he uploaded it to a webserver with php - and then he called me because of "strange 404 errors on his new website". It took him a while to understand that the "works out of the box" promise on the getgrav.org website is actually not true for 99% of users. It would take him weeks to understand what "rewrite" means. No chance. A few hours later he now has his website ready with wordpress. 

This is just a good example of how important defaults are - would this cms really work oob in any php enabled subdirectory, it would make adaption much easier. I guess 90% of users just see a "404" on first contact and go back to wordpress.

**Comment by rhukster** [comment]
This is not a Grav error, but lack of rewrite configuration.  This is not optional because every production website should be using them.  Grav is a **modern** CMS and that means URLs with extraneous query parameters and non-SEO friendly URLs is just not acceptable these days.  Most beginners (possibly 99%) have rewrites working out of the box as they mostly run Apache (WAMP servers, shared hosting, etc) and the included `.htaccess` will be automatically configured.  For those not running Apache, most of those are more experienced and are used to setting up vhosts and rewrites for WordPress/Drupal/Joomla etc.  

FYI Grav is not really trying to be a beginner's CMS, it's not meant for casual users.  It's meant as an alternative for developers who are either building sites for themselves or others.  However, Grav can be used by beginner developers who are willing to learn and improve their web development skills, and many people have successfully done this.

Thanks for your thoughts though.

**Comment by symfonysos** [comment]
It is interesting to learn how do you think about this issue. I totally understand your point and support your opinion, however I still believe every cms looks more professional if the system just works in all expected situations. 

Regarding "Apache everywhere", please update your data:
https://news.netcraft.com/archives/2018/01/19/january-2018-web-server-survey.html

I wish you good luck with this nice project!
