### ISSUE TITLE
Feedback desired for new plugin leaflet-address

### ISSUE THREAD

**Issue by foxfabi** [getgrav/grav#2433]
I would like to receive feedbacks for my new plugin **leaflet-address** from the Grav community. It is my **first project** using Grav CMS. Here are the project details: [**foxfabi/grav-plugin-leaflet-address**](https://github.com/foxfabi/grav-plugin-leaflet-address)

Leaflet Address is a Grav CMS Plugin thats add the ability to easily embed a leaflet map to display an address with a marker. The plugin provides a Twig template that you need to include in your theme where you want to add the leaflet map. 

After entering the address, the coordinates can be determined and saved with the API of [photon.komoot.de](http://photon.komoot.de/). At the moment the following map provider are available:
 * OpenStreetMap Mapnik
 * Esri WorldStreetMap
 * CartoDB Voyager

The [Marker icons](pointhi/leaflet-color-markers) are provided by Thomas Pointhuber @pointhi 

Currently i'm working on the translations .. 
 * https://github.com/foxfabi/grav-plugin-leaflet-address/blob/ce8ec6b9d5940edfa32211d92cf4a559c826660c/admin/templates/forms/fields/coordinateselector/coordinateselector.html.twig#L8
* https://github.com/foxfabi/grav-plugin-leaflet-address/blob/ce8ec6b9d5940edfa32211d92cf4a559c826660c/leaflet-address.php#L129

Glad to hear your feedback.

**Comment by rhukster** [comment]
Would be nice if you offered a shortcode to include this rather than just having the Twig option.  An example of this can be found in the prism-highlight plugin: https://github.com/trilbymedia/grav-plugin-prism-highlight

You really just need to create a shortcut (the shortcut can probably leverage the same Twig file you already have).  Once you have a shortcode, then you just register it in the main plugin.

**Comment by foxfabi** [comment]
Thanks for feedback, I just committed the changes.

**Comment by rhukster** [comment]
Added to GPM for next regen
