### ISSUE TITLE
Error JS v1.6.5

### ISSUE THREAD

**Issue by AstroHaze** [getgrav/grav#2461]
Hi guys, i tried update my installation v1.5.10 in the new version but there is a multiple error, so i try a new installation with last update (1.6.5) and i import my pages, i find this problem wiht Jquery.

If i delete in baste.html.twig at line 36 when the code is 

```
34 {% block assets deferred %}
35    {{ assets.css()|raw }}
36    {{ assets.js()|raw }}
37 {% endblock %}
```

the problem apparentment is resolve, but not work the jquery and another librarys, how i resolve?

**Comment by rhukster** [comment]
Not really following what the exact problem is.  Jquery is not loaded? Which theme are you using? Is it custom?

**Comment by AstroHaze** [comment]
theme is Quark, this is the problem https://ibb.co/jbgHNvp

**Comment by rhukster** [comment]
Sounds like same issue as this:  https://github.com/getgrav/grav/issues/2458#issuecomment-484187238

Something in your code is adding an asset with a `priortity` that is not an integer.  could be a custom plugin, maybe try disabling them one-by-one until you locate it?

In the meantime, I will look to see if i can ensure these are 'cast' to integers to stop the error, but really the issue lies in some come somewhere.

**Comment by AstroHaze** [comment]
ok thanks, i find the plugin is Lazy Image by Matthew M. Crumley

**Comment by rhukster** [comment]
might want to open an issue on that plugin to address the underlying issue, but my fix should stop the error.

**Comment by astroVibes** [comment]
Hi, i'm resolve the problem in Windows 10 with this simple command `npm i -g gulp-cli`
