### ISSUE TITLE
New plugins can overwrite not  published plugins if the name is the same

### ISSUE THREAD

**Issue by aligator** [getgrav/grav#2489]
Some time ago I created a simple plugin named "Antispam" for myself. I did not publish it.

Now with the last Update of my grav-plugins, I noticed, that grav tries to update Antispam 0.0.1 to Antispam 1.1.1

And the update worked. So after the update I had a plugin running on my server I never intended to install! No warning, nothing...

This should not be possible.

**Comment by rhukster** [comment]
Grav doesn't keep a list of 'plugins installed via GPM'.  All it does is go through your plugins directory and match names in there to ones in GPM.  This is a powerful feature that lets you easily install plugins or create new ones on-the-fly without them being in GPM.

However, in your case your naming your plugin the same as on in GPM is causing an issue.  I suggest simply creating your plugins with a unique prefix should ensure this never happens.

i.e., call your plugin `aligator-antispam` rather than a generic `antispam`.
