### ISSUE TITLE
Plugin templates not namespaced

### ISSUE THREAD

**Issue by flaviocopes** [getgrav/grav#255]
It happens that the "Private" plugin has a `login.html.twig` template. 
It happens that the "Login" plugin has a `login.html.twig` template. 

When the page runs and the "Private" plugin renders the `login.html.twig` template, actually it renders the Login's plugin `login.html.twig`.

See http://getgrav.org/forum#!/general:login-and-private-plugin

**Comment by Sommerregen** [comment]
Can we close this? Because this is plugin specific. We should ask and guideline the authors to put all their "special" Twig files in the `templates/plugins` or maybe `templates/plugins/<plugin_name>` folder (depends on the amount of Twig files). Only necessarily Twig files should go into `templates/partials` etc.

**Comment by flaviocopes** [comment]
Yep it is a conflict between two plugins. With the amount of plugins growing this can be a more frequent issue, but I agree this can be easily solved in the plugin level, using a plugin-specific folder for twigs for example.
