### ISSUE TITLE
Twig update

### ISSUE THREAD

**Issue by drzraf** [getgrav/grav#2572]
Although Twig 2 would be a must-have, I would like to pull your attention on the fact that Twig 1.41, released May 14th provides a lovely `filter` filter (+ `map` and `reduce`) : https://twig.symfony.com/doc/2.x/filters/filter.html
(NB: It also support PHP 7.4)

Would be nice to have inside Grav's next tarball.

**Comment by drzraf** [comment]
Just saw changelog for 1.7 with Twig 2.11 (note 2.11.3 includes fixes in the `filter` filter). Good!
BTW, I hope Grav will go composer one (not so far) day ;)

**Comment by mahagr** [comment]
Currently, we're using the latest Twig 1.x, but the code is also running in Twig 2.x. The issue on upgrading to Twig 2 right now is that a lot of templates will break because of using deprecated features. So final jump to Twig 2 will likely have to wait to Grav 2.0 where we can break backwards compatibility.

PS: There are instructions in learn site on what to fix when moving to Twig 2.

**Comment by paulhibbitts** [comment]
I didn't know that @mahagr , thanks for the heads-up! https://learn.getgrav.org/16/advanced/grav-development/grav-16-upgrade-guide#deprecated-twig

**Comment by mahagr** [comment]
I recommend everyone to update their themes/plugins using the above documentation. :)
