### ISSUE TITLE
Paragraphs plugin

### ISSUE THREAD

**Issue by localnetwork** [getgrav/grav#2578]
This plugin helps normal user to design their page by adding paragraph item. 
Developer create templates(paragraph types) to be used in adding paragraph items.

- You can also limit the paragraph types in every page types(content types).

Example:
- Add a block of text with an image left to it
- Add a slideshow between blocks of text
- Add a youtube embed between your text
- Add quotes between your content blocks

[More Info Here](https://www.drupal.org/project/paragraphs)

**Comment by rhukster** [comment]
Is this plugin for Grav?

**Comment by localnetwork** [comment]
Is this plugin for Grav?
- Yes

**Comment by rhukster** [comment]
I'm not seeing a GitHub URL for this Grav plugin, the link takes me to a drupal page.

**Comment by N-Parsons** [comment]
@localnetwork, if you have a working version of this plugin for Grav, I would love to see it. Alternatively, you could build one!

I have something vaguely similar that I was working on recently, but it much more basic, and it's not likely to be production-ready for a while, because for now it does literally just what I need it to.
