### ISSUE TITLE
My plugin has a new name

### ISSUE THREAD

**Issue by Memurame** [getgrav/grav#2618]
I have renamed the plugin name from `grav-plugin-smartthings` to `tools-collection.`

https://github.com/Memurame/grav-plugin-tools-collection

Please update the GPM

**Comment by w00fz** [comment]
It would be nice if your plugin was in English and then had a German translation.

Especially for things like the README. Many people don’t speak German and might be thrown off by the plugin just because they can’t read what it does.

When I first saw SmartThings I thought the plugin was about the Samsung SmartThings and the IoT, I know realized it hasn’t anything to do with that and it’s a collection of tools.

Maybe it shouldn’t be reserving that name? 
Have you considered calling it `grav-toolbox` or `grav-utilities` or something like that?

**Comment by Memurame** [comment]
I did not know Samsung Smart things. The name grav-toolbox is not available, this was communicated to me when submitting the plugin. The objection about Samsung is good. I've thought of a new name

Unfortunately, my English is not so good that I could write a complete guide in English. I already use google for this text ;-)

Name update in the first post

**Comment by rhukster** [comment]
Updated your plugin's name in GPM.
