### ISSUE TITLE
Unsupported Content-Coding: none

### ISSUE THREAD

**Issue by JFossey** [getgrav/grav#2619]
Hi,

I have recently revamped a pre-existing website developed in Yii using GravCMS.

When I have look to test the site using using tools like W3C validator and Chrome dev tools I get and error **"Unsupported Content-Coding: none"**.

When I look into this issue I find Content-Encoding header can take only five values: gzip, compress, deflate, identity, br. The “none” is therefore an invalid value.

**Ref:** 
- Related Issues: https://github.com/getgrav/grav/issues/548
- Related Docs: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Encoding

**Comment by JFossey** [comment]
Just to follow up on this, the only **workaround** I found thus far is the following settings.

- Gzip compression = YES
- Allow WebServer Gzip = NO

**Comment by rhukster** [comment]
Thanks for researching this.  I am going to add this to the troubleshooting section of the learn site.

**Comment by mahagr** [comment]
The issue is caused by this line:

https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Grav.php#L404

I think there was a reason why we ended up using none as the value; I think it prevents webserver from compressing the request.

**Comment by JFossey** [comment]
I looked for an alternative way of preventing gzip compression and found the following. 
Hope it helps. The **apache set env** looks promising for many common setups.

```php
function disable_gzip() {
	@ini_set('zlib.output_compression', 'Off');
	@ini_set('output_buffering', 'Off');
	@ini_set('output_handler', '');
	@apache_setenv('no-gzip', 1);	
}
```

**Comment by mahagr** [comment]
@JFossey Can you test out the change?

**Comment by JFossey** [comment]
@mahagr I have not yet tested it out, but I will, it just might be a while before I get round to this.

**Comment by JFossey** [comment]
@mahagr This seems to work as intended, thank you.

**Comment by awrog** [comment]
Adding a concrete real-world case where this breaks an actual HTTP client, not just linting/validation tools.

I ran into this via Grav's api plugin (v2.0.11) being consumed by an Android app built with MIT App Inventor. The app's Web component (which uses Java's HttpsURLConnection under the hood) consistently failed with a generic "unable to get a response" error (App Inventor error 1101) — no HTTP status code, no body, just a dropped/failed connection at the client's networking layer.

This happened consistently across two completely different server setups (direct origin via Apache/DirectAdmin, and again after fronting the domain with Cloudflare), which ruled out hosting-specific causes. Meanwhile curl, desktop/mobile browsers, and other Android HTTP clients (e.g. OkHttp-based apps) all handled the exact same response without any issue — presumably because they're more lenient about parsing an invalid Content-Encoding value, while HttpsURLConnection is stricter.

Setting system.cache.gzip: true (or otherwise avoiding the code path that emits Content-Encoding: none) immediately resolved it — confirmed via curl -I showing Content-Encoding: identity afterwards, and the Android app working correctly right after.

I understand the header is intentional (to signal upstream servers not to double-compress), but since none isn't a registered content-coding (per [RFC](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Encoding), valid values are gzip, compress, deflate, identity, br), it seems worth considering emitting identity instead in this code path — that would communicate the same "don't compress" intent to the webserver while staying spec-compliant, and would avoid breaking stricter HTTP clients like the one above. Happy to test a fix if one gets proposed.

**Comment by rhukster** [comment]
Thanks @awrog, that's an excellent write-up — the `curl -I` before/after and ruling out the hosting layer pinned it exactly.

You're right that `Content-Encoding: none` is not a valid content-coding, and it's worth fixing. One subtlety on the suggested `none` → `identity` swap though: `identity` is specifically the value webservers read as "this body is *not* encoded, go ahead and compress it," so in this particular fallback it could invite mod_deflate to recompress the response and invalidate the `Content-Length` we set right after — which is the whole reason that branch exists. That fragile "emit a bogus encoding to scare the server off compressing" trick is really the root problem.

So rather than trade one questionable header for another, I've removed the invalid header entirely for that path. For context, this branch only runs on non-FastCGI setups (under PHP-FPM/FastCGI `fastcgi_finish_request()` handles the early close and none of this fires), when gzip is off and `apache_setenv` isn't available. In that last-resort case Grav now simply skips the `Content-Length`/early-close micro-optimization and lets the response close cleanly via `Connection: close`, instead of sending a spec-violating value. No more `Content-Encoding: none`, and strict clients like `HttpsURLConnection` get a clean response.

Fixed on `develop` and it'll ship in the next 2.0 release. If you're able to point your setup at `develop` and confirm the Android/App Inventor client is happy without needing `system.cache.gzip: true`, that'd be a great sanity check — but either way it's in. Thanks again for the thorough report.
