### ISSUE TITLE
Changing the preview url

### ISSUE THREAD

**Issue by AndrewNB** [getgrav/grav#2642]
QUESTION:

I am using Grav as a headless CMS with React.  I'm trying to give editors of the site the ability to preview the page which is hosted elsewhere.

Is there a way of changing the Admin preview URL to link to the domain where the front end of the site is?  So /page-1 becomes OTHERHOST.com/page-1.  **Redirect** dosn't work for this case as I still need to access /page-1.json to get the content.  

Thanks.

**Comment by ulab** [comment]
This is more of a support request than an issue with the Grav. You'd probably be better off asking this on the forum: https://discourse.getgrav.org/

That said, you should be able to change ./user/plugins/admin/themes/grav/templates/preview.html.twig and adjust the preview_link variable accordingly. 

I am not sure how to make this change permanent though since it might be overwritten by upgrades of the admin plugin.

**Comment by rhukster** [comment]
There is currently no way to change this as it's hardcoded into the admin.  As we have plans to rebuild the admin in VueJS on top of an all new Grav API layer, we're not planning on making major changes to the current admin.

**Comment by AndrewNB** [comment]
Thanks ulab and Andy, that's answered my question.  Cheers

**Comment by mahagr** [comment]
Grav 1.7 with Flex pages will make this possible, though likely with some custom code.
