### ISSUE TITLE
Traling slash is removed in canonical tag even if a custom route is specified

### ISSUE THREAD

**Issue by LeFrenchie** [getgrav/grav#2735]
Hello,

I have a custom route for keep historic url of my site with a trailing slash.
But the canonical tag (by default if empty or if specified) cut the trailing slash.

Is it a bug or mistake from me ?

Thx

![image](https://user-images.githubusercontent.com/3471181/69008148-59138180-0947-11ea-9090-bc6e541067f9.png)

![Capture d’écran 2019-11-17 à 14 37 40](https://user-images.githubusercontent.com/3471181/69008176-dfc85e80-0947-11ea-8c32-ba8b025926e6.png)

**Comment by LeFrenchie** [comment]
Hello, for me, it is more than a question, I think is it a bug.
can you reproduce this bug ?

**Comment by mahagr** [comment]
There's no difference between URLs without slash and with a slash, so they get removed to be able to match both at the same time.

Try changing setting which adds the trailing slashes to the urls.

**Comment by AndrassGray** [comment]
Interestingly, this topic has come up on some SEO slack (yesterday?). The take-away from a SEO/SEM view-point :

these are the same : 
https://domain.tld
https://domain.tld/

these are *not* the same
https://domain.tld/page
https://domain.tld/page/

**Comment by mahagr** [comment]
I know they aren't really the same, the first will look for filename first, then if it's not found, it'll check if the folder exists with index.html file in it. The second url with the trailing slash just looks for the folder.

Do you have setting removing the trailing slash turned on? Because of that setting is applied to all urls, including canonical as you asked the site not to use the trailing slash in its urls.

**Comment by mahagr** [comment]
Ok, looks like Grav does not really support routes with trailing slashes in them. They are always been removed, which means that canonical urls will not have them either.
