### ISSUE TITLE
[add-resource] Plugin update remains unnoticed

### ISSUE THREAD

**Issue by bleutzinn** [getgrav/grav#2742]
An new release of one of my plugins last October (October 10the 2019 to be exact) still hasn't found it's way into the Grav Repository

 I'm referring to my [Add Page by Form Plugin](https://github.com/bleutzinn/grav-plugin-add-page-by-form).
I've checked the release, the changelog file and blueprints.yaml file version number and the do match: v2.3.1 yet the repository still shows v2.3.0.

What am I doing wrong or maybe something else is causing this? Thanks for looking into this!

**Comment by rhukster** [comment]
If you go here and look at the tags: https://github.com/bleutzinn/grav-plugin-add-page-by-form

You will price that your latest version is at the bottom of the list and not with the other 2.x releases.  This is because you tagged it V2.3.1 instead of v2.3.1. Notice the capitalization. This has broken the semver  format.  

Deleted the release and the tag and rerelease with lowercase like all the other tags.

**Comment by bleutzinn** [comment]
Ah, than you very much. I've just created a new "lowercase v release".

BTW is being case sensitive of the release tag important?

**Comment by rhukster** [comment]
Yes it critical.  Also keeping the same format.  If you use a ‘v’ keep using it orbit will also cause problems.

**Comment by rhukster** [comment]
BTW, you fixed the tag but the blueprints in the 2.3.2 tag still say 2.3.1:

https://github.com/bleutzinn/grav-plugin-add-page-by-form/blob/v2.3.2/blueprints.yaml

hence, it's still not updating

**Comment by bleutzinn** [comment]
Thanks for the heads-up. Updating is working again.
I'll take more care in the future.
