### ISSUE TITLE
Summary in Markdown causing error after update to PHP 7.4

### ISSUE THREAD

**Issue by jasonccox** [getgrav/grav#2751]
After updating to PHP 7.4, I'm seeing a `Trying to access array offset on value of type null` error caused by having a summary in a Markdown file when `pages.markdown.extra` is `true`.

**System Details**
OS: Arch Linux
Browser: Firefox 70
PHP: v7.4
Grav: v1.6.18, also happening with `develop` branch
Theme: Quark, as well as my custom theme (Webfolio)

**Steps to Reproduce**
1. Install Grav 1.6.18 using the `.zip` download.
2. Create a page that has a summary in the Markdown file. For example, I created a page with the `default` template in Quark that looked like this:
    ```markdown
    This is the summary.

    ===

    And this is the content
    ```
3. Set `pages.markdown.extra` to `true` in `user/config/system.yaml`.
4. Access the page.

**Error Message**
`Trying to access array offset on value of type null` caused by line 241 of `vendor/erusev/parsedown-extra/ParsedownExtra.php`:
```php
    protected function blockSetextHeader($Line, array $Block = null)
    {
        $Block = parent::blockSetextHeader($Line, $Block);

        if (preg_match('/[ ]*{('.$this->regexAttribute.'+)}[ ]*$/', $Block['element']['text'], $matches, PREG_OFFSET_CAPTURE)) // THIS LINE
        {
            $attributeString = $matches[1][0];
 
            $Block['element']['attributes'] = $this->parseAttributeData($attributeString);
 
            $Block['element']['text'] = substr($Block['element']['text'], 0, $matches[0][1]);
        }
 
        return $Block;
    }
```

**Comment by rhukster** [comment]
It does appear to be a PHP 7.4 issue in Parsedown Extra. Please create an issue here: https://github.com/erusev/parsedown-extra/issues

We're running the latest stable release of Parsedown Extra: `0.7.1`

I suggest sticking to 7.3 for now.

**Comment by Tracerneo** [comment]
The problem persists, parsedown-extra got updated, current stable version is 0.8.1.
Is it possible to update the dependency in Grav now?

**Comment by xf-** [comment]
@rhukster would be grate to get 0.8 into 1.7 branch before it releases.

**Comment by rhukster** [comment]
I'm looking at getting Parsedown Extra 0.8 into Grav 1.7, but it does require a newer version of Parsedown that is not 100% compatible with some Grav plugins.

**Comment by xf-** [comment]
1.6.4 parsedown release sounds mare breaking (rawHTML feature backport from 1.8 beta) as 0.8 of parsedown-extra. Some adjustments for 1.8 beta support and no mentions of something breaking https://github.com/erusev/parsedown-extra/releases

**Comment by rhukster** [comment]
1.7.4 is required for Parsedown-Extra 0.8.  1.7.0 had the security escaping of HTML, so that is what kicked off the whole 1.8 beta development, it began as a refactor to provide the functionality to allow HTML to be output (the `rawHTML()` method).  That's why we stuck with 1.6.3 for so long, it was 'less secure' but 1.7.x broke a lot of stuff with no way to write raw HTML (this was added to 1.8 beta)! Luckly they did backport the `rawHTML()` method to 1.7.4, but that means the security 'fixes' are still there and this is what breaks a lot of plugins in Grav.

I have a Parsedown 1.7 feature branch in development, and i've got a couple of plugins that also have fixes, but 3rd party plugins will just not render until they are updated to use `rawHTML()` method rather than `text` as they were doing pre Parsedown 1.7.0

You can test it here: https://github.com/getgrav/grav/tree/feature/parsedown-1.7-compatibility
