### ISSUE TITLE
Inconsistent image URLs in markdown

### ISSUE THREAD

**Issue by SeriousKen** [getgrav/grav#2779]
If you have an image and embed it in the markdown `![](image.jpg)` then the URL to the image is the directory path `/user/pages/01.page/image.jpg` but if you have a simple link to the image file `[link to image](image.jpg)` then the URL is relative to the page `/page/image.jpg`

Even more weird is if you use an action on an image `![](image.jpg?cropZoom=200,200)` and then follow it with `![](image.jpg)` then the link is to a file in the `images` folder `/images/1/c/b/1/c/1cb1ce5d61e4ac9570fef25261bb5781ce305d9b-image.jpg` which is just a copy of the original image.

**Comment by mahagr** [comment]
This is because of the first location is the file itself, second one does not check if there's an image and the third one is resized cached image.

**Comment by SeriousKen** [comment]
I understand why those URLs are the way they are, but this is down to an implementation detail. If I create a link to ![](image.jpg) I should get the same URL all the time, but I don't depending on the circumstances. I would also prefer not to expose the filesystem details in the URL but have it relative to the page URL as I would like to lock down direct access to the `user` folder.

**Comment by rhukster** [comment]
Some details here: https://learn.getgrav.org/16/content/image-linking

if you don't perform any operations on the image, you will get the file system path.. this is because the browser will request the file directly, and it's not efficient to go through Grav to serve up an image, better to let the webserver serve the image directly off the filesystem.  

If you perform an operation, the image is manipulated and a 'cached' image is created in `/images/ folder that is then served directly.

You can set an option so all images are 'cached' automatically by default - https://learn.getgrav.org/16/basics/grav-configuration#images

this way they will basically be 'copied' to images folder and served from there.  you can also pass `?cache` to the image to do it on a per-image basis

```
![](muertos.jpg?cache)
```
