### ISSUE TITLE
When caption property is null/undefined in image metadata, image is output instead

### ISSUE THREAD

**Issue by jacobrayschwartz** [getgrav/grav#2817]
Hi folks, I've been trying to figure out an issue with images. It seems that if a property isn't defined in the metadata, for instance, caption, twig template still act like it is defined.

For example, with the following meta file:

```yaml
alt_text: "MyImage"
title: "My Image"
```

and the following code in the template:

```php
{% set image = page.media.images|first %}
{{ image }}
{% if image.caption %}
<div>
  {{ image.caption }}
</div>
{% endif %}
```
image.caption evaluates as truthy. Furthermore, instead of an empty string, image.caption actually outputs the HTML for the image itself, with the variable as a query parameter added to the image's url:

```html
<img title="MyImage" alt="MyImage" src="/images/a/1/9/2/2/a19222c3692c0ccb30ba55a8136ef4b943d14a06-myimage.png">
<div>
    <img title="MyImage" alt="MyImage" src="/images/a/1/9/2/2/a19222c3692c0ccb30ba55a8136ef4b943d14a06-myimage.png?caption">
</div>
```

(Edited for better example)

**Comment by frankfarm** [comment]
@jacobrayschwartz, I am able to reproduce the problem you described in Grav 1.6.31. I’m able to get the expected behavior (no `div` when `caption` is not set) with this code instead:
```
{% set image = page.media.images|first %}
{{ image }}
{% if image.metadata.caption %}
<div>
  {{ image.metadata.caption }}
</div>
{% endif %}
```
`image.meta.caption` also works. I am newish to Grav development and am not sure that either of these is the correct way to access the data, but maybe someone else can explain why these work and why `image.caption` does not.

**Comment by rhukster** [comment]
This is actually due to the way that the Image 'media' object handles magic-methods for processing.  It doesn't return null or false if the method is not found, it simply returns the object again. This is to ensure that chaining methods don't fail.  e.g. (`image.cropZoom(300,200).sepia.html`).  

@frankfarm has already provided the better way if you need to determine if the metadata value actually exists or not.
