### ISSUE TITLE
Wrong markdown rendering for html code blocks in blog list page

### ISSUE THREAD

**Issue by SykieChen** [getgrav/grav#2879]
When writing a code block containing html codes, the codes inside the block are mistakenly rendered in Blog List view. Like blow:  
![image](https://user-images.githubusercontent.com/5460009/79145924-7405f700-7dfc-11ea-8493-79cd6e6d4089.png)

The page is correct when displayed in detail view:  
![image](https://user-images.githubusercontent.com/5460009/79145976-8aac4e00-7dfc-11ea-9911-948a1015ebc2.png)

The page content is like:  
![image](https://user-images.githubusercontent.com/5460009/79146029-a0ba0e80-7dfc-11ea-8adf-11d5c36caa46.png)

And the construction of pages is like below:  
![image](https://user-images.githubusercontent.com/5460009/79146060-b8919280-7dfc-11ea-94a5-accb2924ed45.png)

**Comment by rhukster** [comment]
This is because you have a large code block at the start of your article, and the listing view shows a summary of X amount of chars.  This is breaking in the middle of your code block.

The simplest way of addressing this is to put a manual summary and use the manual 'summary-delimiter': https://learn.getgrav.org/16/content/content-pages#summary-size-and-separator

**Comment by SykieChen** [comment]
> This is because you have a large code block at the start of your article, and the listing view shows a summary of X amount of chars. This is breaking in the middle of your code block.
> 
> The simplest way of addressing this is to put a manual summary and use the manual 'summary-delimiter': https://learn.getgrav.org/16/content/content-pages#summary-size-and-separator

Got it, thank you very much.

**Comment by SykieChen** [comment]
Sorry, even I make the code block very short, the content of the block is still rendered wrong.
Like the article blow:

![image](https://user-images.githubusercontent.com/5460009/80015996-78719480-850d-11ea-8400-a69bb4f7c86b.png)

The rendered article on blog list page is like this:

![image](https://user-images.githubusercontent.com/5460009/80016059-8fb08200-850d-11ea-8b08-29e3159357c9.png)

The html marks are all gone.
In item detail page it works fine:

![image](https://user-images.githubusercontent.com/5460009/80016129-a7880600-850d-11ea-85ab-54ecd76e0dc8.png)

Thank you very much.

**Comment by rhukster** [comment]
I think this is because HTML is stripped in the `page.summary()` method, so it's actually stripping your HTML from your code block too. 

You could use `page.content()` rather than `page.summary()`, but you might need to limit the chars with the `truncate` twig filter: https://learn.getgrav.org/16/themes/twig-filters-functions#truncate-a-string

**Comment by SykieChen** [comment]
Okay got it. I found the possibly related codes in the Quark theme:
https://github.com/getgrav/grav-theme-quark/blob/72ea4408f9ba11911c032e30712fe58f99eb421d/templates/partials/blog-list-item.html.twig#L16-L22
I will try to make some test and make a PR if I can fix it.
Thanks a lot!

**Comment by rhukster** [comment]
I don't think it something that is worth a PR. as it's very specific to your use case. I would create your own theme based on quark (using devtools plugin), and make your modification there.

**Comment by SykieChen** [comment]
Okay, I guess there maybe some people who want to put a HTML code block at the beginning of their article. Is the `Page::summary()` method designed to strip HTML tags inside a code block?
Anyway I really appreciate you for doing these, thank you very much.
