### ISSUE TITLE
Grab Second Uploaded File

### ISSUE THREAD

**Issue by ma1n** [getgrav/grav#2895]
Hey, I'm currently trying to learn everything about grav and like it so far. The only issue i'm facing is that I have a news section with two headline images that i'd like to be easily changeable. I can access the first page media with 

`            {% set image = page.media.images|first %}
            {% if image %}
                {{ image.cropResize(400,400).html('','','img-fluid'~page.header.image_align) }}
            {% endif %}
`

but how am i grabbing the second one? page.media.images|second doesn't seem to work.

**Comment by ricardo118** [comment]
@ma1n you can either do `{{ page.media.images[1] }}` since its just an array you can access it like a normal array. alternatively you can access an image via its name, like ` {{ page.media.images['header.jpg'] }}` another option would be using a variable in the page like `{{ page.media.images[page.header.headline] }}`
