### ISSUE TITLE
Hook into page save (non-admin)

### ISSUE THREAD

**Issue by djairhogeuens** [getgrav/grav#2907]
Hi, is it possible to hook into some **event** that is triggered every time a **page is saved (create/update) or deleted**? I see that there exist some admin events for this but in this case I have a plugin that performs page modifications and therefore doesn't trigger the admin event.

I find the events documentation to be very unclear and as I have already spent quite some time on this trying stuff out without success, I was hoping to find an answer here.

Any help is more than welcome! Thanks.

**Comment by ricardo118** [comment]
you can trigger your own custom events like `Grav::instance()->fireEvent('onMyPluginBeforeSave', new Event(['page' => $this]));`

If you explain your needs a little more maybe we can provide some more details. Or join the discord and get real time help [Discord](https://discord.gg/5DsmwT)

**Comment by djairhogeuens** [comment]
Thanks for your reply. I know how to trigger custom events but the what I want to do here is have my plugin adjust page content using the Grav API and as a consequence I want to have another plugin listening to such changes and do something. More specifically, I am using this plugin https://github.com/Regaez/grav-plugin-api to make changes to pages and I want the GitSync plugin (https://github.com/trilbymedia/grav-plugin-git-sync) to synchronize those changes to a Git repository. However, the GitSync plugin only seems to be listening to page changes done through the admin portal (so the admin events I was talking about) while the REST API plugin does not trigger those events (nor does Grav trigger these events) which also makes sense.

I had the idea to write a custom integrator plugin that listens to page changes (for which I need an event to listen to) and then trigger the gitsync event as a consequence. This way I have an integration between the two plugins while still maintaining a loose coupling. Therefore my original question: is there an event that is triggered every time a page is saved or deleted (except for the admin events).

**Comment by ricardo118** [comment]
well i don't know anything about the Plugin API however it definitely seems like that API plugin should expose its own events. However, gitsync plugin does not sync without admin because of security reasons. That way its ensured that the user is allowed to login into Admin itself. 

You could attempt to just copy/trigger git sync directly from your plugin that makes the changes. 

For the new flex pages, there are events that trigger on every page save. This is for grav 1.7+

However, flex pages are significant changes to legacy pages so it is possible you will need to update your plugin to use flex instead
