### ISSUE TITLE
[add-resource] New Plugin/Theme: Markdown Yet Another Linker

### ISSUE THREAD

**Issue by HuidaeCho** [getgrav/grav#2979]
I would like to add my new plugin/theme to the Grav Repository.
Here are the project details: [HuidaeCho/grav-plugin-markdown-yalinker](https://github.com/HuidaeCho/grav-plugin-markdown-yalinker)

This new plugin named Markdown Yet Another Linker (markdown-yalinker) allows the user to create links with less typing in certain cases using MediaWiki-like syntax. For example, in regular Markdown, `[Page Title](page-title)` requires typing the page name almost twice. Typing page slugs is also error-prone. This plugin allows `[[Page Title]]`, `[[Page Title|Text]]`, `[[../Relative/Page Title]]`, `[[../Relative/Page Title|]]`, etc. For more details about this syntax, please check [its usage](https://github.com/HuidaeCho/grav-plugin-markdown-yalinker#Usage).

This plugin addresses the issue in [this topic](https://discourse.getgrav.org/t/page-linking-with-less-typing/13021).

Thanks!

**Comment by rhukster** [comment]
This needs a release before it will show up in GPM.  See https://learn.getgrav.org/16/advanced/grav-development#theme-plugin-release-process

**Comment by w00fz** [comment]
@HuidaeCho Did you perhaps miss the above? We can't really publish this until there is a tag/release of the plugin.

**Comment by HuidaeCho** [comment]
@rhukster @w00fz Thanks for the follow up. I just created a release. https://github.com/HuidaeCho/grav-plugin-markdown-yalinker/releases/tag/v1.0.0

Thanks!

**Comment by w00fz** [comment]
I think you have inconsistent versions for your blueprint/tag/changelog. Your tag should match everything else. Right now you have `v1.0.0` as tag and reference that in CHANGELOG too (https://github.com/HuidaeCho/grav-plugin-markdown-yalinker/tree/v1.0.0), however in your blueprint (https://github.com/HuidaeCho/grav-plugin-markdown-yalinker/blob/v1.0.0/blueprints.yaml#L4) the version is `0.1.0`.

What I would suggest you do before I publish your plugin:

1. delete your release AND tag
  1. Go to https://github.com/HuidaeCho/grav-plugin-markdown-yalinker/releases/tag/v1.0.0
  2. Click `Delete Release`
  3. Click on the `v1.0.0` tag (same URL as above should work too)
  4. Click `Delete Tag`
2. Edit your blueprints.yaml and change version to `1.0.0` (we suggest you don't use `v` in front), save/commit.
3. Edit your CHANGELOG.md and change version to `1.0.0` instead of `v1.0.0`, save/commit.
4. Go to https://github.com/HuidaeCho/grav-plugin-markdown-yalinker/releases/new for drafting a new Release and just type `1.0.0` in the Tag Version field. You can add a title and descriptions too, they are optional.

This should get your versions in line, in the future when you need to do a release it will be pretty much the same process, except for the deletion part that won't be needed.

More info: https://learn.getgrav.org/16/advanced/grav-development#theme-plugin-release-process

**Comment by HuidaeCho** [comment]
Thanks for checking. I did it again.

**Comment by w00fz** [comment]
Looking good! It's now in GPM.

Cheers
