### ISSUE TITLE
Twig tag for script file doesn't work with group option

### ISSUE THREAD

**Issue by PixelT** [getgrav/grav#3084]
Grav v1.7.0-rc.17
I define a JS file in template using `script` tag:

```
{% block javascripts %}
    {% script 'theme://js/function.js' in 'bottom' priority: 100 %}
{% endblock %}
```
Then I want to call this group
```
{% block bottom %}
    {{ assets.js('bottom')|raw }}
{% endblock %}
```
It doesn't work and return an error in console:
`Uncaught SyntaxError: Unexpected token '<'` in line 1

When I'm using old version of adding script:
```
{% block javascripts %}
    {% do assets.addJs('theme://js/function.js', 100) %}
{% endblock %}
```
everything works correctly

**Comment by mahagr** [comment]
@PixelT This will be fixed to the next Grav 1.7 release. One thing though, use `at` instead of `in` as it was a poor choice because of it's meaning was: `{% script ('theme://js/function.js' in 'bottom') priority: 100 %}`, meaning it tested if the filename matches bottom.

Updated also documentation on this.
