### ISSUE TITLE
Unable to upgrade Grav

### ISSUE THREAD

**Issue by PeopleInside** [getgrav/grav#3090]
Hi, after the latest release I'm unable to upgrade:

Argument 1 passed to Grav\Plugin\Admin\Gpm::_downloadSelfupgrade() must be of the type array, null given, called in /user/plugins/admin/classes/gpm.php on line 370

**Comment by filippomasoni** [comment]
I have a similar problem when trying to upgrade from 1.6.29. Via the cli I get this error:

Error while trying to download (code: 302): https://getgrav.org/download/core/grav-update/1.6.29

**Comment by PeopleInside** [comment]
As I cannot upgrade admin plugin and Grav I'm asking how to upgrade manually.
Some instructions?
Let's see if someone reply, maybe just need have patience.

**Comment by PeopleInside** [comment]
resolved just trying and trying than download start, error dispeared

**Comment by filippomasoni** [comment]
I just tried upgrading from the admin and it worked, upgrading to the newly released 1.6.30 so I guess your problem is different. I usually upgrade from cli to avoid potential issues, I found it usually works best, not sure why this time it did the opposite.

To upgrade manually follow this guide (which is what I always do): https://learn.getgrav.org/16/cli-console/grav-cli-gpm
If you have problems try clearing the all the cache manually: https://learn.getgrav.org/16/cli-console/grav-cli

As a good practice, backup before an upgrade, I always push to git, and then upgrade. This way if something goes wrong you can just reset before the upgrade, clear cache, and try again without losing anything.

**Comment by PeopleInside** [comment]
I cannot and want use SSH

**Comment by mahagr** [comment]
The issue was in builds failing, it went away when builds finally finished successfully.
