### ISSUE TITLE
markdown extra does not work as documented

### ISSUE THREAD

**Issue by cord** [getgrav/grav#317]
the old setting `markdown_extra` seems to override `markdown.extra: true`

**Comment by rhukster** [comment]
fixed!

**Comment by giansi** [comment]
Hi,
this fix seems not to work, in fact, using the latest release, I'm not able to activate markdown extra at all. it seems that the first condition isset($this->markdown_extra) cannot never be false, due to default configuration setting, so the full condition always returns false.

Restoring the code before the fix, works for me.

**Comment by flaviocopes** [comment]
you're setting it in system.yaml, or in a page header?

**Comment by flaviocopes** [comment]
p.s. `system.pages.markdown_extra` is deprecated, use `system.pages.markdown.extra`

**Comment by giansi** [comment]
Ok. That works. Thank you
