### ISSUE TITLE
Modular content with missing template file ending up using non-modular template

### ISSUE THREAD

**Issue by mahagr** [getgrav/grav#3218]
If a modular template file is missing, Grav ends up using the default page type, thus replicating the whole HTML multiple times inside the document.

**Comment by pamtbaau** [comment]
As a side effect, every non-existing template is being replaced with `user/themes/<theme>/default.html.twig` instead of `/system/templates/default.html.twig` which contains a proper error message. 

When working on a discourse question about switching themes, it took me a while to figure out why a non-existing template was displayed using `default.html.twig` instead of using the `/system/templates/default.html.twig`.

I think issues with non-existing templates should not be hidden and `/system/templates/default` should be shown instead.

**Comment by mahagr** [comment]
It's not possible to do that as twig doesn't tell us where the file comes from. So if it's inside a lookup path, it gets picked up.

**Comment by pamtbaau** [comment]
IMHO a missing template is an unexpected exception which the developer/admin should be notified about in an early stage. Currently the exception is buried which is confusing and makes the issue hard to detect.

**Comment by mahagr** [comment]
I tend to agree, but we cannot do that because many sites rely on showing default template with custom filenames.

What we could do, though, is to make this a configuration option. Maybe you should create a new issue about it?
