### ISSUE TITLE
Value of  the "routable" variable of the page header has no effect.

### ISSUE THREAD

**Issue by maxlysenko** [getgrav/grav#322]
Page header variable `routable` does not affect the corresponding page attribute.

![img_20150914_163548_](https://cloud.githubusercontent.com/assets/12494082/9851266/741427f4-5b00-11e5-941a-888654775fd2.png)

**Comment by rhukster** [comment]
Not entirely sure what i'm looking at.  but the header value doesn't always set the internal state of the Page 100% 1 to 1.  For example for modular pages, you can set that to be routable, but the internal code will override this and set the internal state to be routable=false because modular pages cannot be routable.

**Comment by maxlysenko** [comment]
Ok, I just thought that `page.routable` for the error page should return `false` and that if I set `routable: false` in header for some (non modular) pages the following statements:
``` twig
{% for child in page.children.routable %}
...
{% endfor %}
```
or
``` twig
{% for child in page.children if child.routable %}
...
{% endfor %}
```
will work.
But they don't work, they list all pages including those for which I set `routable: false`.

**Comment by rhukster** [comment]
Ok now you have provided some more information, i can test that scenario.

**Comment by rhukster** [comment]
Well, there was a legitimate issue that I introduced in the last version with some refactoring.  This should be sorted for the next release.  Thanks!
