### ISSUE TITLE
Page Text cut off

### ISSUE THREAD

**Issue by NicoHood** [getgrav/grav#3223]
Checkout this:

```
---
process:
    twig: true
---

Falls du den Link mit einem Logo auschmücken möchtest findest du diese unter [Werbemittel](/werbemittel). Wir werden deinen Vorschlag zeitnah prüfen und einpflegen. Bei weiteren Fragen [**schreibe uns einfach eine Email.**]({{ theme_var('contact_url') }})
```

It will render as (Highlighted the error):
> Falls du den Link mit einem Logo auschmücken möchtest findest du diese unter **[Werbemittel](/kontakt)rüfen** und einpflegen. Bei weiteren Fragen [schreibe uns einfach eine Email.](/kontakt)

* The Text is cut off
* The first Link is wrong, the 2nd link is used for some reason

I can imagine that this was introduced by https://github.com/getgrav/grav/issues/3162

**Comment by mahagr** [comment]
It looks like the Markdown parser didn't like the twig tags. This was an issue even without the twig turned on, so not result from the previous bug fix.

Please do not use twig inside markdown syntax as markdown gets by default parsed first, which causes the content to potentially break. In this case, I made the temporary value look like a URL so it works, but basically, the value coming from the twig will not be parsed correctly by Markdown (is it instead used as it is). 

In cases like this, it may be a better idea to either use HTML instead of markdown around the twig or make Grav parse twig first.
