### ISSUE TITLE
[add-resource] New Plugin/Theme

### ISSUE THREAD

**Issue by DennisdeBest** [getgrav/grav#3294]
I would like to add my new plugin/theme to the Grav Repository.
Here are the project details: **DennisdeBest/grav-plugin-pre-publish**

**Comment by DennisdeBest** [comment]
https://github.com/DennisdeBest/grav-plugin-pre-publish

**Comment by pamtbaau** [comment]
@DennisdeBest, I took a look at your plugin and I'm afraid I do not quite understand its purpose. Just to confirm my understanding:
- In `onPageInitialized`, the page is checked if its rawRoute matches the slug mentioned in the plugin's config value `filter:items:'@page': /blog`
  - If page matches `/blog`,  the plugin registers event `onCollectionProcessed`
- In  `onCollectionProcessed`, the plugin loops through all pages in the collection
  - If page is `published` and its `publish_date` is in the future, the page is removed from the collection.

Correct?

Isn't that how Grav works by default? If a page's `publish_date` is set to be in the future, the collection defined in page `/blog` will not contain that page. Unless variable `published` is explicitly set to `true` which overrides `publish_date`.

See the docs about header variable [published](https://learn.getgrav.org/17/content/headers#published):
> By default, a page is published unless you explicitly set published: false or via a publish_date being in the future, or unpublish_date in the past. Valid values are true or false.

The only situation in which the plugin will remove a page, is when the user explicitly marks the page as `published` and adds a `publish_date` in the future.

If that is the sole purpose of the plugin, I would watch event `onAdminSave` and correct the settings if the page is created/updated in Admin, instead of each time when the page is initialized.

**Comment by DennisdeBest** [comment]
Thanks for your reply !
Indeed I did not think of it in that way. 
I have just tried it out and if `published` is not set at all (so neither true nor false) it will indeed take in account the published_date to check if the page has to be in the parent's page collection.

This means that for now this is pretty much an overlay of something already in place and is not very usefull. I was thinking of adding cron jobs to publish tweets and facebooks posts automatically when the published date has been reached so I will come back to this when that is in place.

I tried checking the page URL on `onPluginsInitialized` this however did not work for me and would always return a 404. I will run it again and find some more information.

I think for now this "plugin" issue can be closed and I will create a new one when some more custom features are added.

**Comment by pamtbaau** [comment]
**Enabling plugin**
In `onPluginsInitialized` you cannot check for the page's url, since the page hasn't been initialized yet. You check instead the requested URI.

```
public function onPluginsInitialized()
{
    ...
    if ($this->isOnRoute()) {
        $this->enable([
            'onPageInitialized' => ['onPageInitialized', 0],
            'onTwigTemplatePaths' => ['onTwigTemplatePaths', 0],
        ]);
    }
}

private function isOnRoute(): bool {
    $uri = $this->grav['uri']->uri();
    $routes = $this->config->get('plugins.' . $this->name . '.routes');

    $enable = $routes && (
        (gettype($routes) === 'string' && $routes === $uri) ||
        (is_array($routes) && in_array($uri, $routes)));

    return $enable;
}

```

**Comment by DennisdeBest** [comment]
Thanks for the clarification.

I will keep this in mind. This was my first attempt at a plugin for Grav, I will be more careful in the futur and make things more explicit before submitting anything else.

Sorry to have wasted your time.

**Comment by pamtbaau** [comment]
No need to apologise, my time has not been wasted... I learned something new!
