### ISSUE TITLE
Remove composer.lock?

### ISSUE THREAD

**Issue by NicoHood** [getgrav/grav#3375]
When developing with grav locally I use the git version to easily switch between different versions and patches. Sometimes I need to update the composer dependencies. The lock file will be updated with this action. Now on a git pull or a new grav version this causes conflicts.

I am not that expert, but from my understanding this file should be added to the gitignore and removed from the repo, right?

**Comment by mahagr** [comment]
We have the lock file to ensure that everyone uses the same version of dependencies. In the past, we didn't have the lock file which caused a lot of problems where code didn't work for some due to incompatibilities.

I think that once I've also had an issue with a release where a new version of a library was just published and build scripts ended up making a broken package due to version change.

So the short answer is no, it will not be removed to ensure that everything works. Use `composer install` instead of `composer update`.

**Comment by NicoHood** [comment]
Thanks!
