### ISSUE TITLE
`blueprints()` function: infinite loop

### ISSUE THREAD

**Issue by masetto** [getgrav/grav#3386]
Hello,
in a custom plugin in Grav 1.6 I had this code:

```
$grav_user = $this->grav['accounts']->load('my_user');

$grav_user['login'] = 'my_user';
$grav_user['fullname'] = 'John Smith';

$data['access']['site']['login'] = true;

$grav_user->update($data);
```

Now, in Grav 1.7, the call to the merge function causes a infinite loop: the problem is in function `Grav\Common\User\DataUser\User->blueprints()`… but I don’t know why.

**Comment by mahagr** [comment]
Loop in blueprints usually happens if you call it too early before some blueprints have been initialized. I think it is related to some fields, for example, if the field needs a list of pages, etc.

If you have custom fields, try removing those one by one until you find the one that causes the loop. Another possibility is to try to move the code to a later event if it's possible.

**Comment by masetto** [comment]
@mahagr, I don't know why, but after rebuilding my project with a fresh grav install, the problem has not recurred.
I close this issue. Thank you for your reply.
