### ISSUE TITLE
Using @page: / to get collections

### ISSUE THREAD

**Issue by stell** [getgrav/grav#341]
It would be a great to be able to get all pages by using @page: / 
Also to be able to get not only children of the current hierarchy level but all beneath it when using @page: /level2.

**Comment by rhukster** [comment]
I have added support for this via:

https://github.com/getgrav/grav/commit/077ba28706f38ea00804f4c39644e34e40ff0b71

Basically you can now get the root page with:

```
content:
    items: 
        '@page': '@root'
```

This is because `@page: /` is actually an alias to the homepage, and the homepage may have children but is not really the root of all pages. The homepage could could be any page in grav as it's configurable.

Also I added support for an extra param like this:

```
content:
    items: 
        '@page': ['@root', true]
```

When set to true, all pages below will be included.  This also works for regular pages:

```
content:
    items: 
        '@page': ['/blog', true]
```

Combined with the new multi-collection support (https://github.com/getgrav/grav/issues/361), page collections are now much more flexible.

Docs will be updated after this release

**Comment by stell** [comment]
Sounds great! Will check it out soon. Thanks!
