### ISSUE TITLE
Forbidden error with Cloudfront CDN / ServerPilot / Apache

### ISSUE THREAD

**Issue by Mehditerranee** [getgrav/grav#3413]
Hi,

I am trying to setup a Cloudfront CDN.
However, I get an error as you can see here : https://deya3mlcjkmrf.cloudfront.net/ 
It seems to be related to hosting software configuration i.e Grav or ServerPilot

I suspect ServerPilot and a missing config on it, but i didn't find anything about it.

Any idea?

### My Website config : 

**EC2 + ServerPilot + PHP7**

**Amazon Machine Image (AMI)**
Ubuntu Server 20.04 LTS (HVM),EBS General Purpose (SSD) Volume Type. 64 bits (x86)

**EC2 instance type**
t2.micro

**Comment by mahagr** [comment]
It looks like the error comes from Apache. So you must have some misconfiguration in the server. Check your logs as the error suggested.

**Comment by Mehditeranee** [comment]
@mahagr 

ServerPilot actually configures Nginx on my server as a reverse proxy in front of Apache. More about the configuration [here](https://serverpilot.io/docs/how-serverpilot-configures-your-lamp-stack/).

It appears that there are rules added in the .htaccess file within my app that may be causing compatibility issues with CloudFront. Perhaps, I will contact CloudFront to see what rules may be causing any issue with their service.

That being said, I'm also seeing the following errors being generated within my **Apache error logs**:
```
[Mon Jul 26 00:29:57.419245 2021] [autoindex:error] [pid 19846:tid 140447125018368] [client 20.94.210.46:0] AH01276: Cannot serve directory /srv/users/mehdigallois/apps/mehdigallois/public/user/themes/mytheme/: No matching DirectoryIndex (index.php,index.html,index.htm) found, and server-generated directory index forbidden by Options directive

[Mon Jul 26 00:29:57.568566 2021] [autoindex:error] [pid 19704:tid 140447338563328] [client 20.94.210.46:0] AH01276: Cannot serve directory /srv/users/mehdigallois/apps/mehdigallois/public/user/themes/mytheme/css/: No matching DirectoryIndex (index.php,index.html,index.htm) found, and server-generated directory index forbidden by Options directive
```

The above error being logged is because someone is trying to access that directory directly, which does not have an index file in it, and so a 403 forbidden error is generated.

I don't understand why it try to access to this directoryand not to the root.

You can check my htaccess file here.
[htaccess.txt](https://github.com/getgrav/grav/files/6877772/htaccess.txt)

Any idea?

**Comment by rhukster** [comment]
Just jumping in here, but did you ever confirm that your site worked _without_ cloudfront enabled? Are you sure its cloudfront that causes the issue, or perhaps the server was never working properly before you enabled it?

**Comment by rhukster** [comment]
BTW your apache log errors are probably caused by this in your `.htaccess`:

```
# Begin - Prevent Browsing and Set Default Resources
Options -Indexes
DirectoryIndex index.php index.html index.htm
# End - Prevent Browsing and Set Default Resources
```

I would back up your htaccess, and use the default `.htaccess` that came with Grav. That should work just fine with serverpilot as we've used it before without any issues.  Then add the additional parts back chunk-by-chunk, checking to make sure things are still working as expected.

**Comment by Mehditeranee** [comment]
@rhukster My site worked well without cloudfront enabled.
BTW, it is working well with cloudfront enabled as you can see here: http://13.37.46.163/

I tried to use the default .htaccess that came with Grav and the result is same: https://deya3mlcjkmrf.cloudfront.net/
 I get the feeling that whatever we do on the `.htaccess`, it has no impact on cloudfront cdn. (still 403)

**Comment by Mehditeranee** [comment]
Maybe one of the configs is pointing to the wrong place. As in the nginx is trying to access the wrong, non-root, directory on the apache, or the config files for one of the other elements in the chain.

**Comment by Mehditerranee** [comment]
**✓ I solved this issue ✓**

A 403 is being returned, as that request from CloudFront is being made to `ec2-13-37-46-163.eu-west-3.compute.amazonaws.com`:

```
52.57.254.217 - - [26/Jul/2021:22:57:40 +0000] "GET /favicon.ico HTTP/1.1" 403 461 "-" "Amazon CloudFront" "46.140.111.92" 340 0.001 "859" "0.000" "ec2-13-37-46-163.eu-west-3.compute.amazonaws.com"

[Mon Jul 26 22:57:40.153019 2021] [access_compat:error] [pid 19703:tid 140447217338112] [client 127.0.0.1:20034] AH01797: client denied by server configuration: /opt/sp/apache/htdocs/favicon.ico
```

The solution is simply to add `ec2-13-37-46-163.eu-west-3.compute.amazonaws.com` as a domain to my ServerPilot app.

<img width="325" alt="Capture d’écran 2021-07-27 à 16 19 47" src="https://user-images.githubusercontent.com/38721898/127170473-a1427a95-2d83-45d8-8ff8-e01bbfcfe0d5.png">


And voilà!

**Comment by rhukster** [comment]
Did you find a solution???

**Comment by pamtbaau** [comment]
Would you mind updating your post on [Discourse](https://discourse.getgrav.org/t/forbidden-error-with-cloudfront-cdn/17722/2) to allow the community to benefit from your solution?
