### ISSUE TITLE
Star rating error after my update 7.4.3

### ISSUE THREAD

**Issue by mrtngrsbch** [getgrav/grav#3433]
Hi,

I have upgraded to the latest version 7.4.3 and now I get an error when trying to save any page.

![image](https://user-images.githubusercontent.com/693328/131773185-47d5d77f-554b-4fd6-86af-85b4716ad34d.png)

**Comment by mahagr** [comment]
https://github.com/getgrav/grav/commit/7a1f5539ed074ab664b5dea348893337c3d18920 should fix the issue.

**Comment by TheoAcker12** [comment]
This doesn't appear to be fully fixed. I didn't test all possible options, but with negative numbers, negative minimums, and high precision, number validation has issues. This is apparently because php's fmod function has issues (the code would be accurate if fmod were accurate).

An example failure is a value of -81.36802 with a minimum of -180 and step of .00001. Interestingly, a value of -81.26208 with the same parameters if perfectly fine, though if you up the step precision to .0000001 the situation reverses.

I'm going to use the previous code `return !(isset($params['step']) && fmod($value - $min, $params['step']) === 0);` for now, since that was working. Is there some issue with the previous code that required it to be changed?

**Comment by mrtngrsbch** [comment]
> Which plugin are you using for star ratings?

I don't have any stars plugin

**Comment by mahagr** [comment]
Well, we do have integer check, let me try that one as fmod() seems to be broken beyond repair....

**Comment by mahagr** [comment]
@TheoAcker12 Now it should work!
