### ISSUE TITLE
[add-resource] New Plugin/Theme

### ISSUE THREAD

**Issue by LuanHimmlisch** [getgrav/grav#3434]
I would like to add my new plugin/theme to the Grav Repository.
Here are the project details: **LuanHimmlisch/grav-plugin-crypto-ticker**

**Comment by pamtbaau** [comment]
@LuanHimmlisch, I've taken the liberty to take a look at your plugin. The ticker is show correctly, however, there is some room for improvement:

- The code is manually calling function `$this->autoload()`. Please note that Grav will automatically call `autoload()` when the plugin is registered. There is no need to call it manually.
- Event 'onGetPageTemplates` is being registered to add Page templates, however, it seems no page templates are actually being provided, nor being used. The event registration could be removed.
- Event `onTwigTemplatePaths` is being registered inside eventhandler `getSubscribedEvents()`, however, this event only needs to be handled when Twig is being called to generate the front-end page. A better place would be to register the event in function `onPluginsInitialized()`.
- Event `onPagesInitialized` is being registered, but its handler is empty.
- The provided css sets the `width` of class `crypto-ticker-wrapper` to 100%. This will force the ticker outside any column set by a grid system used by a theme (eg. Quark).
- I think the ticker could be designed a tad more pleasing to the eyes out of the box. Like, for example:
![Untitled](https://user-images.githubusercontent.com/5120011/132322414-afeee929-9884-4a86-93d4-085c6c0bb2e8.png)
instead of:
![Untitled](https://user-images.githubusercontent.com/5120011/132322920-2ebe74e7-8867-45b5-a100-65b84cc48fc1.png)

**Comment by LuanHimmlisch** [comment]
@pamtbaau I don't really know how the column system work but the width shouldn't overflow the container. Anyways, if it doesn't work as you say, can you tell me what should I set the width to?

**Comment by pamtbaau** [comment]
@LuanHimmlisch, The `crypto-ticker-wrapper` is a `div` which is a `block-level element`, which according to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Block-level_elements):

> A Block-level element occupies the entire horizontal space of its parent element (container), and vertical space equal to the height of its contents, thereby creating a "block"

If you remove `width: 100%` at line 2 of *crypto-ticker.css* the ticker will take the width of the column defined by the theme. For more info on grid frameworks, see for example: [Bootstrap](https://getbootstrap.com/docs/5.1/layout/grid/) or [Spectre](https://picturepan2.github.io/spectre/layout/grid.html) (used by Quark)

**Comment by LuanHimmlisch** [comment]
@pamtbaau I know what a block-level element is, I'm a frontend developer. I was asking specifically for the column system, if this is how the system says then it's not different to any other container, and width 100% shouldn't overflow.

Here, if you insist: https://codepen.io/LuanHimmlisch/pen/gORLNeO

Also, are you part of the Grav team? Thanks for your help on the Grav API, but  on what frontend matters I would like to listen a frontend developer or a  team member .

**Comment by rhukster** [comment]
You can’t rely on any included css framework. In Grav every theme is fully independent and can use whatever framework it wants.  Usually our approach is to have some included css in the plugin that is very specific and provides any needed css. Then we have a toggle to disable including this css to allow people to take the provided css and include it in their theme and customize it to fit the design.

**Comment by LuanHimmlisch** [comment]
@rhukster hello! Yeah, I agree. That's exactly how I did it.

Then I'll commit the fixes of the Grav API and are we ready to go? Thanks

**Comment by rhukster** [comment]
Sorry, i've been super lax on this, will be catching up this week.

**Comment by rhukster** [comment]
Added for next GPM update.

**Comment by LuanHimmlisch** [comment]
Hehe, thanks!
