### ISSUE TITLE
Failed to save file security.yaml in vendor/rockettheme/toolbox/File/src/AbstractFile.php

### ISSUE THREAD

**Issue by leonheess** [getgrav/grav#3458]
I followed the documentation but I'm getting this: 

    Uncaught RuntimeException: Failed to save file /var/www/test.tld/user/config/security.yaml in /var/www/test.tld/vendor/rockettheme/toolbox/File/src/AbstractFile.php:369

I followed the troubleshooting recommendation and tried:

```
chown -R joeblow:staff .
find . -type f -exec chmod 664 {} \;
find ./bin -type f -exec chmod 775 {} \;
find . -type d -exec chmod 775 {} \;
find . -type d -exec chmod +s {} \;
```

But it doesn't help. I'm using CentOS 8, PHP 7.4.19 and nginx 1.14.1.

**Comment by mahagr** [comment]
It does sound like that your server is using different permissions for your user. Apache usually uses something like www-data as the user and group, so you may want to tweak the permissions of the files or change the apache user for the site to yours.

**Comment by leonheess** [comment]
@mahagr Thanks for the fast response! I'm using nginx - how could I verify and solve this issue? I'm very new to Grav.

**Comment by mahagr** [comment]
You can try to temporarily set the folder/file permission to be world-writable -- if the error goes away, you will at least know for sure where the issue is.

To fix it, it really depends on the server and generally means changing the permission settings either for your server or user (or both). The easiest fix would be to create one site per user and just give nginx the same user and group. Try googling on how to do that in your server environment.

**Comment by leonheess** [comment]
I'm on CentOS 8 if that is relevant

**Comment by leonheess** [comment]
Could this be connected to the fact that these directories are all empty?
