### ISSUE TITLE
[add-resource] New Theme Future 2021

### ISSUE THREAD

**Issue by pmoreno-rodriguez** [getgrav/grav#3481]
I would like to add my new theme to the Grav Repository. 

This is the totally redesigned Future Imperfect theme, with new functionalities, templates, expanded SCSS, built-in dropdown menu functionality and totally redesigned sidebar menu.

I would like to bring it into the Grav repository as a new theme: Future 2021
Here are the project details: [https://github.com/pmoreno-rodriguez/future2021](https://github.com/pmoreno-rodriguez/future2021)

**Comment by pamtbaau** [comment]
@pmoreno-rodriguez, I'm guessing you have created this theme with `auto-escape: false` since you've forgotten some `| raw` filters in many places eg. `{{ page.content }}`, `{{ assets.js('bottom') }}`, etc...

Maybe a good idea to test the theme on a fresh installation of Grav first.

**Comment by pmoreno-rodriguez** [comment]
Fixed autoescaping in all twig templates.

**Comment by pamtbaau** [comment]
@pmoreno-rodriguez, I'm afraid you've missed a few spots...

- `{{ ....html() }}`
- *user/themes/future2001/templates/partials/blog_item.html.twig* line 66

**Comment by pmoreno-rodriguez** [comment]
Fixed all the twig templates (now I hope so), and added the "disable" class for the pagination.html.twig buttons when it is the first or last page.

**Comment by pamtbaau** [comment]
Let's move the discussion into your own repo...

**Comment by pmoreno-rodriguez** [comment]
Hello.

The old Future Imperfect theme has not been maintained for a long time, it is not updated and some of the functionalities that it claims to have are not implemented, such as the dropdown menu, as well as others that it has and that no longer work, such as the call to likes from facebook using JSON. However, in the new [Future 2021](https://github.com/pmoreno-rodriguez/future2021) theme, these problems have been corrected and the dropdown menu functionality has been added, both in the top menu and in the sidebar.

In addition, new templates have been included, such as the portfolio, banner, features or contact. The style sheets have been improved and the SASS files have been expanded and improved to fit the updated HTML5Up base theme.

Consider including this theme in the Grav theme repository, to offer users a better experience with Grav.

Thanks.

**Comment by pamtbaau** [comment]
After further reviewing the theme, I'm afraid I'm not that enthusiastic. I see too many red flags that make me question the quality of the theme. I would not add this theme if the choice were mine.

#### UX related:
- The original theme is a blog oriented theme. Template 'base.html.twig' builds a typical blog page with a sidebar containing featured posts, last posts, about, socials etc.. 
This also means that any page type using 'base.html.twig' like default.md, modular.md, form.md, error.md also look like a blog page. 
- Every page has two menus: a menu in the header and the same menu in a slide-in panel. The header-menu is only shown on larger screens. My first impression was that the slide-in panel menu should be removed on larger screens when header-menu is shown. However, the slide-in panel is permanent and also contains items like relatedposts, archives, taxonomylist and login button. What exactly is the purpose of the slide-in panel?  A menu for mobile, or an extra sidebar? Why show the menu when the header menu is visible?
- It feels as if the original theme has become a patchwork of new features without considering the impact on UX.
I agree, this might just be a debatable issue related to taste.

#### Coding
- "God template": All code for sidebar and slide-in panel (with menu and blog related plugins) are in `bases.html.twig` instead of using separate partials for eg. sidebar, slide-in panel, macros.
- DRY: Newly added templates portfolio, single and offline (to a lesser extend) are almost exact copies of `base.html.twig`.
- Invalid HTML: `{% block bottom %}` ,which adds assets and scripts, is placed between `</body>` and `</html>` in several templates.
- File `future2021.php` is an exact copy of `quark.php` including its overrides of form classes. However, the overriding classes are not used in any scss/css file. I wonder if the purpose of the code is understood.
#### Maintenance
- It seems OP does not have a separate develop environment from which commits with proper descriptions are pushed to Github. Changed files are uploaded to Github, all with the same commit message "Add files via upload". This makes it hard to search in the history of files.
- Since this request has been created, approx. 140 new commits (file uploads) have been uploaded to the theme. Is the theme in production or still in alpha/beta stage?

#### License
- The original HTML5 UP themes are licenced under the "Creative Commons Attribution 3.0 License". I wonder if it is allowed to wrap a CC-A license inside a MIT license with its own copyright statement.

**Comment by pmoreno-rodriguez** [comment]
Hi @pamtbaau 

First of all, thank you very much for your criticism and suggestions. I will be happy to correct anything necessary to make this theme better. I have to confess that I am a newbie in many aspects related to web programming, Grav and GitHub.
I will take into account each and every one of your suggestions, starting with making sense of each section of the theme, as well as making separate templates for those blocks that are necessary.

I will need some time for this, because first I have to learn a few more things about programming with Twig, PHP, etc. But surely with reviews as detailed as yours you can improve this template.

Greetings.

**Comment by pamtbaau** [comment]
> I have to confess that I am a newbie in many aspects related to web programming, Grav and GitHub.

> [..] because first I have to learn a few more things about programming with Twig, PHP, etc.

Above was already noticed from the code and Discourse, but it felt too offensive to mention it as a red flag in public. It took me a couple of days of doubt and hesitation before publishing my "not-so-nice-message" anyway...

I wonder however, why would one want to publish a theme to the community, if one knows one's limitations? And also nudging the devs to publish it quickly...

You could at least notify the devs about your skills level and ask for proper review/feedback. A review/feedback could also be asked for on Discourse. You're not the first nor the last one starting from ground zero...

**Comment by pmoreno-rodriguez** [comment]
Hi @pamtbaau 

How about you take a look at the code, after correcting it following your suggestions?. 

I have proceeded to fork the original theme and have made the changes there. 
[https://github.com/pmoreno-rodriguez/grav-theme-future](https://github.com/pmoreno-rodriguez/grav-theme-future).

Thanks so much.

**Comment by pamtbaau** [comment]
@pmoreno-rodriguez, I'm afraid I need to protect my boundaries a bit... 
- I sometimes do reviews here on new plugins/themes in the hope of relieving the dev team a bit.
- However, I cannot be called upon to do reviews in order to improves someone's work or skills.

I did take a look at your updated version and could add some new comments, however, I would like to refer back to my previous [comment](https://github.com/getgrav/grav/issues/3481#issuecomment-985398651) which I made in response to your statement of being a newbie in web development:
> I wonder however, why would one want to publish a theme to the community, if one knows one's limitations?

To elaborate on that:
- Publishing a theme/plugin to the community should not be taken lightly. It comes with a responsibility. Users put their trust in it for their websites.
- Publishing a theme/plugin is not a way to improve ones skills/knowledge. One should already be proficient in coding.
- Publishing a theme/plugin is not the proper stage for getting reviews. Getting a theme/plugin reviewed belongs to earlier stages in development.

I know I impose quite strict quality rules on myself about what I produce and deliver and I realise I might impose that on others too. If I'm being to harsh or strict here, I apologise.

I happily leave the final decision in the hands of the team.

**Comment by pmoreno-rodriguez** [comment]
Hello. First of all, I appreciate your honest feedback. I just wanted to be able to help the grav community improve some of their themes without long-standing support. I will consider all your suggestions in the future. However, I will keep the theme repository active in case the Grav team wants to take it into account for future updates on the GitHub fork [https://github.com/pmoreno-rodriguez/grav-theme-future](https://github.com/pmoreno-rodriguez/grav-theme-future) . I will keep learning so I can improve it.

**Comment by pmoreno-rodriguez** [comment]
Original Repository for Future Theme updated in
[https://github.com/absalomedia/grav-theme-future](https://github.com/absalomedia/grav-theme-future)

**Comment by rhukster** [comment]
Is this cleaned up with the suggestions from @pamtbaau ?  I see the repo has changed from the original.  The Grav team doesn't have time to review/critic themes, so we have to rely on community members (such as @pamtbaau) to help out here.  I think he's done a great job BTW by pointing out some key issues that needed to be addressed.

BTW, like your other theme you will need a release for it to show up in GPM.  I've added both of your themes now, but they are currently commented out of our repo as they have no releases.

**Comment by pmoreno-rodriguez** [comment]
Hello
I just sent a message to @absalomedia to release a new version for the Future theme, in the original repository, which is already updated according to my repository at https://github.com/pmoreno-rodriguez/future2021.
In my repository the version of the theme is 1.0.7 while in the original repository of the theme (https://github.com/absalomedia/grav-theme-future) the version is 1.0.9.

I hope @absalomedia can release this version in the next few days.

**Comment by pmoreno-rodriguez** [comment]
Hi,
I've create the first release for this theme, again.

I expect this time all works fine to be added to Grav repository.

Thanks

**Comment by w00fz** [comment]
Ok it's added. Hopefully it will get picked up by GPM if everything looks good.
