### ISSUE TITLE
[add-resource] New Plugin 

### ISSUE THREAD

**Issue by dallaslu** [getgrav/grav#3514]
I would like to add my new plugin/to the Grav Repository.
Here are the project details: **[dallaslu/grav-plugin-spacer](https://github.com/dallaslu/grav-plugin-spacer)**

It brings [Spacer.js](https://github.com/dallaslu/spacer.js) (Demo: <https://dallaslu.github.io/spacer.js>) to Grav.

**Comment by pamtbaau** [comment]
I've taken the liberty to have a look at your new plugin. I cannot comment on its functionality, since I have no idea about the effects of combining Chinese and other languages.

#### spacer.php
- You have defined event handler 'onTwigSiteVariables()' in which you do not add any Twig variables, but instead only add assets. Although not wrong, it would be more correct to add assets at 'onAssetsInitialized'.
- The code has some issues with legibility. Especially where JavaScript strings are being created. A tad more white space between lines and proper indentation would improve legibility.

#### spacer.yaml
- You have defined field 'method' in *blueprints.yaml* including a default, description and options. Not everyone is using Admin to configure a site. Therefor, fields defined in *spacer.yaml*, should also have a proper default and description (including options).

#### README.md
- Please replace all "todo" templates with proper content.
- Add explaination of setting 'method'.

#### Generated css/JavaScript
- It seems to me that both *css/spacer.css* and *js/spacer.js* have been generated.
- Since this is opensource, it would be nice if the origin of the css/js files and their build script were included in the repo of the plugin. This would make it easier for the community when forking the plugin, or creating pull requests.

#### Conclusion
- Not yet ready for release.
- Although your personal slogan is "Too lazy to write anything.", I would like to encourage you to spend a tad more time to improve the plugin before it should be released.

**Comment by rhukster** [comment]
I've add this to the Repo but as @pamtbaau mentioned, there are several places that could do with some cleanup.
