### ISSUE TITLE
Recommended way to deal with Git in an "adminless Grav install"?

### ISSUE THREAD

**Issue by Rolf-Smit** [getgrav/grav#3515]
I was trying to figure out what the best way is use Grav is when you use it without the admin plugin, basically as a flat-file CMS that you deploy through Git.

I found that most people advice to just commit the `user` folder, but I found a few problems with that approach:
 
- I don't want to reinstall Grav every time I pull the Git repo on a new machine, I need some sort of build script. Obviously I can run the `composer create-project` command every time, but it feels counter intuitive.
- I want my environment to be consistent (in which Grav version is used, but also plugin versions)
- It's kinda strange to commit the `user/plugins` folder, normally you don't modify those files yourself. However I understand it is not part of Grav either.

**Wouldn't it be nicer to just have a build script that pulls the exact version of Grav needed, and also installs the required plugin versions and theme versions?**

I created something like that as a simple bash script (that at least solves the first issue):

```
#!/bin/sh

# Remove current install
rm -rf webroot

# Clone grav
php composer.phar create-project getgrav/grav webroot 1.7.26.1

# Install grav
cd webroot
bin/grav install

# Remove default user directories that we will replace with our own
rm -rf user/accounts
rm -rf user/config
rm -rf user/data
rm -rf user/pages
rm -rf user/plugins
rm -rf user/themes

# Create symlinks from our own user directories to the webroot/user folder
ln -sf ../../user/accounts user/accounts
ln -sf ../../user/config user/config
ln -sf ../../user/data user/data
ln -sf ../../user/pages user/pages
ln -sf ../../user/plugins user/plugins
ln -sf ../../user/themes user/themes
```

**This works and I could probably extend it to include plugin and theme installs as well, however is there a recommended way to work with Git when I use Grav without the admin plugin?**

> I could not get this build script to work with a `composer.json` then symlinking to the vendor folder. But if someone can tell me how that can be done let me know.

> _Unrelated thing which I find really strange (I'm not a web or PHP developer, but do mostly JVM and C based languages), is that packages (plugins) include the full repository sources (Grav as well). Tests, unrelated readme files etc. are all pulled. To me that feels extremely wasteful, especially if you are used to JVM packages etc. But this is probably more a general Composer issue than it is a Grav issue._

**Comment by w00fz** [comment]
The best approach is the first point you mentioned with only user in the repo. It might sound counterintuitive but you’ll find yourself able to manage better Grav updates.
It’s also good for separating local development from production instances of Grav.

Then you could integrate something like GitSync (https://github.com/trilbymedia/grav-plugin-git-sync) for the git synchronization, which expects only the user folder in the repo. Although it has a lot of user friendly implementation for the admin, it is not admin dependent and you can synchronize manually or via cronjob via the simple `bin/plugin git-sync sync`.
GitSync also supports webhooks so that you can have your site update if you manually push to GitHub. 

The GitSync flow can also be manually reproduced by yourself with some simple scripting where you basically push/pull as needed, and if the user folder only is just too limiting for you, you can push everything.
