### ISSUE TITLE
The admin-side page editor don't work

### ISSUE THREAD

**Issue by Jachimoo** [getgrav/grav#3518]
An exception has been thrown during the rendering of a template ("Cannot load blueprint blueprints://flex-objects/pages.yaml: Failed to read C:/xampp/htdocs/user/plugins/recaptchacontact/blueprints/default.yaml: Non-string keys are not supported. Quote your evaluable mapping keys instead at line 26 (near "false: PLUGIN_ADMIN.DISABLED").").

Mirror of error:  https://niewolnicysys.azurewebsites.net

**Comment by w00fz** [comment]
The error comes from one of your plugins “recaptchacontact”, Grav is only forwarding the error.

https://github.com/aradianoff/recaptchacontact

I’m not familiar with that plugin but seems it hasn’t been updated in quite a while.
I suggest you either stop using that plugin or try to fix it for your needs.

This portion of the yaml file is the culprit. You could try changing to 0 and 1 instead of false and true.

```yaml
options:
  false: PLUGIN_ADMIN.DISABLED
  true: PLUGIN_ADMIN.ENABLED
```
