### ISSUE TITLE
[bug] home_url missing trailing / (slash) on home

### ISSUE THREAD

**Issue by kittyfishfrommars** [getgrav/grav#3798]
Grav version 1.7.44 and 1.7.43

From the [docs](https://learn.getgrav.org/16/themes/theme-vars#home-url-variable):

> The [home_url](https://learn.getgrav.org/16/themes/theme-vars#home-url-variable) is particularly useful to use to link back to the homepage of your site. It is similar to [base_url](https://learn.getgrav.org/16/themes/theme-vars#base-url-variable) but takes the currently active language into account.

**Description:**

On home (index) `{{ home_url }}` returns the home_url _without_ trailing / slash: `https://localhost/mysite` returns `/mysite`

On subpages a trailing slash is correctly added: `https://localhost/mysite/subpage` returns `/mysite/`

**Expected output**:

On home (index) `{{ home_url }}` returns the home_url _with_ trailing / slash: `https://localhost/mysite` returns `/mysite/` 

Impact: Consistency - this becomes  a concern when the site should be crawled by search engines, or re-written by static-site generators.

Current workaround: extend template php to add a slash, if needed. See:  [oxygen.php](https://github.com/kittyfishfrommars/grav-theme-oxygen/blob/fb25d8d0d3479247ff43611552993f9da61d93ab/oxygen.php#L14)

**Comment by rhukster** [comment]
Search engines and browsers treat URLs with or without a trailing slash the same.  If you asked someone to type a URL they woud never add a trailing slash to the URL, so in general it's simpler and easier to have a URL without the trailing slash.

I think the rule of thumb weather you use a trailing slash or not is to be consistent.  If you don't use a trailing slash, then consistently don't use it.  I don't think forcing a trailing slash is a good idea because for most people they don't use it.  Best to go with the common use case, and not have it.

**Comment by kittyfishfrommars** [comment]
@rhukster: You are right about consistency.

Please take note that the current implementation of  `{{ home_url }}` in Grav 1.7.45 is inconsistent:
- Home does not add a trailing slash to the URL
- Subpages do add a trailing slash

`wget --no-parent` [requires](https://superuser.com/questions/290682/recursive-download-of-subfolder-with-wget-no-parent-apparently-not-working#answers) trailing slashes.
