### ISSUE TITLE
Outdated / incompatible dependencies

### ISSUE THREAD

**Issue by Rotzbua** [getgrav/grav#3829]
## Problem

Some issues state problems with newer php version. This could be caused by the outdated dependencies.
So far it seems most dependencies could be updated to a newer version without the need to increase the current grav php requirement of >=7.3.
I think this overview is useful for @rhukster .

## Dependencies

Used `guzzlehttp/psr7` v1 does not officially support php>8.0
https://github.com/guzzle/psr7/tree/2.6.2?tab=readme-ov-file#version-guidance

`monolog/monolog` v1 does not officially support php>8.1
https://github.com/Seldaek/monolog/tree/3.6.0?tab=readme-ov-file#requirements

Used `symfony/*` v4 is EOL since 21 Nov 2022.
https://endoflife.date/symfony

Used `twig/twig` v1 is EOL since 28 Sep 2022.
https://endoflife.date/twig

`dragonmantank/cron-expression` v1 are outdated since 2017. Current v3 available.

`composer/semver` used v1 not updated since 2020. Current version v3 available.

`symfony/service-contracts` not used at all. #3828

**Comment by rhukster** [comment]
Some of these have already been addressed, but i've also updated the rest in Grav 1.8 branch.

Thanks!

**Comment by rhukster** [comment]
I am already working on Twig3 support but has some compatibility issues with themes and plugins.  I’m trying to mitigate these as much as possible.

**Comment by rhukster** [comment]
Actually it looks like the problems with the Deferred Twig extension is going to be major problem with Twig 3.  Seems they changed the architecture in Twig 3.9 (and all previous versions were removed), and Deferred extension no longer works.  To compound the issue, it doesn't seem like the author is interested in finding a solution, and the team closed the issue stating that because Deferred extension was doing 'weird stuff' under the covers, they had no interest in supporting it in the newer version of Twig 3. (https://github.com/twigphp/Twig/issues/4026)

This is a huge issue for Grav as we rely on that functionality to support plugins or themes that load asssets into the Asset Manager via partial Twig files.  We use this technique extensively to load stuff from form form fields and other twig 'chunks' outside of the base page template that extends the base twig.   I'm sure 3rd party plugins and themes do this also.  There's no easy way around this, as it means you have to change themes/plugins to load CSS via the PHP to ensure they are all ready in the assets object when the template renders.  It would be a huge backwards compatibility issue with no easy solution. 

I just dont have time to dig into the Twig internals and familiarize myself with it enough to find a solution for Twig 3. So I think it's Twig 2.8 as the latest version we can move to.  Will need to be forked as-is to properly support PHP 8.4. Grr....

**Comment by Karmalakas** [comment]
> It would be a huge backwards compatibility issue with no easy solution

@rhukster, what about Grav 2.0? 🙂
I mean it's a breaking change. If someone is using plugins, that do not support the change, can stay on Grav 1.7/1.8, can't they? I would gladly update my own plugins to get rid of `deferred` (if I have any 🤔) if Grav team would decide to update all of their official plugins. If I had time, I might help (no promises though)
