### ISSUE TITLE
bundled composer

### ISSUE THREAD

**Issue by naomik** [getgrav/grav#383]
Why does `grav` bundle `bin/composer.phar` on its own ?

Usually, if you're going to distribute a composer package, you'd just ask the user to

```js
$ composer require getgrav
```

Trying to be clever by magically managing composer and dependencies seems like you're stepping on developer toes instead of actually making things easier.

Rather than feel blessed there's a unique way to interact with grav and dependencies, I feel annoyed that  conventional tool chains weren't used and there's now a composer redundancy on my system.

I feel like composer should be separated from `grav` core and perhaps make a `gpm` a separately installed module or maybe make a `grav-nerf-mode` for people that have no idea what they're doing.

Just thinking out loud...

**Comment by rhukster** [comment]
Grav actually will use a user installed composer before it falls back to the one that is bundled with it.  There are several commands and features that use composer to update libs, so it if there is none installed, it will use the one bundled rather than just fail and tell you to install your own.  

This is particularly useful for many windows users that typically don't already have composer installed and are already scared enough of the command line that any extra steps are a huge turn off.

**Comment by rhukster** [comment]
I'll  close this for now.  Feel free to reopen it if you have any more questions or perhaps ways to improve the process.  Thanks!

**Comment by naomik** [comment]
This is well and good, thank you for the explanation :+1:
