### ISSUE TITLE
Menu icon rendered on homepage only

### ISSUE THREAD

**Issue by pboguslawski** [getgrav/grav#3832]
[Menu icon](https://github.com/getgrav/grav/blob/c97a0ffb161856c48571a3d79771f62acd4640f8/system/config/site.yaml#L32) is rendered on homepage (modular) only and not on the other pages (i.e. blog). Noticed in quark theme.

**Comment by pamtbaau** [comment]
That is by design in Quark theme.

If you want the custom menu items to be shown in regular/default pages, you'll need to copy the logic from *modular.html.twig* (See [/templates/modular.html.twig#L34-L41](https://github.com/getgrav/grav-theme-quark/blob/c427627daa301ba09d61ab15f34109f680ff7ba7/templates/modular.html.twig#L34-L41)) into partial */templates/partials/navigation.html.twig*
