### ISSUE TITLE
Updating (admin)plugin 30 seconds timeout

### ISSUE THREAD

**Issue by teodorsandu** [getgrav/grav#385]
Hi, trying to update admin plugin I get a "Maximum execution time of 30 seconds exceeded"  meaning the plugin wasn't updated successfully, and as result, the whole admin area is throwing a woops error "One of the required plugins is missing or not enabled". The installation is from http://getgrav.org/downloads (GRAV CORE + ADMIN PLUGIN) on localhost.

**Comment by flaviocopes** [comment]
Make sure Login, Form and Email plugins are installed. You can also install them from the command line.

**Comment by teodorsandu** [comment]
> Make sure Login, Form and Email plugins are installed

They were installed, by default
I re-installed all by unzipping again and copying my user account file from the old installation.
I raised this issue because it might be good to increase maximum execution time (set_time_limit) when updating plugins. Also wanting to inform that unsuccessful update of a plugin will break the admin interface

**Comment by flaviocopes** [comment]
Thanks for pointing that out, will keep this open

**Comment by stephanfriedrich** [comment]
Hi, the same issue here if i save a new or updated page. 
this generates an 96% occupancy rate for my old bananaPi.

**Comment by rhukster** [comment]
This could be related to the fact that we had not updated the 'clean' command recently. This means that the bundled vendor folder is full of extraneous stuff like tests, docs, etc.  I've updated this and re-released admin+email plugins which should now have smaller packages. It might just be overloading your pi because PHP unzip is not the most efficient thing.
