### ISSUE TITLE
Suggestion: why not have theme related plugin settings inside of theme folder?

### ISSUE THREAD

**Issue by nerijusgood** [getgrav/grav#428]
I believe it would make sense to have plugin setting files in the theme folder. For example a lot of plugins have their css files included by default and if my theme provides styles for, lets say, pagination I need to create plugin config file in, probably (differs by plugins, also annoying), `user/config/plugins/` folder. 

The issue is if I have few themes and I want to swap them on occasion, I need to modify those config files. Wouldn't it make sense to have theme related settings in theme folder. In addition it would be easier to install new themes without having to add extra settings. 

Also, plugins, should have standardized rules on where, how to use config files and template file overrides: some plugins have config files directly in  `user/config/` some in `user/config/plugins/`; template files sometimes are located directly in `templates/` folder while sometimes in 'templates/partials/`. 

This is just a suggestion.

**Comment by rhukster** [comment]
i'll have a think about this.  Thanks!

**Comment by rhukster** [comment]
Regarding the location of things I can definitely clarify that a little.

All plugins can have a configuration file called `pluginname.yaml` in the root of the plugin.  E.g. `user/plugins/pluginname/pluginname.yaml`

There is only one location supported for this.  You override the plugin configuration by putting a similar file in your `user/config/plugins/` folder, e.g. `user/config/plugins/pluginname.yaml`.

That is consistent for all plugins and will "just work".  However, In Grav YAML is converted into a PHP array, so you could theoretically have a `user/config/plugins.yaml` file that contains configuration for all plugins as long as in that file you have format like this:

```
pluginname:
  enabled: true

anotherplugin:
  someoption: false
```

This is because both methods effectively create a php array of the same format. However, for simplicity I always advocate the first method of having a folder called `plugins` and putting individual plugin configuration files in there.

Regarding Twig templates, every theme has a `templates/` folder that is the location of the Twig templates.  Plugins can also have a similar `templates/` folder although the naming is not as critical there as actually register this location in your plugin.  The important thing is that there is really only one main folder level that you register with Twig.  

Page files have a template associated with them, and those are are requested from the Twig setup simply as `default.html.twig` (for example).  These would then have to sit at the top level to be found.

As a naming convention, top level templates that render a page, should be at this top level.  Parts that are used to render one of these top level pages, should be put in `templates/partials/`.  But there is nothing hardcoded to say this is the folder to use, the theme's templates just load `partials/somepartial.html.twig` and so they are looked for in the partials sub directory.

Most plugins have partials because they are Twig bits of a greater page.  Although some plugins such as **feed** has top level Twig templates because they are actually used to render the entire page as an XML RSS feed.

Hope that sheds some light on those parts :)

**Comment by nerijusgood** [comment]
This makes sense. Thanks for clarification, tho I would love to bundle theme with plugin settings.

**Comment by rhukster** [comment]
I'm still thinking about that part :)

**Comment by rhukster** [comment]
Ok, so i've thought about this and here are my thoughts:

While it could be possible to add support to look in the theme for a plugins.yaml file that was then merged with the plugin configuration, I think this could lead to more problems than it resolves.  There could be unpredictable results for the user where plugins all of a sudden change their behavior without any clear indication of how or why this is happening.  Also it could change a a configuration setting that the user explicitly set for the plugin.  It just opens up a can of worms that could potentially lead to more errors.

The better solution is to create a **skeleton** package that contains sample pages for the theme and configuration for the site, plugins, etc.  We do this already for a variety of our themes for this very reason.  It provides a ready-to-run package for the user.

Usually skeleton repos contain the basics of the `user/` folder, without the actual plugins nor the theme.  It has a `.dependencies` file that contains references to the Git repos where these can be obtained.  This allows you to download the skeleton and insert it as the `user/` folder, then run `bin/grav install` to obtain the dependencies.  The resulting site should 'just run'.  

The release package should be the entire site include Grav etc.  You can see some of our skeleton packages for reference.
