### ISSUE TITLE
Theme autoloading doesn't seem to work

### ISSUE THREAD

**Issue by sowebdev** [getgrav/grav#432]
Hello,

I ran into an issue when trying to extend the Antimatter theme. I followed the steps from the tutorial but at the end I got an error : 

    E_WARNING - include_once(/home/me/myproject): failed to open stream: No such file or directory

I did some debugging and found out that there is a problem in \Grav\Common\Themes::autoloadTheme().

Method is called with argument "Grav\Theme\Antimatter" and tries to load a file "/home/me/grav/user/themes/Antimatter/Antimatter.php" which is not all right since theme directory names are lower case.

The $file variable evaluates to false but it seems that stream_resolve_include_path() doesn't return false but the path to the root of the project. This results to include_once() beeing executed with a wrong path and leads to this crash.

This code should probably use file names in lower case but maybe there could be another way to do this such as using the configuration.

**Comment by rhukster** [comment]
@sommerregen do you mind looking any this?

**Comment by Sommerregen** [comment]
@rhukster Yes, I will do this.

@sowebdev Thanks for the detailed investigation and since you mentioned this you are totally right that the directory name should be lowercase. Unfortunately on my local install (this error didn't come up...). In the end I guess we only have to change one line namely https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Themes.php#L287. Can you try to use this at line 287

```php
$path = strtolower(ltrim(preg_replace('#\\\|_(?!.+\\\)#', '/', $class), '/'));
```

instead?

**Comment by sowebdev** [comment]
@Sommerregen Thanks for your fix, tested it, it will work :-)

**Comment by rhukster** [comment]
Thanks!
