### ISSUE TITLE
Not working with spaces in GRAV_ROOT

### ISSUE THREAD

**Issue by cabrero** [getgrav/grav#463]
It doesn't find content neither themes when GRAV_ROOT directory path contains spaces.

**Comment by rhukster** [comment]
I'm having trouble replicating this.. I created a subdir called `/grav test/` and put a grav instance in there.  And was able to reach it no problem with `http://localhost/grav%20test/`

Also admin plugin seems to work fine, so no problems with routing. Can you provide more info as to the exact nature of your problem???

**Comment by cabrero** [comment]
El domingo, 22 de noviembre de 2015, Andy Miller <notifications@github.com>
escribió:

> I'm having trouble replicating this.. I created a subdir called /grav
> test/ and put a grav instance in there. And was able to reach it no
> problem with http://localhost/grav%20test/
>
> Also admin plugin seems to work fine, so no problems with routing. Can you
> provide more info as to the exact nature of your problem???
>

Inside grav instance I have a symbolic link from user/ to  $HOME/Dropbox
(madsgroup)/foo/bar/user
When I change the link to another dir whithout spaces in the path,
everything works ok.

But, at the time I'm writing, I realise I have not check whether the
problem is the space or the '(', ')' chars.


-- david

**Comment by rhukster** [comment]
I can't replicate this.  I have tested with both spaces and parenthesis in my webroot.  After adjusting my webserver config so it could find the new path, everything worked fine.

Also i've tried changing a subdirectory with Grav installed so that it had both spaces and parenthesis, and after replacing spaces with `%20` it worked fine too.
