### ISSUE TITLE
Canonical header (routes.canonical) works like alias (but in reverse)

### ISSUE THREAD

**Issue by mikkosalo** [getgrav/grav#479]
Using routes.canonical on pages header (http://learn.getgrav.org/content/headers#routes) causes a problem.

If you have a page whose slug is for example: `example-page` and another page with slug `another-example-page`. Now you add canonical header tag for a `another-example-page` like this:
```
slug: another-example-page
routes:
    canonical: '/example-page'
```

If you now go to url `http://yoursite/example-page` Grav shows content from `another-example-page`, and gives it canonical link `<link rel="canonical" href="http://yoursite/example-page" />`. However, in this situation it should give this canonical link only for a `another-example-page`, and do nothing for `example-page`.

Is this a bug or am I understood something wrong?

**Comment by rhukster** [comment]
Your providing an example with an intentional conflict.  if there are pages with the same routes, then the first one grav comes to will be used.  The pages are added to Grav in order they are discovered as they are traversed recursively through the filesystem.  As pages are found, all aliases, canonical, and default routes are added to the routes table with a reference to the page in question. 

So when a particular route is passed via the URL, the routes table is searched in order until a match is found.  When a page is found, if a canonical link is explicitly defined, it will use that rather than the default route to render the canonical link.

Your example makes sense in this case. 

Really the only solution to your problem is to ensure you don't have a route conflict like this.
