### ISSUE TITLE
changelog

### ISSUE THREAD

**Issue by grangeway** [getgrav/grav#496]
When updating, and selecting to read changelog - only show the change log since your current release rather then the whole file.

**Comment by rhukster** [comment]
Why? I always like to see the whole changelog.

**Comment by grangeway** [comment]
if you are on 1.0.0rc5, and evaluating yes/no to upgrade at command prompt to 1.0.0rc7 for example - at that point, you'd only care about fixes/features that will be new after updating. "Is this a minor/major upgrade, am I hitting any of the issues this update fixes, do i need any of the new features".  [FWIW, I was looking at command prompt upgrade at the time].

**Comment by rhukster** [comment]
Oh i see during GPM install. I guess that is possible.  I'll leave this here to remind me to investigate.

**Comment by w00fz** [comment]
Changelog has already a smart logic in place to only show the difference based on your current version and what you are going to upgrade to.
So if you are on `rc3` and you are about to download `rc5`, you will get the changelog for `rc4` and `rc5`.

However, this all stopped working once we started releasing release candidates, due to a bug in the code that was only considering digits. I have now fixed it with dc8c0b6 and it should be back to the way it was!

![gpm selfupgrade php 2015-12-02 23-42-33](https://cloud.githubusercontent.com/assets/11734/11554686/15ad2c82-994f-11e5-970b-843db1440d8e.png)
