### ISSUE TITLE
No routes available in the CLI :-/

### ISSUE THREAD

**Issue by CoolGoose** [getgrav/grav#499]
```
protected function serve()
{
    $pages =  self::getGrav()['pages'];
    $routes = $pages->routes(); 
    $this->output->writeln(var_export($routes, true));
}
```

```
-bash-4.1$ php bin/plugin staticgenerator log
array (
)
```

Any chance to be able to get the routes so I can export the site with twig ? :+1:

**Comment by rhukster** [comment]
The CLI only has the basics to get at configuration and such.  The whole of Grav is not run, so that means the pages are not processed.

My suggestion is that in your method, you mimic what is being don in Grav itself and create a new Pages object, then call:

```
$pages->init();
```

There might be more involved to get that all working but all the code that Grav uses is there, so it should be easy to track down what's required.
