### ISSUE TITLE
disabling sessions from admin plugin kills the site

### ISSUE THREAD

**Issue by webstersx** [getgrav/grav#504]
I'm using the latest 1.0.0 rc6, and learn2 theme.

I disabled sessions in my site configuration, and pretty much killed the site as soon as I hit save.

Spent a couple minutes trying to figure out how to configure it back on but gave up and uninstalled, reinstalled admin plugin and re-created user.. still didn't work so I wiped and re-started from base skeleton

**Comment by flaviocopes** [comment]
Can you define "pretty much killed the site"? Which error you got?

The Admin plugin will not work with sessions disabled, so it needs to be active. As soon as you turn it off, the plugin will give an error.
Also, if you had the Login plugin (and you had, since the Admin plugin was installed and it depends on Login), you probably had an error in the frontend because the Login plugin needs sessions.

If you disable the Login plugin, the frontend will work.

The system configuration is saved to user/config/system.yaml. Just find the `session.enabled` property and set it to true to re-enable sessions.

**Comment by rhukster** [comment]
Sessions are required for admin/login to function.  I'll see if we can separate the admin side from the user side, but probably that will prove difficult.  We might just have to remove the option from the admin, and leave it as something only available via editing the config file directly.

**Comment by rhukster** [comment]
Sessions enable/disable has been removed from admin.
