### ISSUE TITLE
Multiple markdown files within a folder [feature request]

### ISSUE THREAD

**Issue by acki-m** [getgrav/grav#506]
I need to put a lot of md files (200) into one folder, because the the contained links are all relative to the current folder. I cannot change this.
I also want to avoid creating artificial folders. Because the md files are created offline by another tool, which can contain more or less files. I batch copy these files then into one folder.

Unfortunately, grav does not support containing multiple md files in one folder.
I don't see why this limitation exist? Without this limitation, I don't need to write a plugin to load my files by my self.

**Comment by rhukster** [comment]
Can you put these files in a folder outside of `user/pages`? Maybe something like `/user/files`.  I assume you just want to be able to link to these to download?

Grav is built around the concept of parsing markdown files in the user/pages folder.  It's going to look for everything that is a `filename.md` type format.  It will even look for multiple files to see if they are for other languages.  However, you could use another extension like `.mdown` or `.markdown` or something, and then Grav would ignore them.

**Comment by acki-m** [comment]
I want that grav creates from these md files pages. So no, these files are not for download.

This is my workaround for loading the content of html files via a plugin. I want to use the build in functionality of grav.

**Comment by rhukster** [comment]
then nope, this won't work as you want it.  You would have to create a separate folder for each page, as to Grav a 'page' is a folder + markdown file. The both of those are essential.

**Comment by acki-m** [comment]
it would be nice to know, why this is essential?
I have a plugin which makes this step;creates grav pages from html files, which are placed in one folder.
You have to explain the why.

**Comment by rhukster** [comment]
I did already.  Grav looks for a markdown file in the folder to represent the page.  It finds the first markdown file and uses that.  If you have multi-language enabled, it will look for appropriately named files for each language.  

The folder dictates the slug of the page, the file dictates the template.  These can be overridden by the frontmatter, but the fact of the matter is that each 'page' in Grav consists of a folder with a file in it.  We use a folder because it's nice to have multiple translations, media files, etc associated with the page. 

You can try hacking Grav to make it work with multiple files, but i have no interest in changing this most fundamental architectural decision.
