### ISSUE TITLE
asset manager not picking up modular assets after first page load

### ISSUE THREAD

**Issue by benblee** [getgrav/grav#507]
If you add js or css assets to a modular twig template, they only get picked up for the first page load after clearing cache. After refreshing a couple of times, they don't get picked up anymore.

This can be tested by moving an asset line from ```/partials/base.html.twig``` to a modular template file, clearing cache, then loading the page.

I believe this is the same for plugins, but it seems most plugins like [SimpleSearch](https://github.com/getgrav/grav-plugin-simplesearch) load the js inline, or the js is loaded sitewide and enabled/disabled like in [Featherlight](https://github.com/getgrav/grav-plugin-featherlight). I haven't really tested with plugins yet, so only sure about modular pages.

**Comment by rhukster** [comment]
This is really an intentional limitation in how modular pages work.  

In short, a modular page is processed during the call to `content()` of the parent page.  The results of this page is cached into the parent's finished page content.  While this is cached, the modular page is not even communicated with on subsequent calls.  The only real way to get around this is to turn off the caching of the parent page and force the content to be recreated with each request.  

The only way to resolve this would be to have this work 'automatically' would be to force disabling of all modular parent pages, but frankly this is an overkill reaction when you don't need to rebuild those in a lot of situations.  

The solution, Turn off the parent's page caching first, then potentially turn of the page cache of your very dynamic modular page as needed.

Another approach is to move assets up into the Twig of the parent page rather than in the modular page.  BTW this is the approach we use on getgrav.org.
