### ISSUE TITLE
Better i18n slug

### ISSUE THREAD

**Issue by serphacker** [getgrav/grav#522]
We can retrieve other language slugs by prefixing "raw" slug with the lang, like `/fr/blog/post`.

However if we have custom slug for each language of article like `/fr/blog/article-en-francais` and `/en/blog/english-post` we can't retrieve the i18n slugs in the template.

Even if `/fr/blog/post` and `/fr/blog/article-en-francais` point to the same page, that's not SEO efficient (we need a redirect or we have to set canonical url).

it would be usefull to be able to retrieve custom FR slug from EN page, so we can set hreflang and switch language url properly

**Comment by rhukster** [comment]
This is an architectural decision.

In short, to ensure languages do not effect performance, each language runs in a sandbox of sorts.  So when you are in a particular language, Grav knows nothing about other languages.  This is because each language has it's own set of pages, configuration, etc.  One one set of these is loaded at a time. To be able to know what the customized routes are for each page in each language, would require loading every set of pages in every language.  This would slow down the site dramatically for each language installed, as well as significantly increasing memory usage, simply not practical.

The **rawRoute()** is the only way to reliably get a page in a different language. 

However, if you enable the **Redirect to Default Route** option, when it gets to the rawroute page in the particular language, it can then redirect (301 by default) to the default route (which probably has the nice translated title etc). All search engines take these kinds of redirects as a normal course of crawling.  It should not cause any issues.
