### ISSUE TITLE
Plugin and theme use of namespace.

### ISSUE THREAD

**Issue by sturple** [getgrav/grav#529]
I have just started using grav, and so for like it very much, thank you for all the work.
* Is there a reason why namespaces aren't being used for themes and plugins. 
* Are you not limiting yourself by not doing this.
* Also why would you not use https://packagist.org/ as a method of loading resources.  After all you are using composer.
 
Regards,
Shawn.

**Comment by rhukster** [comment]
* What kind of namespacing are you referring to? It can mean many things.
* Composer is being used to managed the vendor libraries that Grav needs to function.  Using packagist for plugins and themes is not idea because the preferred location for these installs is in the vendor folder.  Also it requires that composer run to rebuild the autoloader.  This may not operate reliably on all installations.  

We have discussed the idea that composer could be used by plugins that have a need to add their own vendor dependencies, but composer doesn't support multiple locations, and this would mean a `user/` folder would no longer be self-contained.

The interim solution is to have your own composer.json in a plugin if you require it, and then build the vendor packages out so the plugin can be distributed with everything it needs as-is.

**Comment by rhukster** [comment]
Reponed so you can reply to the first part...

**Comment by sturple** [comment]
I am talking about the themes and plugins for example if i wanted to create an seo plugin it would be called turple/seo, and if yoast wanted to create a seo plugin it would be yoast/seo

**Comment by rhukster** [comment]
just call it 'turple-seo'.  Grav grew somewhat organically and at the start we were creating plugins as we needed them.  We really didn't plan the plugins with huge growth in mind.  Now it's a bit late to change this.  

We will probably address this in the next major revision of Grav, version 2.0

**Comment by ITSecMedia** [comment]
That answers a question that came up here today....
