### ISSUE TITLE
Collection nextSibling() and prevSibling() are Switched (Reversed)

### ISSUE THREAD

**Issue by sturple** [getgrav/grav#531]
When do a page.collection() loop.  I was using the nextSibling() function and found that the sibling functions were reverse.

## Using 
```
bin/grav -V 
Grav CLI Application version 0.1.0
```

## Page YAML
```yaml
content:
    items: '@self.modular'
    order:
        by: default
        dir: asc
        custom:
            - _hero
            - _feature
            - _about-us
            - _announcements
            - _showcase
```

```twig
    {% for module in page.collection() %}
    	<div class="modular-anchor" id="{{ _self.pageLinkName(module.menu) }}" ></div>
        {{ module.content }}
		{% if module.isLast()%}			
		{% else%}		
		<div class="modular-next-nav"><a data-scroll href="#{{ _self.pageLinkName(module.nextSibling().menu) }}">{{module.prevSibling().menu}} - {{module.nextSibling().menu}}</a></div>
		{% endif%}
    {% endfor %}
```

## Results

```
_feature -
_showcase - _feature
_about-us - _announcements
```

**Comment by hotovec** [comment]
@rhukster @sturple Confirming this behavior.

my case
Hey Guys,

seems there is issue with ordering. Here is my case:
a) I have root pages only
```
user/pages/
   01.home/
   02.themes/
   03.features/
   04.pricing/
   05.sign-in/
```
b) all pages don't specify collection in the header. Pages also do not have order parameter there. This is how each page header look like: (with different titles)
```
title: Home
```

c) I have defined order type in system.yaml
```
pages:
  order:
    by: default
    dir: asc
```

asc(0,1,2,3 .....)

d) I'm using antimatter template and this code to pickup my pages
{% set cp = page.parent().children() %}
next sibling: {{ cp.nextSibling(page.path).title }}
prev sibling: {{ cp.prevSibling(page.path).title }}

But my result are inverted. 
For page features (03), I'm getting next sibling page as 02.themes
and previous siblings is giving me 04.pricing

**Comment by hotovec** [comment]
@rhukster I tried Page.php collections like @self.siblings, seems it is also returning reversed results. But depend on sort direction. in case you have desc it looks like OK, but asc direction is reversed.

**Comment by rhukster** [comment]
Ok taken me a while to decipher this.  I think the problem is simply that we chose a different terminology for `previous` and `next`.  

In my thinking, `next` is **up** the list and `previous` is **down** the list.

I don't know if there is a universal way to approaching this, but no matter what, changing how this works now will have dramatic effects on sites that are built expecting the current behavior.  I suggest that if it feels 'inverted' to you, simply change the `dir: asc` to `dir: desc` or vice versa.

If you feel the `nextSibling` and `prevSibling` are inverted, just flip them in your code.  

So how it works now:

Assuming you have the pages:

```
- Project A
- Project B
- Project C
```

You are on `Project A`, the `previous` page is `Project B`.

If you are on `Project B`, the `previous` page is `Project C` and `next` is `Project A`

Just visualize the list vertically and associate `next` with **up** and `prev` with **down** and it will make sense :)

**Comment by hotovec** [comment]
Heh. So. Can you double check that please?

And I do not understand why I should use prevSibling for next page etc....
This is working for Arab countries;)

There in first column is real numbering of folders. At the second and third column are results what you get from GRAV. Seems to me this is not solved and it is not problem of terminology.
And really doesn't matter what is happen somewhere in the background in the code.


```
// Order by default sorting asc

vertical:
Folders             prev result           next result
--------------------------------------------------------
01.home             02.themes             ---
02.themes           03.features           01.home
03.features         04.pricing            02.themes
04.pricing          05.sign-in            03.features
05.sign-in          ---                   04.pricing

horizontal:
01.home - 02.themes - 03.features - 04.pricing - 05.sign-in


What do you suppose you should get as NEXT if you are on page 03.features (first column)?

I mean:
next page to 03.features is page 04.pricing
prev page to 03.features is page 02.themes


// Order by default sorting desc

vertical:
Folders             prev result           next result
--------------------------------------------------------
05.sign-in          04.pricing            ---
04.pricing          03.features           05.sign-in
03.features         02.themes             04.pricing
02.themes           01.home               03.features
01.home             ---                   02.themes


horizontal:
05.sign-in - 04.pricing - 03.features - 02.themes - 01.home

What do you suppose you should get as NEXT if you are on page 03.features (first column)?

I mean:
next page to 03.features should be 02.themes 
prev page to 03.features should be 04.pricing
```

**Comment by flaviocopes** [comment]
Take a blog posts listing:

```yaml
content:
    items: @self.children
    order:
        by: date
        dir: desc
```

The first post has nextSibling `null` and prevSibling is the previous blog post.
So in the blog posts case, a collection order makes perfect sense. It’s a stack, and if you look at it as a stack, it still makes sense. If you think about it in other ways, it’s backwards. Changing the direction does not work unfortunately as in that case the collection first item is the last.

But this cannot be changed in Grav and it must be kept this way for backwards compatibility as it's always behaved like this.

I can suggest to use `page.adjacentSibling(-1)` to point to the next page instead of `page.nextSibling()` to reduce the confusion the terminology might make, you can also define a constant in the theme and use that for better readability, like `page.adjacentSibling(NEXT_PAGE)`

**Comment by hotovec** [comment]
I did patch my Collection and Page nextSibling/prevSibling methods and swap -1/1 values and it is working as I wish. For both type of sorting. So it is my solution. If I have range from 1 to 5.
I will get 4 as next number to 3. :)

**Comment by hotovec** [comment]
Also I do not care which kind of sorting is set somewhere, because it is working. And I do not need care about that somewhere I need use desc and prevSibling to get next value :)
