### ISSUE TITLE
bin/grav install is broken in 1.0.5

### ISSUE THREAD

**Issue by aptly-io** [getgrav/grav#536]
Did someone perform a `bin/grav install` before releasing 1.0.5? 
I get the stack dump saying that `Error` cannot derive from `final class Whoops\Run`. 
It still working in 1.0.4. 
Where are the release regression tests :smile:  ...

**Comment by aptly-io** [comment]
Oops, seems there's a pending pull request ... Might this fix it?

**Comment by flaviocopes** [comment]
It's strange you're having this error. 
Whoops (a library we use) made the Run class `final` in version 2.0. The version Grav installs is 1.1.10, which does not have this problem. 

Whoops 2.0 is the version compatible with PHP 7. Previous versions are not. So we eventually need to update the library version.

We have a PR in place, but since 2.0 requires PHP 5.5, we need to increase the requirements of Grav, dropping PHP 5.4, so we cannot yet merge the PR without prior warnings and checks in place.

**Comment by aptly-io** [comment]
Argh, I'm using HEAD again, not really release 1.0.5 ... just verified that this is working fine. I closed the defect. Sorry for opening this non-issue ...
