### ISSUE TITLE
How to set up Grav on CentOS 7?

### ISSUE THREAD

**Issue by Endogen** [getgrav/grav#574]
I started with a clean CentOS 7 system and wanted to run Grav on it. I ran into the problem that everything in the `bin` folder wasn't executable.
The error:
![error](https://cloud.githubusercontent.com/assets/226475/12050476/7cff461a-aef6-11e5-9f8f-bb13d5165470.png)
The execution rights:
![chmod](https://cloud.githubusercontent.com/assets/226475/12050493/bad7f59a-aef6-11e5-9044-ecc4fda09690.png)

I realized that this is most likely a SELinux problem. So i temporarily disabled SELinux with `setenforce Permissive` and could then install Grav. But i still get this error here:
![gpm-error](https://cloud.githubusercontent.com/assets/226475/12050549/412091f2-aef7-11e5-8b80-f2837c7fd1a3.png)
I get this error everywhere in Grav admin.

I would have two questions:
1) How can i fix this "can not connect to GPM" error?
2) How can i install Grav without disabling SELinux temporarily?

Maybe someone already has some insight into CentOS & Grav and can help me out here? I'm using Grav 1.0.6 bundled with the admin plugin.

**Comment by webfed** [comment]
In which directory did you put Grav?

**Comment by Endogen** [comment]
I put it in `/var/www/html`

**Comment by webfed** [comment]
That should be working. I have several sites on CentOS 6 without problems.

**Comment by webfed** [comment]
I my setup the sites are in /home/domain/public_html and I have set:
Run CGI scripts as domain owner? yes
PHP script execution mode FCGId (run as virtual server owner)

**Comment by Endogen** [comment]
Well, i guess CentOS 6 is not the same as CentOS 7 :)
I should also mention that i had to execute `chcon -R -t httpd_sys_content_rw_t /var/www/html` to even get Apache to read and write in that directory.

**Comment by webfed** [comment]
Did a quick test since I have a fresh CentOS 7 install on a VPS. I placed a Grav skeleton in /var/www/html and got errors too. But different ones ;-)

PHP %s to run.', $ver, $req)); } // Ensure vendor libraries exist $autoload = __DIR__ . '/vendor/autoload.php'; if (!is_file($autoload)) { throw new \RuntimeException("Please run: bin/grav install"); } use Grav\Common\Grav; // Register the auto-loader. $loader = require_once $autoload; // Set timezone to default, falls back to system if php.ini not set date_default_timezone_set(@date_default_timezone_get()); // Set internal encoding if mbstring loaded if (!extension_loaded('mbstring')) { throw new \RuntimeException("'mbstring' extension is not loaded. This is required for Grav to run correctly"); } mb_internal_encoding('UTF-8'); // Get the Grav instance $grav = Grav::instance( array( 'loader' => $loader ) ); // Process the page try { $grav->process(); } catch (\Exception $e) { $grav->fireEvent('onFatalException'); throw $e; }

**Comment by flaviocopes** [comment]
Simply looks to me like PHP not running, it just prints the index.php page: https://github.com/getgrav/grav/blob/2ecebd14b02ec1cbca2fe7aa99b4302563d6103d/index.php does a `<?php phpinfo() ?>` page run?

**Comment by webfed** [comment]
Thanks, looks like PHP is indeed not enabled for the /var/www/html directory
Just tested a Grav site as a virtual domain and everything works as expected.

**Comment by Endogen** [comment]
@webfed do the options you set have something todo with Virtualmin? I'm not using that, i connect via SSH and it's a root server.

**Comment by webfed** [comment]
Yes correct, I installed Virtualmin as root

**Comment by Endogen** [comment]
I'm asking because i'm not sure if the settings you described are relevant only if Virtualmin is used or are generally important.

**Comment by Endogen** [comment]
The PHP version i use is 7.0.0 from the testing repository. Maybe the issue has something todo with that?

**Comment by Endogen** [comment]
Turns out that is really is only a SELinux thing. Setting SELinux to permissive mode with `sudo setenforce Permissive` does the trick for me. But i had that already set previously and it still didn't work but now it does. Maybe i didn't restart apache didn't clear the Grav cache or something. Thanks for the help.

**Comment by Endogen** [comment]
If SELinux should stay enabled, but apache able to execute GPM, then execute `setsebool httpd_execmem on`

**Comment by rhukster** [comment]
FYI i'm going to remove this check from the problems plugin.
