### ISSUE TITLE
Page ordering doesn't work

### ISSUE THREAD

**Issue by openscript** [getgrav/grav#642]
Problem:
![grav-ordering](https://cloud.githubusercontent.com/assets/1105080/12637660/44a88378-c597-11e5-9254-8a9efaa60e50.gif)

Grav versions:
![image](https://cloud.githubusercontent.com/assets/1105080/12637672/5ad4ea7e-c597-11e5-934a-834a5c689d19.png)

Runs on:
PHP 7 & Nginx

**Comment by flaviocopes** [comment]
Works fine for me. Just tested with that theme too.

Caching is disabled?

**Comment by rhukster** [comment]
Maybe the theme is doing some specific ordering?

**Comment by flaviocopes** [comment]
No, I tested with that theme, and ordering worked fine.

**Comment by openscript** [comment]
Caching is disabled. I still cannot get it to work. Maybe I have time to do further investigation in a few days :-)

**Comment by flaviocopes** [comment]
You can send me your user/ folder via Gitter PM and I'll check it out.

**Comment by rhukster** [comment]
@openscript did you ever send a zip of the user/ folder to @flaviocopes ???

**Comment by flaviocopes** [comment]
No never got anything.

**Comment by flaviocopes** [comment]
Got the folder and recreated the issue. The problem is reordering pages which have a folder without a number. Not sure how to handle this, @rhukster. This issue belongs to the Admin plugin.

**Comment by rhukster** [comment]
any page that is not numbered should not be included in the ordering.  I would suggest they appear at the end in the admin.  And yes, this probably should be in the admin plugin issues.

**Comment by lfaoro** [comment]
We're experiencing a similar issue too, whenever we reorder the pages, the `template:` statement from the frontmatter gets deleted for non specific reason.

What could cause this?

**Comment by rhukster** [comment]
This appears to be an issue with template override field specifically - referencing that issue: https://github.com/getgrav/grav-plugin-admin/issues/433

**Comment by rhukster** [comment]
Closing based on inactivity

**Comment by ZYSF** [comment]
I came across the same issue on my site and although the workaround is simple, the behaviour is still really confusing. The page ordering UI could do with an explanation or at least a hint that you should enable numeric prefixes for it to work, otherwise it just feels like a completely broken feature. (I'm using the default theme BTW, and the only thing I can think of that I've customised on these pages is setting "menu" to a shorter title than the default of the page title.)

I'm not sure if the following is strictly related to this issue, or even if it's a bug at all (I don't know what it's meant to be doing), but this is some strange behaviour I noticed while enabling numeric prefixes and I feel like it probably has a related root cause:

When I enable numeric prefixes for one page in a parent folder and then go to reorder pages (from that page's editing UI), that page alone has a menu-looking icon in the reordering UI, but when numeric prefixes are disabled for all pages in that parent folder, they all have that icon.

When I go to a page with numeric prefixes disabled (and another page in that folder has prefixes enabled), the behaviour is inverted, so all of the pages without numeric prefixes have the menu icon and the ones with numeric prefixes don't. Then I find that if I enable it on more than one page it seems to revert to either the initial behaviour (ordered pages having the icon) or simply the current page having the icon.

I'm not even sure if the icon behaviour is repeatable or totally random (I can try again if necessary), or whether the icon is meaningful at all, or whether the icon is always meant to be visible and this is just a theme glitch or something. Looks like the icon represents the page(s) which can be moved, but the behaviour above doesn't make sense in this case (nor does the icon - how about a four-way arrow symbol to represent movability?). In any case, it works fine once all pages in a parent folder have numeric prefixes enabled (in that case, I can only move around the current page, and only it has the icon).

Here are screenshots of reordering UI for 1) page which has just been set to numeric prefix and 2) page in the same parent folder which still has numeric prefix disabled.

![screenshot from 2016-11-30 16-26-38](https://cloud.githubusercontent.com/assets/3704047/20741159/820c0cfe-b71c-11e6-915e-59676899b6f4.png)
![screenshot from 2016-11-30 16-26-54](https://cloud.githubusercontent.com/assets/3704047/20741160/820fcd1c-b71c-11e6-9cdb-ee011c5d8de6.png)

Version details:
Grav v1.1.8
Admin v1.2.4 
Antimatter 2.0.0
(PHP 5.6, nginx, FreeBSD.)
