### ISSUE TITLE
Redirect not supporting query strings

### ISSUE THREAD

**Issue by luqmanrom** [getgrav/grav#676]
I need build a query strings for my redirect path. But it does not working for now
```
routes:
    /test/([^\/]+)/(.*): '/test/job?data=$2'

```

It supposed to use `/test/job` files but due to the query strings, it return not found

**Comment by rhukster** [comment]
not exactly sure what your trying to match? 

Can you give me a concrete example of a URL coming in, and what it should redirect to?

**Comment by luqmanrom** [comment]
What I am basically doing here is, for any url that matches the regex, redirect to `/test/job`. It works that way. But, when I am adding the query strings at the end, it does not work. The problem is not on the regex, but I think on the query strings.

**Comment by rhukster** [comment]
Actually the problem is that the redirects are only consulted if a page is not found.  However, the page is going to be found because it does exists at the route you are asking for.

Either move the the pages to another route, so the redirects can be used, or a better option would be to use .htaccess/rewrite based redirects if you need this kind of functionality.
