### ISSUE TITLE
Admin login fail / Invalid slug set in YAML frontmatter

### ISSUE THREAD

**Issue by rhasqx** [getgrav/grav#733]
Steps to reproduce:
- open the admin page
- create a first account
- logout

The next login will fail:

> Login failed
> Oops there was a problem, please check your input and submit the form again.

```
$ tail logs/grav.log
[2016-03-17 17:39:29] grav.NOTICE: Invalid slug set in YAML frontmatter:  =>  [] []
```

Where do I have to set a valid slug?

I'm using:

- Grav _latest version_
- Apache 2.2.15
- PHP 5.6.18
- CentOS 6.7

Thanks in advance!

**Comment by flaviocopes** [comment]
Very strange! 

Tried with a fresh install of the latest Grav+Admin package, cannot reproduce. Can you try it locally too, to make sure it's not an environment-related issue? Also, the username was lowercase, did it contain any particular character?

**Comment by rhasqx** [comment]
Yep. On my Mac OS X 10.11.3:

**Apache config:**

```
<VirtualHost *:80>
    ServerAdmin webmaster@foo
    DocumentRoot "/Users/rhasqx/workspace/foo/html"
    ServerName foo
    ErrorLog "/private/var/log/apache2/foo-error_log"
    CustomLog "/private/var/log/apache2/foo-access_log" common
</VirtualHost>

<Directory "/Users/rhasqx/workspace/foo/html">
    AllowOverride All
    Options Indexes MultiViews FollowSymLinks
    Require all granted
</Directory>
```

**Terminal:**
```
cd ~/workspace/foo
git clone https://github.com/getgrav/grav.git
mv grav html
cd html
bin/grav install
bin/gpm install admin
bin/gpm install materializer
bin/gpm install googlemaps
sudo chown -R www .
sudo chgrp -R _www .
sudo apachectl restart
```

> Browser:

1. open _http://foo/admin_ and create new admin account & auto login
2. logout
3. login again with username _admin_ and correct password (saved in browser) results in...

> Login failed

```
$ cat logs/grav.log 
[2016-03-17 17:13:52] grav.NOTICE: Invalid slug set in YAML frontmatter:  =>  [] []
[2016-03-17 17:13:56] grav.NOTICE: Invalid slug set in YAML frontmatter:  =>  [] []
[2016-03-17 17:13:58] grav.NOTICE: Invalid slug set in YAML frontmatter:  =>  [] []
```

No pages, no themes. Only plugins: admin, materializer, googlemaps

**Comment by flaviocopes** [comment]
A note, you mentioned "Grav latest version" but since you checkout from Git you're using the `develop` branch, which currently is a bit under work until it's stabilized into `1.1`. Use `master` instead to get the latest published release.
In my last comment I assumed latest published Grav version, `1.0.10`

So I tested the steps you posted, and I can login successfully, typing the credentials manually. 

Chrome for me saved the email as the username for some reason, which might be an unknown issue in `develop`. 
If I let him autofill the wrong values, I got "login failed" AND the log message, which I'll now try to see what could be.

Can you check it's a problem of wrong username stored by the browser auto-fill?

**Comment by rhasqx** [comment]
This is so strange. I cloned the repo again, checked out the master branch, installed the admin plugin, etc -> doesn't work.

So I ended up in downloading the grav+admin.zip. Again, created an admin account, used different email address / password and all I get is (on the production server):

> Login failed
> Oops there was a problem, please check your input and submit the form again.

I'll try again on Sat/Sun...

**Comment by rhasqx** [comment]
To be unable to see the wood for the trees... using the correct username it works. Shame on me, it's my fault.

Thank you very much & sorry!
