### ISSUE TITLE
Twig_Error_Runtime when js_minify foundation.core.js

### ISSUE THREAD

**Issue by tyrion273** [getgrav/grav#766]
Hello,

I think it has to do with this: http://foundation.zurb.com/sites/docs/javascript.html#babel-required

What do you think of integrating Babel?

Olli

**Comment by flaviocopes** [comment]
This is an issue that cannot be solved by Grav itself, see
https://github.com/getgrav/grav/issues/231

The problem is probably in the Javascript file itself, and the library we
use to minify cannot handle it.
I know the Featherlight Grav Plugin causes the same issue.

Faster solution: turn on js pipelining but disable minifying (let the web
server gzip compression do the job)

Il giorno lun 4 apr 2016 alle ore 09:52 Oliver Stapelfeldt <
notifications@github.com> ha scritto:
