### ISSUE TITLE
Environment-Based Language Handling doesn't automatically route users to the correct site-version

### ISSUE THREAD

**Issue by ReneKaesler** [getgrav/grav#772]

**Comment by rhukster** [comment]
Did you follow this guide? http://learn.getgrav.org/content/multi-language#setup-with-language-specific-domains ?

**Comment by ReneKaesler** [comment]
Yes I did. and the redirect from domains containing */en* or */de* to the  corresponding language-specific domain works well. It seems the Automatic Environment Configuration does not work with virtual hosts. Changing any configuration for different environments (for *customerdomain.lde*) is not possible.

**Comment by flaviocopes** [comment]
Right. Currently this is currently not working in localhost testing, while it works on a remote server.

The key is in 

https://github.com/getgrav/grav/blob/develop/system/src/Grav/Common/Uri.php#L160-L173

```php
    private function buildEnvironment()
    {
        // set hostname
        $address = isset($_SERVER['REMOTE_ADDR']) ? $_SERVER['REMOTE_ADDR'] : '::1';
        // check for localhost variations
        if ($this->name == 'localhost' || $address == '::1' || $address == '127.0.0.1') {
            $env = 'localhost';
        } else {
            $env = $this->name;
        }
        return $env;
    }
```

Looking at it, I think the first check is actually wrong because there's a check on `$_SERVER['REMOTE_ADDR']` which is the client IP address, not the server one. I checked, was like this since it was added in https://github.com/getgrav/grav/commit/ce9e955f21b225390d4590fcabf8c03a59d4caf7

So, such environment configuration option never worked in a local testing environment, needed an actual web server.

I posted a PR that should address this: https://github.com/getgrav/grav/pull/773

**Comment by ReneKaesler** [comment]
I've merged your changes to my *Uri.php* as quick&dirty workaround...seems to work :)

Thank you so much for your prompt help!

**Comment by rhukster** [comment]
Closing as i resolved this with a compromise solution that still treats 127.0.0.1 and ::1 as localhost, but uses hostname for environment otherwise
