### ISSUE TITLE
Twig issue

### ISSUE THREAD

**Issue by rbwilkinson** [getgrav/grav#814]
I have installed Grav easily enough. It is simply beautiful. However with some templates I get this error:

RuntimeException (404)
Template "modular/three-columns.html.twig" is not defined.

I need some direction on how to fix. 
Thank you

**Comment by rhukster** [comment]
As [explained in the docs](https://learn.getgrav.org/content/content-pages#page-file), the name of the page in your content 'three-columns.md` dictates to Grav to use a Twig template file called `three-columns.md`.  (This is can be overridden by setting `template: something` in page headers). 

However, there is no requirement for a theme to provide a fixed set of templates, basically a theme provides the templates it needs to render itself.  It's your job to ensure your content is using templates the theme provides.  This allow Grav themes to be very different from standard 'CMS type themes' because there is a tight coupling between theme and content.  I do cover this topic a bit in this blog post: https://www.getgrav.org/blog/traditional-cms-platforms-and-grav

So you just can't toggle randomly between themes and expect your site to be radically transformed, you need to start with a theme you like and build/modify your site with that in mind.  This is why we have skeleton packages available for many themes, they are ready-to-run packages with Grav + Theme + Plugins + Content + Configuration.
