### ISSUE TITLE
Problems rendering {{page.summary}}

### ISSUE THREAD

**Issue by ganar** [getgrav/grav#819]
Hi:

I found that the {{page.summary}} render `<p> </p>` tags around the variable.

I suppose that this has to do with the _markdown_ formatting.

How can I add a class to that  `<p> </p>` tag?, the only way I found around the issue was using `{{ page.summary | striptags}}` and setting my own code around the variable.

**Comment by rhukster** [comment]
That's exactly the case.  The content has HTML tags added by markdown processing. You would have to remove them with Twig probably  You could use striptags, or regex to achieve this.  We have a `regex_replace` filter available which is a pass through for `preg_replace` in PHP (need to get this added to docs)

**Comment by ganar** [comment]
I [added my comment to the documentation](https://github.com/getgrav/grav-learn/commit/96247f05fc6d8724857ba08656662cd0442f1b39), in hopes that someone may find it useful.

`{{ page.summary | striptags}}` works as intended

**Comment by fredrikekelund** [comment]
I found this useful! But I also discovered that there's a problem with this method. Since `page.summary()` generates `<p>` tags without putting a space between them, the `striptags` filter will join the two paragraphs together without a space. I could of course use the `preg_replace` filter, but considering how common it must be to want to use `page.summary` to generate a meta description tag, I think Grav would benefit from an easier way to achieve this. I guess one way would be to ensure that there's always a single space between generated the `<p>` tags generated from the markdown, and another would be to allow passing a second boolean parameter to `page.summary` that makes the method strip away HTML tags if true.
