### ISSUE TITLE
Modify Install directions to include permissions rewriting

### ISSUE THREAD

**Issue by btopro** [getgrav/grav#821]
Hey, awesome project, really impressed. Some install feedback that could go a long way cause I was getting really frustrated -- indicate that grav needs ownership / write access to itself in order to work. This is currently in the docs but it's buried in the "other problems" area. The directions for someone to do a self install, git pull down or zip upload is almost always going to give ownership permissions to the person putting the files up as opposed to apache/iis/etc.

With your bash prompt copy and paste directions for installations something like:
- You may not have to but it wouldn't hurt to make sure permissions to correct, as a step right after upload
- `chmod 775 -R gravcms`
- `chown ${USER}:apache -R gravcms`

At minimum a direct link to the part of the docs from right after install about needing to change permissions.

**Comment by rhukster** [comment]
That step is quite specific to your setup.  On most shared hosting setups, the user account  is the same as the PHP process due to suPHP.  Also on most local setups the webserver is also running with the user account rather than root, so these permissions issues don't come up.  I do outline these permissions issues in the troubleshooting area, but really it's only about 10% of people that are running their own linux servers that face this.
