### ISSUE TITLE
Update datetools plugin to 1.0.4

### ISSUE THREAD

**Issue by paulcmal** [getgrav/grav#925]
[kalebheitzman/grav-plugin-datetools](https://github.com/kalebheitzman/grav-plugin-datetools/releases/tag/1.0.4) v1.0.4 is now available to ensure Grav 1.1 RC compatibility.

**Comment by Sommerregen** [comment]
@paulcmal The `datetools` plugin is properly formatted (has a release). Usually the Grav site picks it automatically between one and two hours. From the repo I see, that https://github.com/kalebheitzman/grav-plugin-datetools/blob/master/blueprints.yaml#L2 has or should be updated, too.

**Comment by flaviocopes** [comment]
Yes, the blueprint needs to be updated otherwise it's not picked up, and once it's done, the version is updated automatically on the Grav site and GPM

**Comment by paulcmal** [comment]
Thanks for the info!

I did not find this information in the [docs](https://learn.getgrav.org/plugins). Could it maybe be added in the plugin tutorial?

**Comment by BugHunter2k** [comment]
@paulcmal Release-Process Docs: https://learn.getgrav.org/advanced/grav-development#themeplugin-release-process

**Comment by flaviocopes** [comment]
Looks like 1.0.5 is correctly tagged, but not updated on the GPM

**Comment by paulcmal** [comment]
Indeed, as pointed out [here](https://github.com/kalebheitzman/grav-plugin-datetools/issues/6#issuecomment-231434572).

**Comment by rhukster** [comment]
Ok, the problem is 2 fold:

1) you started with versions like `v1.0.1` and `v1.0.2` then switched to `1.0.3`, `1.0.4`, and `1.0.5`.

The `v...` versions are taking precedence, so `v1.0.2` is actually getting picked up as latest, however, in that version you never updated the blueprint version: https://github.com/kalebheitzman/grav-plugin-datetools/blob/v1.0.2/blueprints.yaml#L2

So that is why GPM shows `1.0.1` as the latest version.  

**To fix**:  delete the prior release tags `v1.0.1` and `v1.0.2`, and then the `1.0.5` version should get picked up properly.
