### ISSUE TITLE
Out of memory error with new version

### ISSUE THREAD

**Issue by lorddoumer** [getgrav/grav#941]
Hello,

just upgraded to the new version today and suddenly grav stoped working :(
Every time I try to load a page, I goth the message: 

_**Server Error**
Sorry, something went terribly wrong!
E_ERROR - Out of memory (allocated 127926272) (tried to allocate 11028481 bytes)_

I'm on a 1&1 Linux Unlimited shared host – nothing great of course but before the update everything ran smooth, so does anyonee have a idea how to fix this problem? Unfortunately the memory_limit is fixed at 256M, so increasing this is no option ([read here](https://hilfe-center.1und1.de/hosting/1und1-hosting-c10085285/skript--und-programmiersprachen-c10082634/php-c10082686/bedienung-c10082739/welche-php-einstellungen-kann-ich-aendern-a10791899.html))

I really loved Grav thus far – would hate to switch to another CMS :(

Thank you in advance.

**Comment by rhukster** [comment]
Maybe try clearing the cache? Not too much has changed that would cause this and 256mb should be plenty. 

How many pages do you have? Can you provide a zip of your site for me to test locally?

**Comment by rhukster** [comment]
Also what version of PHP are you using? 1and1 should support PHP 7 which is much faster and uses less memory. 

Most likely though you have some bad logic in twig or something that is causing an infinite loop.

**Comment by lorddoumer** [comment]
Hi, 
thanks for your help! First, a little background info: 

- I use a custom theme, which is based on the default antimatter-theme (and not that much modified)
- currently there are 80 pages, most are subpages of a blog-page
- all pages are structured equaly: 2-3 images and a short text
- I used to upload stuff directly from my Android device, since the text is really short – so the images are not modified at all and because of that the zip is quite large
- I'm using PHP 7.0

Here is the [downloadlink](https://drive.google.com/open?id=0B4mfArh9gu4EWGlJbXRZcDg0ZW8). ( I changed the password-hash)
Thanks again for having alook!

**Comment by rhukster** [comment]
Ok, i replicated the exact same problem on my localhost and I have isolated the problem to really 2 things:

![image](https://cloud.githubusercontent.com/assets/1084697/16901355/44e44f64-4bfe-11e6-8903-78e9cfb42967.png)

1. Looking in your pages, I see your images are JPG with a resolution of 4000x2992.  This is very large. When PHP is asked to manipulate an image of this size it first has to convert it to a bitmap, this 5mb file then becomes HUGE. Probably around 50mb, then copies are made in memory taking up even more memory.

2. The second problem is you are using "Related Pages", this plugin runs through the `content()` of every page in your system to compare the content to see which pages are good matches.  Now when you call the `content()` method on a page, it does all those image manipulations too.  So all those manipulations on every page are being run the first time through (which is why you get that timeout on first load, but not second).  After the first load, the content is cached, and it's not required to process again.


SOLUTION:

First use **smaller images**.  I did a  batch image conversion of all images in user/pages to a max width of 1920px which is plenty big enough.

Second, I would **disable related pages** entirely.  I think I need to re-look at this plugin anyway and perhaps only compare the 'raw' content and not the processed content.  It will not be able to match things that are pulled in by twig, or other plugin related things, but it will mean things are MUCH faster. But until that happens, this is just not going to work for you, as you have too many large images for it to handle well.

**Comment by lorddoumer** [comment]
Wow, thank you for your detailed answer!
I underestimated the image thing a bit, also tried a version with smaller images on one article but didn't work – and the related pages problem is a good tip: this alone helped a lot! Still I'm gonna scale down the images and work with smaller versions in the future.
Thank you very much :-)

**Comment by lorddoumer** [comment]
quick update: scaled down all images (now all together only have 98mb instead of 850mb) and deactivated related pages, now its working fine again, yeah!
but the simplesearch plugin also runs out of memory, when searchign within the blog-items. not a big deal, but maybe it can be optimized..
