### ISSUE TITLE
Summary with size: 0 don't work on modular pages

### ISSUE THREAD

**Issue by egormkn** [getgrav/grav#991]
Dear developers,
First of all, thank you so much for a great, fast and flexible CMS! 

I found a bug with summary delimiter on modular pages: 
created a modular page template:
**.../templates/modular/test.html.twig**
````
{{ page.summary }}
``` 

and added a new modular page with summary header and summary delimiter:
**.../_test/test.md**
```
---
title: Test
summary:
    enabled: true
    format: short
    size: 0
---

Summary text

===

Content text
```

On regular pages it prints only summary text (as expected), but on modular pages this prints both summary and content . Also, when `summary.size` > 0, `page.summary` returns truncated content, ignoring delimiter. Just tested it on a skeleton with Antimatter theme. Could you fix this, please?

**Comment by rhukster** [comment]
Ok i've investigated this and it seems to work as expected. The major difference is that with modular pages, the output is processed through the Twig template first, so that is important.

I created a very basic modular twig template:

```
<div style="border: 1px solid #f00;">
{{ content }}
</div>
```

Then I created two pages, one regular and one modular with basically the same content

---
    title: Modular Test Page
    summary:
        enabled: true
        format: short
        size: 0
    ---
    
    Summary Text
    
    ===
    
    Content Text

and output the `.summary()` for both:

![summary with size 0 don t work on modular pages 991 grav 2016-09-07 10-59-14](https://cloud.githubusercontent.com/assets/1084697/18321176/22aa9a10-74ea-11e6-9a20-63fbfd5cc4eb.png)

Output is as expected.
